// Code generated by protoc-gen-go. DO NOT EDIT.
// source: appserver.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AppServerDeviceProfile struct {
	DevEui               string               `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	ApplicationId        int64                `protobuf:"varint,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Name                 string               `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AppServerDeviceProfile) Reset()         { *m = AppServerDeviceProfile{} }
func (m *AppServerDeviceProfile) String() string { return proto.CompactTextString(m) }
func (*AppServerDeviceProfile) ProtoMessage()    {}
func (*AppServerDeviceProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_2566523af06a975e, []int{0}
}

func (m *AppServerDeviceProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppServerDeviceProfile.Unmarshal(m, b)
}
func (m *AppServerDeviceProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppServerDeviceProfile.Marshal(b, m, deterministic)
}
func (m *AppServerDeviceProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppServerDeviceProfile.Merge(m, src)
}
func (m *AppServerDeviceProfile) XXX_Size() int {
	return xxx_messageInfo_AppServerDeviceProfile.Size(m)
}
func (m *AppServerDeviceProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_AppServerDeviceProfile.DiscardUnknown(m)
}

var xxx_messageInfo_AppServerDeviceProfile proto.InternalMessageInfo

func (m *AppServerDeviceProfile) GetDevEui() string {
	if m != nil {
		return m.DevEui
	}
	return ""
}

func (m *AppServerDeviceProfile) GetApplicationId() int64 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

func (m *AppServerDeviceProfile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AppServerDeviceProfile) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type AddDeviceInM2MServerRequest struct {
	OrgId                int64                   `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	DevProfile           *AppServerDeviceProfile `protobuf:"bytes,2,opt,name=dev_profile,json=devProfile,proto3" json:"dev_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *AddDeviceInM2MServerRequest) Reset()         { *m = AddDeviceInM2MServerRequest{} }
func (m *AddDeviceInM2MServerRequest) String() string { return proto.CompactTextString(m) }
func (*AddDeviceInM2MServerRequest) ProtoMessage()    {}
func (*AddDeviceInM2MServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2566523af06a975e, []int{1}
}

func (m *AddDeviceInM2MServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddDeviceInM2MServerRequest.Unmarshal(m, b)
}
func (m *AddDeviceInM2MServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddDeviceInM2MServerRequest.Marshal(b, m, deterministic)
}
func (m *AddDeviceInM2MServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddDeviceInM2MServerRequest.Merge(m, src)
}
func (m *AddDeviceInM2MServerRequest) XXX_Size() int {
	return xxx_messageInfo_AddDeviceInM2MServerRequest.Size(m)
}
func (m *AddDeviceInM2MServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddDeviceInM2MServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddDeviceInM2MServerRequest proto.InternalMessageInfo

func (m *AddDeviceInM2MServerRequest) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *AddDeviceInM2MServerRequest) GetDevProfile() *AppServerDeviceProfile {
	if m != nil {
		return m.DevProfile
	}
	return nil
}

type AddDeviceInM2MServerResponse struct {
	DevId                int64    `protobuf:"varint,1,opt,name=dev_id,json=devId,proto3" json:"dev_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddDeviceInM2MServerResponse) Reset()         { *m = AddDeviceInM2MServerResponse{} }
func (m *AddDeviceInM2MServerResponse) String() string { return proto.CompactTextString(m) }
func (*AddDeviceInM2MServerResponse) ProtoMessage()    {}
func (*AddDeviceInM2MServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2566523af06a975e, []int{2}
}

func (m *AddDeviceInM2MServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddDeviceInM2MServerResponse.Unmarshal(m, b)
}
func (m *AddDeviceInM2MServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddDeviceInM2MServerResponse.Marshal(b, m, deterministic)
}
func (m *AddDeviceInM2MServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddDeviceInM2MServerResponse.Merge(m, src)
}
func (m *AddDeviceInM2MServerResponse) XXX_Size() int {
	return xxx_messageInfo_AddDeviceInM2MServerResponse.Size(m)
}
func (m *AddDeviceInM2MServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddDeviceInM2MServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddDeviceInM2MServerResponse proto.InternalMessageInfo

func (m *AddDeviceInM2MServerResponse) GetDevId() int64 {
	if m != nil {
		return m.DevId
	}
	return 0
}

type DeleteDeviceInM2MServerRequest struct {
	DevEui               string   `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDeviceInM2MServerRequest) Reset()         { *m = DeleteDeviceInM2MServerRequest{} }
func (m *DeleteDeviceInM2MServerRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteDeviceInM2MServerRequest) ProtoMessage()    {}
func (*DeleteDeviceInM2MServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2566523af06a975e, []int{3}
}

func (m *DeleteDeviceInM2MServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDeviceInM2MServerRequest.Unmarshal(m, b)
}
func (m *DeleteDeviceInM2MServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDeviceInM2MServerRequest.Marshal(b, m, deterministic)
}
func (m *DeleteDeviceInM2MServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDeviceInM2MServerRequest.Merge(m, src)
}
func (m *DeleteDeviceInM2MServerRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteDeviceInM2MServerRequest.Size(m)
}
func (m *DeleteDeviceInM2MServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDeviceInM2MServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDeviceInM2MServerRequest proto.InternalMessageInfo

func (m *DeleteDeviceInM2MServerRequest) GetDevEui() string {
	if m != nil {
		return m.DevEui
	}
	return ""
}

type DeleteDeviceInM2MServerResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDeviceInM2MServerResponse) Reset()         { *m = DeleteDeviceInM2MServerResponse{} }
func (m *DeleteDeviceInM2MServerResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteDeviceInM2MServerResponse) ProtoMessage()    {}
func (*DeleteDeviceInM2MServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2566523af06a975e, []int{4}
}

func (m *DeleteDeviceInM2MServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDeviceInM2MServerResponse.Unmarshal(m, b)
}
func (m *DeleteDeviceInM2MServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDeviceInM2MServerResponse.Marshal(b, m, deterministic)
}
func (m *DeleteDeviceInM2MServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDeviceInM2MServerResponse.Merge(m, src)
}
func (m *DeleteDeviceInM2MServerResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteDeviceInM2MServerResponse.Size(m)
}
func (m *DeleteDeviceInM2MServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDeviceInM2MServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDeviceInM2MServerResponse proto.InternalMessageInfo

func (m *DeleteDeviceInM2MServerResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type AppServerGatewayProfile struct {
	Mac                  string               `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	OrgId                int64                `protobuf:"varint,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Description          string               `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Name                 string               `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AppServerGatewayProfile) Reset()         { *m = AppServerGatewayProfile{} }
func (m *AppServerGatewayProfile) String() string { return proto.CompactTextString(m) }
func (*AppServerGatewayProfile) ProtoMessage()    {}
func (*AppServerGatewayProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_2566523af06a975e, []int{5}
}

func (m *AppServerGatewayProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppServerGatewayProfile.Unmarshal(m, b)
}
func (m *AppServerGatewayProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppServerGatewayProfile.Marshal(b, m, deterministic)
}
func (m *AppServerGatewayProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppServerGatewayProfile.Merge(m, src)
}
func (m *AppServerGatewayProfile) XXX_Size() int {
	return xxx_messageInfo_AppServerGatewayProfile.Size(m)
}
func (m *AppServerGatewayProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_AppServerGatewayProfile.DiscardUnknown(m)
}

var xxx_messageInfo_AppServerGatewayProfile proto.InternalMessageInfo

func (m *AppServerGatewayProfile) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *AppServerGatewayProfile) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *AppServerGatewayProfile) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AppServerGatewayProfile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AppServerGatewayProfile) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type AddGatewayInM2MServerRequest struct {
	OrgId                int64                    `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	GwProfile            *AppServerGatewayProfile `protobuf:"bytes,2,opt,name=gw_profile,json=gwProfile,proto3" json:"gw_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *AddGatewayInM2MServerRequest) Reset()         { *m = AddGatewayInM2MServerRequest{} }
func (m *AddGatewayInM2MServerRequest) String() string { return proto.CompactTextString(m) }
func (*AddGatewayInM2MServerRequest) ProtoMessage()    {}
func (*AddGatewayInM2MServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2566523af06a975e, []int{6}
}

func (m *AddGatewayInM2MServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddGatewayInM2MServerRequest.Unmarshal(m, b)
}
func (m *AddGatewayInM2MServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddGatewayInM2MServerRequest.Marshal(b, m, deterministic)
}
func (m *AddGatewayInM2MServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddGatewayInM2MServerRequest.Merge(m, src)
}
func (m *AddGatewayInM2MServerRequest) XXX_Size() int {
	return xxx_messageInfo_AddGatewayInM2MServerRequest.Size(m)
}
func (m *AddGatewayInM2MServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddGatewayInM2MServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddGatewayInM2MServerRequest proto.InternalMessageInfo

func (m *AddGatewayInM2MServerRequest) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *AddGatewayInM2MServerRequest) GetGwProfile() *AppServerGatewayProfile {
	if m != nil {
		return m.GwProfile
	}
	return nil
}

type AddGatewayInM2MServerResponse struct {
	GwId                 int64    `protobuf:"varint,1,opt,name=gw_id,json=gwId,proto3" json:"gw_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddGatewayInM2MServerResponse) Reset()         { *m = AddGatewayInM2MServerResponse{} }
func (m *AddGatewayInM2MServerResponse) String() string { return proto.CompactTextString(m) }
func (*AddGatewayInM2MServerResponse) ProtoMessage()    {}
func (*AddGatewayInM2MServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2566523af06a975e, []int{7}
}

func (m *AddGatewayInM2MServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddGatewayInM2MServerResponse.Unmarshal(m, b)
}
func (m *AddGatewayInM2MServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddGatewayInM2MServerResponse.Marshal(b, m, deterministic)
}
func (m *AddGatewayInM2MServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddGatewayInM2MServerResponse.Merge(m, src)
}
func (m *AddGatewayInM2MServerResponse) XXX_Size() int {
	return xxx_messageInfo_AddGatewayInM2MServerResponse.Size(m)
}
func (m *AddGatewayInM2MServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddGatewayInM2MServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddGatewayInM2MServerResponse proto.InternalMessageInfo

func (m *AddGatewayInM2MServerResponse) GetGwId() int64 {
	if m != nil {
		return m.GwId
	}
	return 0
}

type DeleteGatewayInM2MServerRequest struct {
	MacAddress           string   `protobuf:"bytes,2,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteGatewayInM2MServerRequest) Reset()         { *m = DeleteGatewayInM2MServerRequest{} }
func (m *DeleteGatewayInM2MServerRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteGatewayInM2MServerRequest) ProtoMessage()    {}
func (*DeleteGatewayInM2MServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2566523af06a975e, []int{8}
}

func (m *DeleteGatewayInM2MServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGatewayInM2MServerRequest.Unmarshal(m, b)
}
func (m *DeleteGatewayInM2MServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGatewayInM2MServerRequest.Marshal(b, m, deterministic)
}
func (m *DeleteGatewayInM2MServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGatewayInM2MServerRequest.Merge(m, src)
}
func (m *DeleteGatewayInM2MServerRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteGatewayInM2MServerRequest.Size(m)
}
func (m *DeleteGatewayInM2MServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGatewayInM2MServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGatewayInM2MServerRequest proto.InternalMessageInfo

func (m *DeleteGatewayInM2MServerRequest) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

type DeleteGatewayInM2MServerResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteGatewayInM2MServerResponse) Reset()         { *m = DeleteGatewayInM2MServerResponse{} }
func (m *DeleteGatewayInM2MServerResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteGatewayInM2MServerResponse) ProtoMessage()    {}
func (*DeleteGatewayInM2MServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2566523af06a975e, []int{9}
}

func (m *DeleteGatewayInM2MServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGatewayInM2MServerResponse.Unmarshal(m, b)
}
func (m *DeleteGatewayInM2MServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGatewayInM2MServerResponse.Marshal(b, m, deterministic)
}
func (m *DeleteGatewayInM2MServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGatewayInM2MServerResponse.Merge(m, src)
}
func (m *DeleteGatewayInM2MServerResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteGatewayInM2MServerResponse.Size(m)
}
func (m *DeleteGatewayInM2MServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGatewayInM2MServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGatewayInM2MServerResponse proto.InternalMessageInfo

func (m *DeleteGatewayInM2MServerResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type GetDeviceByDevEuiRequest struct {
	DevEui               string   `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeviceByDevEuiRequest) Reset()         { *m = GetDeviceByDevEuiRequest{} }
func (m *GetDeviceByDevEuiRequest) String() string { return proto.CompactTextString(m) }
func (*GetDeviceByDevEuiRequest) ProtoMessage()    {}
func (*GetDeviceByDevEuiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2566523af06a975e, []int{10}
}

func (m *GetDeviceByDevEuiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceByDevEuiRequest.Unmarshal(m, b)
}
func (m *GetDeviceByDevEuiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceByDevEuiRequest.Marshal(b, m, deterministic)
}
func (m *GetDeviceByDevEuiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceByDevEuiRequest.Merge(m, src)
}
func (m *GetDeviceByDevEuiRequest) XXX_Size() int {
	return xxx_messageInfo_GetDeviceByDevEuiRequest.Size(m)
}
func (m *GetDeviceByDevEuiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceByDevEuiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceByDevEuiRequest proto.InternalMessageInfo

func (m *GetDeviceByDevEuiRequest) GetDevEui() string {
	if m != nil {
		return m.DevEui
	}
	return ""
}

type GetDeviceByDevEuiResponse struct {
	OrgId                int64                   `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	DevProfile           *AppServerDeviceProfile `protobuf:"bytes,2,opt,name=dev_profile,json=devProfile,proto3" json:"dev_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetDeviceByDevEuiResponse) Reset()         { *m = GetDeviceByDevEuiResponse{} }
func (m *GetDeviceByDevEuiResponse) String() string { return proto.CompactTextString(m) }
func (*GetDeviceByDevEuiResponse) ProtoMessage()    {}
func (*GetDeviceByDevEuiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2566523af06a975e, []int{11}
}

func (m *GetDeviceByDevEuiResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceByDevEuiResponse.Unmarshal(m, b)
}
func (m *GetDeviceByDevEuiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceByDevEuiResponse.Marshal(b, m, deterministic)
}
func (m *GetDeviceByDevEuiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceByDevEuiResponse.Merge(m, src)
}
func (m *GetDeviceByDevEuiResponse) XXX_Size() int {
	return xxx_messageInfo_GetDeviceByDevEuiResponse.Size(m)
}
func (m *GetDeviceByDevEuiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceByDevEuiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceByDevEuiResponse proto.InternalMessageInfo

func (m *GetDeviceByDevEuiResponse) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *GetDeviceByDevEuiResponse) GetDevProfile() *AppServerDeviceProfile {
	if m != nil {
		return m.DevProfile
	}
	return nil
}

type GetGatewayByMacRequest struct {
	Mac                  string   `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGatewayByMacRequest) Reset()         { *m = GetGatewayByMacRequest{} }
func (m *GetGatewayByMacRequest) String() string { return proto.CompactTextString(m) }
func (*GetGatewayByMacRequest) ProtoMessage()    {}
func (*GetGatewayByMacRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2566523af06a975e, []int{12}
}

func (m *GetGatewayByMacRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGatewayByMacRequest.Unmarshal(m, b)
}
func (m *GetGatewayByMacRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGatewayByMacRequest.Marshal(b, m, deterministic)
}
func (m *GetGatewayByMacRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGatewayByMacRequest.Merge(m, src)
}
func (m *GetGatewayByMacRequest) XXX_Size() int {
	return xxx_messageInfo_GetGatewayByMacRequest.Size(m)
}
func (m *GetGatewayByMacRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGatewayByMacRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGatewayByMacRequest proto.InternalMessageInfo

func (m *GetGatewayByMacRequest) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

type GetGatewayByMacResponse struct {
	OrgId                int64                    `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	GwProfile            *AppServerGatewayProfile `protobuf:"bytes,2,opt,name=gw_profile,json=gwProfile,proto3" json:"gw_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GetGatewayByMacResponse) Reset()         { *m = GetGatewayByMacResponse{} }
func (m *GetGatewayByMacResponse) String() string { return proto.CompactTextString(m) }
func (*GetGatewayByMacResponse) ProtoMessage()    {}
func (*GetGatewayByMacResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2566523af06a975e, []int{13}
}

func (m *GetGatewayByMacResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGatewayByMacResponse.Unmarshal(m, b)
}
func (m *GetGatewayByMacResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGatewayByMacResponse.Marshal(b, m, deterministic)
}
func (m *GetGatewayByMacResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGatewayByMacResponse.Merge(m, src)
}
func (m *GetGatewayByMacResponse) XXX_Size() int {
	return xxx_messageInfo_GetGatewayByMacResponse.Size(m)
}
func (m *GetGatewayByMacResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGatewayByMacResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetGatewayByMacResponse proto.InternalMessageInfo

func (m *GetGatewayByMacResponse) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *GetGatewayByMacResponse) GetGwProfile() *AppServerGatewayProfile {
	if m != nil {
		return m.GwProfile
	}
	return nil
}

type GetDeviceDevEuiListResponse struct {
	DevEui               []string `protobuf:"bytes,1,rep,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeviceDevEuiListResponse) Reset()         { *m = GetDeviceDevEuiListResponse{} }
func (m *GetDeviceDevEuiListResponse) String() string { return proto.CompactTextString(m) }
func (*GetDeviceDevEuiListResponse) ProtoMessage()    {}
func (*GetDeviceDevEuiListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2566523af06a975e, []int{14}
}

func (m *GetDeviceDevEuiListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceDevEuiListResponse.Unmarshal(m, b)
}
func (m *GetDeviceDevEuiListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceDevEuiListResponse.Marshal(b, m, deterministic)
}
func (m *GetDeviceDevEuiListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceDevEuiListResponse.Merge(m, src)
}
func (m *GetDeviceDevEuiListResponse) XXX_Size() int {
	return xxx_messageInfo_GetDeviceDevEuiListResponse.Size(m)
}
func (m *GetDeviceDevEuiListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceDevEuiListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceDevEuiListResponse proto.InternalMessageInfo

func (m *GetDeviceDevEuiListResponse) GetDevEui() []string {
	if m != nil {
		return m.DevEui
	}
	return nil
}

type GetGatewayMacListResponse struct {
	GatewayMac           []string `protobuf:"bytes,1,rep,name=gateway_mac,json=gatewayMac,proto3" json:"gateway_mac,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGatewayMacListResponse) Reset()         { *m = GetGatewayMacListResponse{} }
func (m *GetGatewayMacListResponse) String() string { return proto.CompactTextString(m) }
func (*GetGatewayMacListResponse) ProtoMessage()    {}
func (*GetGatewayMacListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2566523af06a975e, []int{15}
}

func (m *GetGatewayMacListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGatewayMacListResponse.Unmarshal(m, b)
}
func (m *GetGatewayMacListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGatewayMacListResponse.Marshal(b, m, deterministic)
}
func (m *GetGatewayMacListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGatewayMacListResponse.Merge(m, src)
}
func (m *GetGatewayMacListResponse) XXX_Size() int {
	return xxx_messageInfo_GetGatewayMacListResponse.Size(m)
}
func (m *GetGatewayMacListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGatewayMacListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetGatewayMacListResponse proto.InternalMessageInfo

func (m *GetGatewayMacListResponse) GetGatewayMac() []string {
	if m != nil {
		return m.GatewayMac
	}
	return nil
}

func init() {
	proto.RegisterType((*AppServerDeviceProfile)(nil), "api.AppServerDeviceProfile")
	proto.RegisterType((*AddDeviceInM2MServerRequest)(nil), "api.AddDeviceInM2MServerRequest")
	proto.RegisterType((*AddDeviceInM2MServerResponse)(nil), "api.AddDeviceInM2MServerResponse")
	proto.RegisterType((*DeleteDeviceInM2MServerRequest)(nil), "api.DeleteDeviceInM2MServerRequest")
	proto.RegisterType((*DeleteDeviceInM2MServerResponse)(nil), "api.DeleteDeviceInM2MServerResponse")
	proto.RegisterType((*AppServerGatewayProfile)(nil), "api.AppServerGatewayProfile")
	proto.RegisterType((*AddGatewayInM2MServerRequest)(nil), "api.AddGatewayInM2MServerRequest")
	proto.RegisterType((*AddGatewayInM2MServerResponse)(nil), "api.AddGatewayInM2MServerResponse")
	proto.RegisterType((*DeleteGatewayInM2MServerRequest)(nil), "api.DeleteGatewayInM2MServerRequest")
	proto.RegisterType((*DeleteGatewayInM2MServerResponse)(nil), "api.DeleteGatewayInM2MServerResponse")
	proto.RegisterType((*GetDeviceByDevEuiRequest)(nil), "api.GetDeviceByDevEuiRequest")
	proto.RegisterType((*GetDeviceByDevEuiResponse)(nil), "api.GetDeviceByDevEuiResponse")
	proto.RegisterType((*GetGatewayByMacRequest)(nil), "api.GetGatewayByMacRequest")
	proto.RegisterType((*GetGatewayByMacResponse)(nil), "api.GetGatewayByMacResponse")
	proto.RegisterType((*GetDeviceDevEuiListResponse)(nil), "api.GetDeviceDevEuiListResponse")
	proto.RegisterType((*GetGatewayMacListResponse)(nil), "api.GetGatewayMacListResponse")
}

func init() { proto.RegisterFile("appserver.proto", fileDescriptor_2566523af06a975e) }

var fileDescriptor_2566523af06a975e = []byte{
	// 711 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0x55, 0x9a, 0x34, 0xdf, 0x97, 0x89, 0xa0, 0x65, 0x4b, 0x93, 0xe0, 0xb4, 0x8d, 0x31, 0x54,
	0xaa, 0xb8, 0x48, 0xa5, 0x14, 0x90, 0x0a, 0xbd, 0x49, 0xd5, 0xaa, 0x8a, 0x68, 0x04, 0x32, 0xdc,
	0x21, 0x11, 0x6d, 0xbd, 0x53, 0xcb, 0x52, 0x1c, 0x2f, 0xf6, 0x26, 0x51, 0x5e, 0x86, 0x5b, 0x1e,
	0x80, 0x37, 0xe1, 0x89, 0x90, 0xd7, 0x6b, 0x37, 0x3f, 0xde, 0x14, 0x04, 0x37, 0x95, 0xbb, 0x3b,
	0x33, 0xe7, 0xcc, 0x39, 0x33, 0x1b, 0xd8, 0xa2, 0x9c, 0x47, 0x18, 0x4e, 0x30, 0x6c, 0xf3, 0x30,
	0x10, 0x01, 0x29, 0x52, 0xee, 0x19, 0x2d, 0x37, 0x08, 0xdc, 0x21, 0x1e, 0xcb, 0xa3, 0x9b, 0xf1,
	0xed, 0xb1, 0xf0, 0x7c, 0x8c, 0x04, 0xf5, 0x79, 0x12, 0x65, 0x34, 0x97, 0x03, 0xd0, 0xe7, 0x62,
	0x96, 0x5c, 0x5a, 0xdf, 0x0b, 0x50, 0xeb, 0x72, 0xfe, 0x51, 0x96, 0xbd, 0xc0, 0x89, 0xe7, 0xe0,
	0x87, 0x30, 0xb8, 0xf5, 0x86, 0x48, 0xea, 0xf0, 0x1f, 0xc3, 0xc9, 0x00, 0xc7, 0x5e, 0xa3, 0x60,
	0x16, 0x8e, 0x2a, 0x76, 0x99, 0xe1, 0xe4, 0x72, 0xec, 0x91, 0x43, 0x78, 0x48, 0x39, 0x1f, 0x7a,
	0x0e, 0x15, 0x5e, 0x30, 0x1a, 0x78, 0xac, 0xb1, 0x61, 0x16, 0x8e, 0x8a, 0xf6, 0x83, 0xb9, 0xd3,
	0x1e, 0x23, 0x04, 0x4a, 0x23, 0xea, 0x63, 0xa3, 0x28, 0x93, 0xe5, 0x37, 0x39, 0x05, 0x70, 0x42,
	0xa4, 0x02, 0xd9, 0x80, 0x8a, 0x46, 0xc9, 0x2c, 0x1c, 0x55, 0x3b, 0x46, 0x3b, 0x21, 0xd8, 0x4e,
	0x09, 0xb6, 0x3f, 0xa5, 0x1d, 0xd8, 0x15, 0x15, 0xdd, 0x15, 0x56, 0x08, 0xcd, 0x2e, 0x63, 0x09,
	0xc5, 0xde, 0xa8, 0xdf, 0xe9, 0x27, 0x9c, 0x6d, 0xfc, 0x3a, 0xc6, 0x48, 0x90, 0x5d, 0x28, 0x07,
	0xa1, 0x1b, 0x93, 0x29, 0x48, 0x32, 0x9b, 0x41, 0xe8, 0xf6, 0x18, 0x39, 0x83, 0x6a, 0xdc, 0x04,
	0x4f, 0x7a, 0x92, 0x44, 0xab, 0x9d, 0x66, 0x9b, 0x72, 0xaf, 0x9d, 0xdf, 0xb6, 0x0d, 0x0c, 0x27,
	0xea, 0xdb, 0x7a, 0x05, 0x7b, 0xf9, 0x98, 0x11, 0x0f, 0x46, 0x11, 0xc6, 0xa0, 0x71, 0xf5, 0x3b,
	0x50, 0x86, 0x93, 0x1e, 0xb3, 0x4e, 0xe1, 0xe0, 0x02, 0x87, 0x28, 0x50, 0xcb, 0x56, 0xa7, 0xad,
	0x75, 0x0a, 0x2d, 0x6d, 0xaa, 0x02, 0xad, 0x41, 0x39, 0x12, 0x54, 0x8c, 0x23, 0x99, 0xfa, 0xbf,
	0xad, 0xfe, 0xb3, 0x7e, 0x14, 0xa0, 0x9e, 0xf5, 0x74, 0x45, 0x05, 0x4e, 0xe9, 0x2c, 0xf5, 0x72,
	0x1b, 0x8a, 0x3e, 0x75, 0x14, 0x56, 0xfc, 0x39, 0xa7, 0xd7, 0xc6, 0xbc, 0x5e, 0x66, 0xac, 0x57,
	0xe4, 0x84, 0x1e, 0x8f, 0x5d, 0x54, 0xde, 0xcd, 0x1f, 0x65, 0xb6, 0x96, 0xb4, 0xb6, 0x6e, 0xfe,
	0x99, 0xad, 0xb1, 0xc4, 0x8a, 0xee, 0xef, 0xfb, 0xfa, 0x16, 0xc0, 0x9d, 0x2e, 0xd9, 0xba, 0xb7,
	0x68, 0xeb, 0xa2, 0x04, 0x76, 0xc5, 0x9d, 0xa6, 0xb6, 0xbe, 0x84, 0x7d, 0x0d, 0xa6, 0x92, 0x78,
	0x07, 0x36, 0xdd, 0xe9, 0x1d, 0x66, 0xc9, 0x9d, 0xf6, 0x98, 0x75, 0x9e, 0x5a, 0xa3, 0x27, 0xdb,
	0x82, 0xaa, 0x4f, 0x9d, 0x01, 0x65, 0x2c, 0xc4, 0x28, 0x92, 0xb4, 0x2a, 0x36, 0xf8, 0xd4, 0xe9,
	0x26, 0x27, 0xd6, 0x1b, 0x30, 0xf5, 0x35, 0xee, 0xf1, 0xf7, 0x04, 0x1a, 0x57, 0x28, 0x92, 0xb9,
	0x38, 0x9f, 0x5d, 0xc8, 0x79, 0xb9, 0x77, 0x9e, 0x38, 0x3c, 0xc9, 0x49, 0xba, 0x1b, 0xdf, 0x7f,
	0xbf, 0x33, 0x2f, 0xa0, 0x76, 0x85, 0x42, 0xf5, 0x77, 0x3e, 0xeb, 0x53, 0x27, 0x25, 0xb9, 0x32,
	0x84, 0x96, 0x0f, 0xf5, 0x95, 0xd8, 0xf5, 0xdc, 0xfe, 0xca, 0xf7, 0xd7, 0xd0, 0xcc, 0xc4, 0x48,
	0xa4, 0xb8, 0xf6, 0x22, 0x91, 0x41, 0x2e, 0x88, 0x58, 0x9c, 0x13, 0xf1, 0x4c, 0x8a, 0xa8, 0xea,
	0xf6, 0xa9, 0xb3, 0x90, 0xd5, 0x82, 0xaa, 0x9b, 0xdc, 0x0c, 0x92, 0xee, 0xe2, 0x4c, 0x70, 0xb3,
	0xe0, 0xce, 0xb7, 0x22, 0x6c, 0x67, 0x2e, 0xc7, 0x7f, 0x3d, 0x07, 0xc9, 0x67, 0x78, 0x9c, 0xf7,
	0xb2, 0x10, 0x33, 0xe9, 0x45, 0xff, 0xd0, 0x19, 0x4f, 0xd7, 0x44, 0x28, 0x4a, 0x0c, 0xea, 0x9a,
	0x47, 0x84, 0x3c, 0x93, 0xd9, 0xeb, 0x5f, 0x27, 0xe3, 0xf9, 0xfa, 0x20, 0x85, 0xf2, 0x05, 0x76,
	0x73, 0xb7, 0x88, 0x64, 0x0c, 0xb5, 0x8b, 0x62, 0x58, 0xeb, 0x42, 0x54, 0x7d, 0x17, 0x1a, 0xba,
	0x5d, 0x21, 0xf3, 0x0c, 0xf5, 0x28, 0x87, 0xf7, 0x44, 0x25, 0x40, 0x9d, 0x9f, 0x1b, 0xb0, 0x9d,
	0x4d, 0x4f, 0x6a, 0x90, 0x0d, 0x8f, 0x56, 0x16, 0x87, 0xec, 0xcb, 0x82, 0xba, 0x2d, 0x34, 0x0e,
	0x74, 0xd7, 0xaa, 0xa3, 0x6b, 0xd8, 0x5a, 0x1a, 0x77, 0xd2, 0x4c, 0x53, 0x72, 0x16, 0xc6, 0xd8,
	0xcb, 0xbf, 0x54, 0xd5, 0xde, 0xc3, 0x4e, 0xce, 0x34, 0x93, 0xda, 0xca, 0xbb, 0x7b, 0x19, 0xff,
	0xde, 0x1b, 0xe6, 0x22, 0xb9, 0x9c, 0xf9, 0x7f, 0x27, 0x5b, 0x5e, 0x1c, 0x73, 0x6d, 0xb9, 0x83,
	0x25, 0x6e, 0x4b, 0x6b, 0x71, 0x53, 0x96, 0xf1, 0x27, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x0b,
	0x14, 0x11, 0xe0, 0xb5, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// M2MServerServiceClient is the client API for M2MServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type M2MServerServiceClient interface {
	AddDeviceInM2MServer(ctx context.Context, in *AddDeviceInM2MServerRequest, opts ...grpc.CallOption) (*AddDeviceInM2MServerResponse, error)
	DeleteDeviceInM2MServer(ctx context.Context, in *DeleteDeviceInM2MServerRequest, opts ...grpc.CallOption) (*DeleteDeviceInM2MServerResponse, error)
	AddGatewayInM2MServer(ctx context.Context, in *AddGatewayInM2MServerRequest, opts ...grpc.CallOption) (*AddGatewayInM2MServerResponse, error)
	DeleteGatewayInM2MServer(ctx context.Context, in *DeleteGatewayInM2MServerRequest, opts ...grpc.CallOption) (*DeleteGatewayInM2MServerResponse, error)
}

type m2MServerServiceClient struct {
	cc *grpc.ClientConn
}

func NewM2MServerServiceClient(cc *grpc.ClientConn) M2MServerServiceClient {
	return &m2MServerServiceClient{cc}
}

func (c *m2MServerServiceClient) AddDeviceInM2MServer(ctx context.Context, in *AddDeviceInM2MServerRequest, opts ...grpc.CallOption) (*AddDeviceInM2MServerResponse, error) {
	out := new(AddDeviceInM2MServerResponse)
	err := c.cc.Invoke(ctx, "/api.M2MServerService/AddDeviceInM2MServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *m2MServerServiceClient) DeleteDeviceInM2MServer(ctx context.Context, in *DeleteDeviceInM2MServerRequest, opts ...grpc.CallOption) (*DeleteDeviceInM2MServerResponse, error) {
	out := new(DeleteDeviceInM2MServerResponse)
	err := c.cc.Invoke(ctx, "/api.M2MServerService/DeleteDeviceInM2MServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *m2MServerServiceClient) AddGatewayInM2MServer(ctx context.Context, in *AddGatewayInM2MServerRequest, opts ...grpc.CallOption) (*AddGatewayInM2MServerResponse, error) {
	out := new(AddGatewayInM2MServerResponse)
	err := c.cc.Invoke(ctx, "/api.M2MServerService/AddGatewayInM2MServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *m2MServerServiceClient) DeleteGatewayInM2MServer(ctx context.Context, in *DeleteGatewayInM2MServerRequest, opts ...grpc.CallOption) (*DeleteGatewayInM2MServerResponse, error) {
	out := new(DeleteGatewayInM2MServerResponse)
	err := c.cc.Invoke(ctx, "/api.M2MServerService/DeleteGatewayInM2MServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// M2MServerServiceServer is the server API for M2MServerService service.
type M2MServerServiceServer interface {
	AddDeviceInM2MServer(context.Context, *AddDeviceInM2MServerRequest) (*AddDeviceInM2MServerResponse, error)
	DeleteDeviceInM2MServer(context.Context, *DeleteDeviceInM2MServerRequest) (*DeleteDeviceInM2MServerResponse, error)
	AddGatewayInM2MServer(context.Context, *AddGatewayInM2MServerRequest) (*AddGatewayInM2MServerResponse, error)
	DeleteGatewayInM2MServer(context.Context, *DeleteGatewayInM2MServerRequest) (*DeleteGatewayInM2MServerResponse, error)
}

// UnimplementedM2MServerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedM2MServerServiceServer struct {
}

func (*UnimplementedM2MServerServiceServer) AddDeviceInM2MServer(ctx context.Context, req *AddDeviceInM2MServerRequest) (*AddDeviceInM2MServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDeviceInM2MServer not implemented")
}
func (*UnimplementedM2MServerServiceServer) DeleteDeviceInM2MServer(ctx context.Context, req *DeleteDeviceInM2MServerRequest) (*DeleteDeviceInM2MServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDeviceInM2MServer not implemented")
}
func (*UnimplementedM2MServerServiceServer) AddGatewayInM2MServer(ctx context.Context, req *AddGatewayInM2MServerRequest) (*AddGatewayInM2MServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddGatewayInM2MServer not implemented")
}
func (*UnimplementedM2MServerServiceServer) DeleteGatewayInM2MServer(ctx context.Context, req *DeleteGatewayInM2MServerRequest) (*DeleteGatewayInM2MServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGatewayInM2MServer not implemented")
}

func RegisterM2MServerServiceServer(s *grpc.Server, srv M2MServerServiceServer) {
	s.RegisterService(&_M2MServerService_serviceDesc, srv)
}

func _M2MServerService_AddDeviceInM2MServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDeviceInM2MServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(M2MServerServiceServer).AddDeviceInM2MServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.M2MServerService/AddDeviceInM2MServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(M2MServerServiceServer).AddDeviceInM2MServer(ctx, req.(*AddDeviceInM2MServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _M2MServerService_DeleteDeviceInM2MServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeviceInM2MServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(M2MServerServiceServer).DeleteDeviceInM2MServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.M2MServerService/DeleteDeviceInM2MServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(M2MServerServiceServer).DeleteDeviceInM2MServer(ctx, req.(*DeleteDeviceInM2MServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _M2MServerService_AddGatewayInM2MServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGatewayInM2MServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(M2MServerServiceServer).AddGatewayInM2MServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.M2MServerService/AddGatewayInM2MServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(M2MServerServiceServer).AddGatewayInM2MServer(ctx, req.(*AddGatewayInM2MServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _M2MServerService_DeleteGatewayInM2MServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGatewayInM2MServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(M2MServerServiceServer).DeleteGatewayInM2MServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.M2MServerService/DeleteGatewayInM2MServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(M2MServerServiceServer).DeleteGatewayInM2MServer(ctx, req.(*DeleteGatewayInM2MServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _M2MServerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.M2MServerService",
	HandlerType: (*M2MServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddDeviceInM2MServer",
			Handler:    _M2MServerService_AddDeviceInM2MServer_Handler,
		},
		{
			MethodName: "DeleteDeviceInM2MServer",
			Handler:    _M2MServerService_DeleteDeviceInM2MServer_Handler,
		},
		{
			MethodName: "AddGatewayInM2MServer",
			Handler:    _M2MServerService_AddGatewayInM2MServer_Handler,
		},
		{
			MethodName: "DeleteGatewayInM2MServer",
			Handler:    _M2MServerService_DeleteGatewayInM2MServer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "appserver.proto",
}

// AppServerServiceClient is the client API for AppServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AppServerServiceClient interface {
	GetDeviceByDevEui(ctx context.Context, in *GetDeviceByDevEuiRequest, opts ...grpc.CallOption) (*GetDeviceByDevEuiResponse, error)
	GetGatewayByMac(ctx context.Context, in *GetGatewayByMacRequest, opts ...grpc.CallOption) (*GetGatewayByMacResponse, error)
	GetDeviceDevEuiList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetDeviceDevEuiListResponse, error)
	GetGatewayMacList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetGatewayMacListResponse, error)
}

type appServerServiceClient struct {
	cc *grpc.ClientConn
}

func NewAppServerServiceClient(cc *grpc.ClientConn) AppServerServiceClient {
	return &appServerServiceClient{cc}
}

func (c *appServerServiceClient) GetDeviceByDevEui(ctx context.Context, in *GetDeviceByDevEuiRequest, opts ...grpc.CallOption) (*GetDeviceByDevEuiResponse, error) {
	out := new(GetDeviceByDevEuiResponse)
	err := c.cc.Invoke(ctx, "/api.AppServerService/GetDeviceByDevEui", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServerServiceClient) GetGatewayByMac(ctx context.Context, in *GetGatewayByMacRequest, opts ...grpc.CallOption) (*GetGatewayByMacResponse, error) {
	out := new(GetGatewayByMacResponse)
	err := c.cc.Invoke(ctx, "/api.AppServerService/GetGatewayByMac", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServerServiceClient) GetDeviceDevEuiList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetDeviceDevEuiListResponse, error) {
	out := new(GetDeviceDevEuiListResponse)
	err := c.cc.Invoke(ctx, "/api.AppServerService/GetDeviceDevEuiList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServerServiceClient) GetGatewayMacList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetGatewayMacListResponse, error) {
	out := new(GetGatewayMacListResponse)
	err := c.cc.Invoke(ctx, "/api.AppServerService/GetGatewayMacList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppServerServiceServer is the server API for AppServerService service.
type AppServerServiceServer interface {
	GetDeviceByDevEui(context.Context, *GetDeviceByDevEuiRequest) (*GetDeviceByDevEuiResponse, error)
	GetGatewayByMac(context.Context, *GetGatewayByMacRequest) (*GetGatewayByMacResponse, error)
	GetDeviceDevEuiList(context.Context, *empty.Empty) (*GetDeviceDevEuiListResponse, error)
	GetGatewayMacList(context.Context, *empty.Empty) (*GetGatewayMacListResponse, error)
}

// UnimplementedAppServerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAppServerServiceServer struct {
}

func (*UnimplementedAppServerServiceServer) GetDeviceByDevEui(ctx context.Context, req *GetDeviceByDevEuiRequest) (*GetDeviceByDevEuiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceByDevEui not implemented")
}
func (*UnimplementedAppServerServiceServer) GetGatewayByMac(ctx context.Context, req *GetGatewayByMacRequest) (*GetGatewayByMacResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGatewayByMac not implemented")
}
func (*UnimplementedAppServerServiceServer) GetDeviceDevEuiList(ctx context.Context, req *empty.Empty) (*GetDeviceDevEuiListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceDevEuiList not implemented")
}
func (*UnimplementedAppServerServiceServer) GetGatewayMacList(ctx context.Context, req *empty.Empty) (*GetGatewayMacListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGatewayMacList not implemented")
}

func RegisterAppServerServiceServer(s *grpc.Server, srv AppServerServiceServer) {
	s.RegisterService(&_AppServerService_serviceDesc, srv)
}

func _AppServerService_GetDeviceByDevEui_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceByDevEuiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServerServiceServer).GetDeviceByDevEui(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AppServerService/GetDeviceByDevEui",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServerServiceServer).GetDeviceByDevEui(ctx, req.(*GetDeviceByDevEuiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppServerService_GetGatewayByMac_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGatewayByMacRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServerServiceServer).GetGatewayByMac(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AppServerService/GetGatewayByMac",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServerServiceServer).GetGatewayByMac(ctx, req.(*GetGatewayByMacRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppServerService_GetDeviceDevEuiList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServerServiceServer).GetDeviceDevEuiList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AppServerService/GetDeviceDevEuiList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServerServiceServer).GetDeviceDevEuiList(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppServerService_GetGatewayMacList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServerServiceServer).GetGatewayMacList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AppServerService/GetGatewayMacList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServerServiceServer).GetGatewayMacList(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _AppServerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.AppServerService",
	HandlerType: (*AppServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDeviceByDevEui",
			Handler:    _AppServerService_GetDeviceByDevEui_Handler,
		},
		{
			MethodName: "GetGatewayByMac",
			Handler:    _AppServerService_GetGatewayByMac_Handler,
		},
		{
			MethodName: "GetDeviceDevEuiList",
			Handler:    _AppServerService_GetDeviceDevEuiList_Handler,
		},
		{
			MethodName: "GetGatewayMacList",
			Handler:    _AppServerService_GetGatewayMacList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "appserver.proto",
}
