// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mxprotocol-server/lpwan-app-server/device_item.proto

package m2m

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeviceMode int32

const (
	DeviceMode_DV_INACTIVE              DeviceMode = 0
	DeviceMode_DV_FREE_GATEWAYS_LIMITED DeviceMode = 1
	DeviceMode_DV_WHOLE_NETWORK         DeviceMode = 2
	DeviceMode_DV_DELETED               DeviceMode = 3
)

var DeviceMode_name = map[int32]string{
	0: "DV_INACTIVE",
	1: "DV_FREE_GATEWAYS_LIMITED",
	2: "DV_WHOLE_NETWORK",
	3: "DV_DELETED",
}

var DeviceMode_value = map[string]int32{
	"DV_INACTIVE":              0,
	"DV_FREE_GATEWAYS_LIMITED": 1,
	"DV_WHOLE_NETWORK":         2,
	"DV_DELETED":               3,
}

func (x DeviceMode) String() string {
	return proto.EnumName(DeviceMode_name, int32(x))
}

func (DeviceMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b28b7c3f2b1e3cd0, []int{0}
}

type GetDeviceListRequest struct {
	OrgId                int64    `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Offset               int64    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int64    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeviceListRequest) Reset()         { *m = GetDeviceListRequest{} }
func (m *GetDeviceListRequest) String() string { return proto.CompactTextString(m) }
func (*GetDeviceListRequest) ProtoMessage()    {}
func (*GetDeviceListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b28b7c3f2b1e3cd0, []int{0}
}

func (m *GetDeviceListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceListRequest.Unmarshal(m, b)
}
func (m *GetDeviceListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceListRequest.Marshal(b, m, deterministic)
}
func (m *GetDeviceListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceListRequest.Merge(m, src)
}
func (m *GetDeviceListRequest) XXX_Size() int {
	return xxx_messageInfo_GetDeviceListRequest.Size(m)
}
func (m *GetDeviceListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceListRequest proto.InternalMessageInfo

func (m *GetDeviceListRequest) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *GetDeviceListRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetDeviceListRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetDeviceListResponse struct {
	DevProfile           []*DSDeviceProfile `protobuf:"bytes,1,rep,name=dev_profile,json=devProfile,proto3" json:"dev_profile,omitempty"`
	Count                int64              `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetDeviceListResponse) Reset()         { *m = GetDeviceListResponse{} }
func (m *GetDeviceListResponse) String() string { return proto.CompactTextString(m) }
func (*GetDeviceListResponse) ProtoMessage()    {}
func (*GetDeviceListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b28b7c3f2b1e3cd0, []int{1}
}

func (m *GetDeviceListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceListResponse.Unmarshal(m, b)
}
func (m *GetDeviceListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceListResponse.Marshal(b, m, deterministic)
}
func (m *GetDeviceListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceListResponse.Merge(m, src)
}
func (m *GetDeviceListResponse) XXX_Size() int {
	return xxx_messageInfo_GetDeviceListResponse.Size(m)
}
func (m *GetDeviceListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceListResponse proto.InternalMessageInfo

func (m *GetDeviceListResponse) GetDevProfile() []*DSDeviceProfile {
	if m != nil {
		return m.DevProfile
	}
	return nil
}

func (m *GetDeviceListResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetDSDeviceProfileRequest struct {
	OrgId                int64    `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	DevId                int64    `protobuf:"varint,2,opt,name=dev_id,json=devId,proto3" json:"dev_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDSDeviceProfileRequest) Reset()         { *m = GetDSDeviceProfileRequest{} }
func (m *GetDSDeviceProfileRequest) String() string { return proto.CompactTextString(m) }
func (*GetDSDeviceProfileRequest) ProtoMessage()    {}
func (*GetDSDeviceProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b28b7c3f2b1e3cd0, []int{2}
}

func (m *GetDSDeviceProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDSDeviceProfileRequest.Unmarshal(m, b)
}
func (m *GetDSDeviceProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDSDeviceProfileRequest.Marshal(b, m, deterministic)
}
func (m *GetDSDeviceProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDSDeviceProfileRequest.Merge(m, src)
}
func (m *GetDSDeviceProfileRequest) XXX_Size() int {
	return xxx_messageInfo_GetDSDeviceProfileRequest.Size(m)
}
func (m *GetDSDeviceProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDSDeviceProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDSDeviceProfileRequest proto.InternalMessageInfo

func (m *GetDSDeviceProfileRequest) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *GetDSDeviceProfileRequest) GetDevId() int64 {
	if m != nil {
		return m.DevId
	}
	return 0
}

type DSDeviceProfile struct {
	Id                   int64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DevEui               string     `protobuf:"bytes,2,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	FkWallet             int64      `protobuf:"varint,3,opt,name=fk_wallet,json=fkWallet,proto3" json:"fk_wallet,omitempty"`
	Mode                 DeviceMode `protobuf:"varint,4,opt,name=mode,proto3,enum=m2m.DeviceMode" json:"mode,omitempty"`
	CreatedAt            string     `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastSeenAt           string     `protobuf:"bytes,6,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	ApplicationId        int64      `protobuf:"varint,7,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Name                 string     `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DSDeviceProfile) Reset()         { *m = DSDeviceProfile{} }
func (m *DSDeviceProfile) String() string { return proto.CompactTextString(m) }
func (*DSDeviceProfile) ProtoMessage()    {}
func (*DSDeviceProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_b28b7c3f2b1e3cd0, []int{3}
}

func (m *DSDeviceProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DSDeviceProfile.Unmarshal(m, b)
}
func (m *DSDeviceProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DSDeviceProfile.Marshal(b, m, deterministic)
}
func (m *DSDeviceProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DSDeviceProfile.Merge(m, src)
}
func (m *DSDeviceProfile) XXX_Size() int {
	return xxx_messageInfo_DSDeviceProfile.Size(m)
}
func (m *DSDeviceProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_DSDeviceProfile.DiscardUnknown(m)
}

var xxx_messageInfo_DSDeviceProfile proto.InternalMessageInfo

func (m *DSDeviceProfile) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DSDeviceProfile) GetDevEui() string {
	if m != nil {
		return m.DevEui
	}
	return ""
}

func (m *DSDeviceProfile) GetFkWallet() int64 {
	if m != nil {
		return m.FkWallet
	}
	return 0
}

func (m *DSDeviceProfile) GetMode() DeviceMode {
	if m != nil {
		return m.Mode
	}
	return DeviceMode_DV_INACTIVE
}

func (m *DSDeviceProfile) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *DSDeviceProfile) GetLastSeenAt() string {
	if m != nil {
		return m.LastSeenAt
	}
	return ""
}

func (m *DSDeviceProfile) GetApplicationId() int64 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

func (m *DSDeviceProfile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetDSDeviceProfileResponse struct {
	DevProfile           *DSDeviceProfile `protobuf:"bytes,1,opt,name=dev_profile,json=devProfile,proto3" json:"dev_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetDSDeviceProfileResponse) Reset()         { *m = GetDSDeviceProfileResponse{} }
func (m *GetDSDeviceProfileResponse) String() string { return proto.CompactTextString(m) }
func (*GetDSDeviceProfileResponse) ProtoMessage()    {}
func (*GetDSDeviceProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b28b7c3f2b1e3cd0, []int{4}
}

func (m *GetDSDeviceProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDSDeviceProfileResponse.Unmarshal(m, b)
}
func (m *GetDSDeviceProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDSDeviceProfileResponse.Marshal(b, m, deterministic)
}
func (m *GetDSDeviceProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDSDeviceProfileResponse.Merge(m, src)
}
func (m *GetDSDeviceProfileResponse) XXX_Size() int {
	return xxx_messageInfo_GetDSDeviceProfileResponse.Size(m)
}
func (m *GetDSDeviceProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDSDeviceProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDSDeviceProfileResponse proto.InternalMessageInfo

func (m *GetDSDeviceProfileResponse) GetDevProfile() *DSDeviceProfile {
	if m != nil {
		return m.DevProfile
	}
	return nil
}

type GetDeviceHistoryRequest struct {
	OrgId                int64    `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	DevId                int64    `protobuf:"varint,2,opt,name=dev_id,json=devId,proto3" json:"dev_id,omitempty"`
	Offset               int64    `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int64    `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeviceHistoryRequest) Reset()         { *m = GetDeviceHistoryRequest{} }
func (m *GetDeviceHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetDeviceHistoryRequest) ProtoMessage()    {}
func (*GetDeviceHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b28b7c3f2b1e3cd0, []int{5}
}

func (m *GetDeviceHistoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceHistoryRequest.Unmarshal(m, b)
}
func (m *GetDeviceHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceHistoryRequest.Marshal(b, m, deterministic)
}
func (m *GetDeviceHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceHistoryRequest.Merge(m, src)
}
func (m *GetDeviceHistoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetDeviceHistoryRequest.Size(m)
}
func (m *GetDeviceHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceHistoryRequest proto.InternalMessageInfo

func (m *GetDeviceHistoryRequest) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *GetDeviceHistoryRequest) GetDevId() int64 {
	if m != nil {
		return m.DevId
	}
	return 0
}

func (m *GetDeviceHistoryRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetDeviceHistoryRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetDeviceHistoryResponse struct {
	DevHistory           string   `protobuf:"bytes,1,opt,name=dev_history,json=devHistory,proto3" json:"dev_history,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeviceHistoryResponse) Reset()         { *m = GetDeviceHistoryResponse{} }
func (m *GetDeviceHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*GetDeviceHistoryResponse) ProtoMessage()    {}
func (*GetDeviceHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b28b7c3f2b1e3cd0, []int{6}
}

func (m *GetDeviceHistoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceHistoryResponse.Unmarshal(m, b)
}
func (m *GetDeviceHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceHistoryResponse.Marshal(b, m, deterministic)
}
func (m *GetDeviceHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceHistoryResponse.Merge(m, src)
}
func (m *GetDeviceHistoryResponse) XXX_Size() int {
	return xxx_messageInfo_GetDeviceHistoryResponse.Size(m)
}
func (m *GetDeviceHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceHistoryResponse proto.InternalMessageInfo

func (m *GetDeviceHistoryResponse) GetDevHistory() string {
	if m != nil {
		return m.DevHistory
	}
	return ""
}

type SetDeviceModeRequest struct {
	OrgId                int64      `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	DevId                int64      `protobuf:"varint,2,opt,name=dev_id,json=devId,proto3" json:"dev_id,omitempty"`
	DevMode              DeviceMode `protobuf:"varint,3,opt,name=dev_mode,json=devMode,proto3,enum=m2m.DeviceMode" json:"dev_mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SetDeviceModeRequest) Reset()         { *m = SetDeviceModeRequest{} }
func (m *SetDeviceModeRequest) String() string { return proto.CompactTextString(m) }
func (*SetDeviceModeRequest) ProtoMessage()    {}
func (*SetDeviceModeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b28b7c3f2b1e3cd0, []int{7}
}

func (m *SetDeviceModeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDeviceModeRequest.Unmarshal(m, b)
}
func (m *SetDeviceModeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDeviceModeRequest.Marshal(b, m, deterministic)
}
func (m *SetDeviceModeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDeviceModeRequest.Merge(m, src)
}
func (m *SetDeviceModeRequest) XXX_Size() int {
	return xxx_messageInfo_SetDeviceModeRequest.Size(m)
}
func (m *SetDeviceModeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDeviceModeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetDeviceModeRequest proto.InternalMessageInfo

func (m *SetDeviceModeRequest) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *SetDeviceModeRequest) GetDevId() int64 {
	if m != nil {
		return m.DevId
	}
	return 0
}

func (m *SetDeviceModeRequest) GetDevMode() DeviceMode {
	if m != nil {
		return m.DevMode
	}
	return DeviceMode_DV_INACTIVE
}

type SetDeviceModeResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetDeviceModeResponse) Reset()         { *m = SetDeviceModeResponse{} }
func (m *SetDeviceModeResponse) String() string { return proto.CompactTextString(m) }
func (*SetDeviceModeResponse) ProtoMessage()    {}
func (*SetDeviceModeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b28b7c3f2b1e3cd0, []int{8}
}

func (m *SetDeviceModeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDeviceModeResponse.Unmarshal(m, b)
}
func (m *SetDeviceModeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDeviceModeResponse.Marshal(b, m, deterministic)
}
func (m *SetDeviceModeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDeviceModeResponse.Merge(m, src)
}
func (m *SetDeviceModeResponse) XXX_Size() int {
	return xxx_messageInfo_SetDeviceModeResponse.Size(m)
}
func (m *SetDeviceModeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDeviceModeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetDeviceModeResponse proto.InternalMessageInfo

func (m *SetDeviceModeResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type DeviceStruct struct {
	DevEui               string               `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	ApplicationId        int64                `protobuf:"varint,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Name                 string               `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeviceStruct) Reset()         { *m = DeviceStruct{} }
func (m *DeviceStruct) String() string { return proto.CompactTextString(m) }
func (*DeviceStruct) ProtoMessage()    {}
func (*DeviceStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_b28b7c3f2b1e3cd0, []int{9}
}

func (m *DeviceStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceStruct.Unmarshal(m, b)
}
func (m *DeviceStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceStruct.Marshal(b, m, deterministic)
}
func (m *DeviceStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceStruct.Merge(m, src)
}
func (m *DeviceStruct) XXX_Size() int {
	return xxx_messageInfo_DeviceStruct.Size(m)
}
func (m *DeviceStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceStruct.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceStruct proto.InternalMessageInfo

func (m *DeviceStruct) GetDevEui() string {
	if m != nil {
		return m.DevEui
	}
	return ""
}

func (m *DeviceStruct) GetApplicationId() int64 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

func (m *DeviceStruct) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeviceStruct) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type AddDeviceRequest struct {
	OrgId                int64         `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	DevProfile           *DeviceStruct `protobuf:"bytes,2,opt,name=dev_profile,json=devProfile,proto3" json:"dev_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AddDeviceRequest) Reset()         { *m = AddDeviceRequest{} }
func (m *AddDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*AddDeviceRequest) ProtoMessage()    {}
func (*AddDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b28b7c3f2b1e3cd0, []int{10}
}

func (m *AddDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddDeviceRequest.Unmarshal(m, b)
}
func (m *AddDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddDeviceRequest.Marshal(b, m, deterministic)
}
func (m *AddDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddDeviceRequest.Merge(m, src)
}
func (m *AddDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_AddDeviceRequest.Size(m)
}
func (m *AddDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddDeviceRequest proto.InternalMessageInfo

func (m *AddDeviceRequest) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *AddDeviceRequest) GetDevProfile() *DeviceStruct {
	if m != nil {
		return m.DevProfile
	}
	return nil
}

type AddDeviceResponse struct {
	DevId                int64    `protobuf:"varint,1,opt,name=dev_id,json=devId,proto3" json:"dev_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddDeviceResponse) Reset()         { *m = AddDeviceResponse{} }
func (m *AddDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*AddDeviceResponse) ProtoMessage()    {}
func (*AddDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b28b7c3f2b1e3cd0, []int{11}
}

func (m *AddDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddDeviceResponse.Unmarshal(m, b)
}
func (m *AddDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddDeviceResponse.Marshal(b, m, deterministic)
}
func (m *AddDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddDeviceResponse.Merge(m, src)
}
func (m *AddDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_AddDeviceResponse.Size(m)
}
func (m *AddDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddDeviceResponse proto.InternalMessageInfo

func (m *AddDeviceResponse) GetDevId() int64 {
	if m != nil {
		return m.DevId
	}
	return 0
}

type DeleteDeviceRequest struct {
	DevEui               string   `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDeviceRequest) Reset()         { *m = DeleteDeviceRequest{} }
func (m *DeleteDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteDeviceRequest) ProtoMessage()    {}
func (*DeleteDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b28b7c3f2b1e3cd0, []int{12}
}

func (m *DeleteDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDeviceRequest.Unmarshal(m, b)
}
func (m *DeleteDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDeviceRequest.Marshal(b, m, deterministic)
}
func (m *DeleteDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDeviceRequest.Merge(m, src)
}
func (m *DeleteDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteDeviceRequest.Size(m)
}
func (m *DeleteDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDeviceRequest proto.InternalMessageInfo

func (m *DeleteDeviceRequest) GetDevEui() string {
	if m != nil {
		return m.DevEui
	}
	return ""
}

type DeleteDeviceResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDeviceResponse) Reset()         { *m = DeleteDeviceResponse{} }
func (m *DeleteDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteDeviceResponse) ProtoMessage()    {}
func (*DeleteDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b28b7c3f2b1e3cd0, []int{13}
}

func (m *DeleteDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDeviceResponse.Unmarshal(m, b)
}
func (m *DeleteDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDeviceResponse.Marshal(b, m, deterministic)
}
func (m *DeleteDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDeviceResponse.Merge(m, src)
}
func (m *DeleteDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteDeviceResponse.Size(m)
}
func (m *DeleteDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDeviceResponse proto.InternalMessageInfo

func (m *DeleteDeviceResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterEnum("m2m.DeviceMode", DeviceMode_name, DeviceMode_value)
	proto.RegisterType((*GetDeviceListRequest)(nil), "m2m.GetDeviceListRequest")
	proto.RegisterType((*GetDeviceListResponse)(nil), "m2m.GetDeviceListResponse")
	proto.RegisterType((*GetDSDeviceProfileRequest)(nil), "m2m.GetDSDeviceProfileRequest")
	proto.RegisterType((*DSDeviceProfile)(nil), "m2m.DSDeviceProfile")
	proto.RegisterType((*GetDSDeviceProfileResponse)(nil), "m2m.GetDSDeviceProfileResponse")
	proto.RegisterType((*GetDeviceHistoryRequest)(nil), "m2m.GetDeviceHistoryRequest")
	proto.RegisterType((*GetDeviceHistoryResponse)(nil), "m2m.GetDeviceHistoryResponse")
	proto.RegisterType((*SetDeviceModeRequest)(nil), "m2m.SetDeviceModeRequest")
	proto.RegisterType((*SetDeviceModeResponse)(nil), "m2m.SetDeviceModeResponse")
	proto.RegisterType((*DeviceStruct)(nil), "m2m.DeviceStruct")
	proto.RegisterType((*AddDeviceRequest)(nil), "m2m.AddDeviceRequest")
	proto.RegisterType((*AddDeviceResponse)(nil), "m2m.AddDeviceResponse")
	proto.RegisterType((*DeleteDeviceRequest)(nil), "m2m.DeleteDeviceRequest")
	proto.RegisterType((*DeleteDeviceResponse)(nil), "m2m.DeleteDeviceResponse")
}

func init() {
	proto.RegisterFile("mxprotocol-server/lpwan-app-server/device_item.proto", fileDescriptor_b28b7c3f2b1e3cd0)
}

var fileDescriptor_b28b7c3f2b1e3cd0 = []byte{
	// 793 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x6d, 0x4f, 0xfa, 0x56,
	0x14, 0x5f, 0x29, 0x22, 0x1c, 0x15, 0xf1, 0x0e, 0xb4, 0x74, 0x3a, 0x49, 0x97, 0x25, 0xc6, 0x44,
	0x4c, 0xd8, 0xf6, 0x62, 0xdb, 0x2b, 0x62, 0xab, 0x36, 0x43, 0x5d, 0x5a, 0x02, 0x59, 0x96, 0xa5,
	0xa9, 0xdc, 0x0b, 0x6b, 0x6c, 0x69, 0xd7, 0xde, 0xe2, 0xf6, 0x61, 0xf6, 0x7d, 0xf6, 0x91, 0xf6,
	0x72, 0xe9, 0xed, 0x05, 0x5a, 0x2c, 0xee, 0x1f, 0x5f, 0xb5, 0xf7, 0x3c, 0xfc, 0xce, 0xd3, 0xef,
	0x1c, 0xf8, 0xd6, 0xfb, 0x33, 0x08, 0x7d, 0xea, 0x4f, 0x7c, 0xf7, 0x2a, 0x22, 0xe1, 0x82, 0x84,
	0xd7, 0x6e, 0xf0, 0x6a, 0xcf, 0xaf, 0xec, 0x20, 0x58, 0x0a, 0x30, 0x59, 0x38, 0x13, 0x62, 0x39,
	0x94, 0x78, 0x5d, 0x66, 0x8c, 0x44, 0xaf, 0xe7, 0xc9, 0x6d, 0xea, 0x78, 0x24, 0xa2, 0xb6, 0x17,
	0x5c, 0xaf, 0xfe, 0x52, 0xbd, 0xf2, 0x2b, 0x34, 0xef, 0x08, 0x55, 0x99, 0xdf, 0xc0, 0x89, 0xa8,
	0x41, 0xfe, 0x88, 0x49, 0x44, 0x51, 0x0b, 0x2a, 0x7e, 0x38, 0xb3, 0x1c, 0x2c, 0x09, 0x1d, 0xe1,
	0x42, 0x34, 0x76, 0xfc, 0x70, 0xa6, 0x63, 0x74, 0x0c, 0x15, 0x7f, 0x3a, 0x8d, 0x08, 0x95, 0x4a,
	0x4c, 0xcc, 0x5f, 0xa8, 0x09, 0x3b, 0xae, 0xe3, 0x39, 0x54, 0x12, 0x53, 0x6b, 0xf6, 0x50, 0x30,
	0xb4, 0x36, 0xc0, 0xa3, 0xc0, 0x9f, 0x47, 0x04, 0x7d, 0x07, 0x7b, 0x98, 0x2c, 0xac, 0x20, 0xf4,
	0xa7, 0x8e, 0x4b, 0x24, 0xa1, 0x23, 0x5e, 0xec, 0xf5, 0x9a, 0x5d, 0xaf, 0xe7, 0x75, 0x55, 0x33,
	0xb5, 0xff, 0x39, 0xd5, 0x19, 0x80, 0xc9, 0x82, 0xff, 0x27, 0x51, 0x26, 0x7e, 0x3c, 0x5f, 0x06,
	0x4f, 0x1f, 0x8a, 0x0e, 0xed, 0x24, 0xca, 0x86, 0xdf, 0xfb, 0x75, 0xb4, 0xa0, 0x92, 0x24, 0xe0,
	0xe0, 0x25, 0x14, 0x26, 0x0b, 0x1d, 0x2b, 0xff, 0x0a, 0x70, 0xb8, 0x01, 0x84, 0xea, 0x50, 0x5a,
	0x79, 0x97, 0x1c, 0x8c, 0x4e, 0x60, 0x37, 0x71, 0x25, 0xb1, 0xc3, 0x7c, 0x6b, 0x46, 0x82, 0xa4,
	0xc5, 0x0e, 0xfa, 0x02, 0x6a, 0xd3, 0x17, 0xeb, 0xd5, 0x76, 0x5d, 0xb2, 0xec, 0x43, 0x75, 0xfa,
	0x32, 0x66, 0x6f, 0xf4, 0x15, 0x94, 0x3d, 0x1f, 0x13, 0xa9, 0xdc, 0x11, 0x2e, 0xea, 0xbd, 0xc3,
	0xb4, 0x54, 0x16, 0xe7, 0xc1, 0xc7, 0xc4, 0x60, 0x4a, 0x74, 0x06, 0x30, 0x09, 0x89, 0x4d, 0x09,
	0xb6, 0x6c, 0x2a, 0xed, 0x30, 0xf4, 0x1a, 0x97, 0xf4, 0x29, 0xea, 0xc0, 0xbe, 0x6b, 0x47, 0xd4,
	0x8a, 0x08, 0x99, 0x27, 0x06, 0x15, 0x66, 0x00, 0x89, 0xcc, 0x24, 0x64, 0xde, 0xa7, 0xe8, 0x6b,
	0xa8, 0xdb, 0x41, 0xe0, 0x3a, 0x13, 0x9b, 0x3a, 0xfe, 0x3c, 0x29, 0x6f, 0x97, 0xe5, 0x71, 0x90,
	0x91, 0xea, 0x18, 0x21, 0x28, 0xcf, 0x6d, 0x8f, 0x48, 0x55, 0x06, 0xc0, 0xfe, 0x15, 0x13, 0xe4,
	0xa2, 0x2e, 0x6e, 0x1b, 0x98, 0xf0, 0x29, 0x03, 0x53, 0x62, 0x38, 0x59, 0x11, 0xe0, 0xde, 0x89,
	0xa8, 0x1f, 0xfe, 0xf5, 0xa1, 0xc1, 0x64, 0x78, 0x27, 0x16, 0xf3, 0xae, 0x9c, 0xe5, 0xdd, 0x8f,
	0x20, 0xbd, 0x0d, 0xcb, 0x2b, 0x39, 0x4f, 0x2b, 0xf9, 0x3d, 0x15, 0xb3, 0xe0, 0x35, 0x96, 0x33,
	0x37, 0x54, 0x02, 0x68, 0x9a, 0x4b, 0x67, 0x36, 0x9b, 0x0f, 0x25, 0x7c, 0x09, 0xd5, 0x44, 0xcc,
	0x66, 0x2e, 0x16, 0xcf, 0x3c, 0xa1, 0x51, 0xf2, 0xa3, 0x5c, 0x43, 0x6b, 0x23, 0x22, 0xcf, 0xf5,
	0x18, 0x2a, 0x11, 0xb5, 0x69, 0x1c, 0xb1, 0x90, 0x55, 0x83, 0xbf, 0x94, 0xbf, 0x05, 0xd8, 0x4f,
	0xcd, 0x4d, 0x1a, 0xc6, 0x13, 0x9a, 0xe5, 0xa4, 0x90, 0xe3, 0xe4, 0x5b, 0x42, 0x94, 0xde, 0x23,
	0x84, 0xb8, 0x26, 0x04, 0xfa, 0x3e, 0x47, 0xc6, 0x32, 0x9b, 0xb8, 0xdc, 0x9d, 0xf9, 0xfe, 0xcc,
	0x25, 0xe9, 0xf1, 0x78, 0x8e, 0xa7, 0xdd, 0xe1, 0xf2, 0x9e, 0x64, 0x88, 0xaa, 0xfc, 0x06, 0x8d,
	0x3e, 0xc6, 0x69, 0x86, 0xff, 0xd3, 0xbe, 0x5e, 0x9e, 0x58, 0x25, 0x16, 0xe6, 0x28, 0xd3, 0xaa,
	0xb4, 0xc2, 0x1c, 0xab, 0x2e, 0xe1, 0x28, 0x03, 0xcf, 0x7b, 0xb5, 0x9e, 0x83, 0x90, 0xdd, 0xe8,
	0x2e, 0x7c, 0xae, 0x12, 0x97, 0x50, 0x92, 0xcf, 0x66, 0x5b, 0xc3, 0x94, 0x2e, 0x34, 0xf3, 0xf6,
	0xef, 0x8f, 0xe2, 0xd2, 0x06, 0x58, 0x0f, 0x0e, 0x1d, 0xc2, 0x9e, 0x3a, 0xb2, 0xf4, 0xc7, 0xfe,
	0xcd, 0x50, 0x1f, 0x69, 0x8d, 0xcf, 0xd0, 0x29, 0x48, 0xea, 0xc8, 0xba, 0x35, 0x34, 0xcd, 0xba,
	0xeb, 0x0f, 0xb5, 0x71, 0xff, 0x17, 0xd3, 0x1a, 0xe8, 0x0f, 0xfa, 0x50, 0x53, 0x1b, 0x02, 0x6a,
	0x42, 0x43, 0x1d, 0x59, 0xe3, 0xfb, 0xa7, 0x81, 0x66, 0x3d, 0x6a, 0xc3, 0xf1, 0x93, 0xf1, 0x53,
	0xa3, 0x84, 0xea, 0x00, 0xea, 0xc8, 0x52, 0xb5, 0x81, 0x96, 0x58, 0x89, 0xbd, 0x7f, 0xc4, 0xf5,
	0x51, 0x32, 0x49, 0x98, 0x7c, 0xd0, 0x2d, 0x1c, 0xe4, 0x2e, 0x2b, 0x6a, 0xb3, 0x96, 0x15, 0x9d,
	0x72, 0x59, 0x2e, 0x52, 0xf1, 0xb2, 0x4c, 0x68, 0xac, 0x14, 0xcb, 0x83, 0xf7, 0xe5, 0xca, 0xbe,
	0xf0, 0xa4, 0xca, 0xe7, 0x5b, 0xf5, 0x1c, 0xf4, 0x29, 0x03, 0xca, 0xb7, 0x0a, 0x9d, 0xe6, 0x93,
	0xc8, 0x1f, 0x03, 0xf9, 0x6c, 0x8b, 0x96, 0x03, 0xde, 0xc2, 0x41, 0x6e, 0x41, 0x78, 0xb5, 0x45,
	0x6b, 0xca, 0xab, 0x2d, 0xde, 0xa7, 0x1f, 0xa0, 0xb6, 0x22, 0x0e, 0x6a, 0x31, 0xc3, 0x4d, 0x9e,
	0xca, 0xc7, 0x9b, 0x62, 0xee, 0x7b, 0x93, 0xac, 0xdc, 0x9a, 0x18, 0x48, 0xe2, 0x1c, 0x7d, 0xc3,
	0x2d, 0xb9, 0x5d, 0xa0, 0x49, 0x41, 0x9e, 0x2b, 0x6c, 0x6f, 0xbe, 0xf9, 0x2f, 0x00, 0x00, 0xff,
	0xff, 0x61, 0x42, 0xae, 0xba, 0xcc, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DSDeviceServiceClient is the client API for DSDeviceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DSDeviceServiceClient interface {
	GetDeviceList(ctx context.Context, in *GetDeviceListRequest, opts ...grpc.CallOption) (*GetDeviceListResponse, error)
	GetDeviceProfile(ctx context.Context, in *GetDSDeviceProfileRequest, opts ...grpc.CallOption) (*GetDSDeviceProfileResponse, error)
	GetDeviceHistory(ctx context.Context, in *GetDeviceHistoryRequest, opts ...grpc.CallOption) (*GetDeviceHistoryResponse, error)
	SetDeviceMode(ctx context.Context, in *SetDeviceModeRequest, opts ...grpc.CallOption) (*SetDeviceModeResponse, error)
	AddDevice(ctx context.Context, in *AddDeviceRequest, opts ...grpc.CallOption) (*AddDeviceResponse, error)
	DeleteDevice(ctx context.Context, in *DeleteDeviceRequest, opts ...grpc.CallOption) (*DeleteDeviceResponse, error)
}

type dSDeviceServiceClient struct {
	cc *grpc.ClientConn
}

func NewDSDeviceServiceClient(cc *grpc.ClientConn) DSDeviceServiceClient {
	return &dSDeviceServiceClient{cc}
}

func (c *dSDeviceServiceClient) GetDeviceList(ctx context.Context, in *GetDeviceListRequest, opts ...grpc.CallOption) (*GetDeviceListResponse, error) {
	out := new(GetDeviceListResponse)
	err := c.cc.Invoke(ctx, "/m2m.DSDeviceService/GetDeviceList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dSDeviceServiceClient) GetDeviceProfile(ctx context.Context, in *GetDSDeviceProfileRequest, opts ...grpc.CallOption) (*GetDSDeviceProfileResponse, error) {
	out := new(GetDSDeviceProfileResponse)
	err := c.cc.Invoke(ctx, "/m2m.DSDeviceService/GetDeviceProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dSDeviceServiceClient) GetDeviceHistory(ctx context.Context, in *GetDeviceHistoryRequest, opts ...grpc.CallOption) (*GetDeviceHistoryResponse, error) {
	out := new(GetDeviceHistoryResponse)
	err := c.cc.Invoke(ctx, "/m2m.DSDeviceService/GetDeviceHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dSDeviceServiceClient) SetDeviceMode(ctx context.Context, in *SetDeviceModeRequest, opts ...grpc.CallOption) (*SetDeviceModeResponse, error) {
	out := new(SetDeviceModeResponse)
	err := c.cc.Invoke(ctx, "/m2m.DSDeviceService/SetDeviceMode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dSDeviceServiceClient) AddDevice(ctx context.Context, in *AddDeviceRequest, opts ...grpc.CallOption) (*AddDeviceResponse, error) {
	out := new(AddDeviceResponse)
	err := c.cc.Invoke(ctx, "/m2m.DSDeviceService/AddDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dSDeviceServiceClient) DeleteDevice(ctx context.Context, in *DeleteDeviceRequest, opts ...grpc.CallOption) (*DeleteDeviceResponse, error) {
	out := new(DeleteDeviceResponse)
	err := c.cc.Invoke(ctx, "/m2m.DSDeviceService/DeleteDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DSDeviceServiceServer is the server API for DSDeviceService service.
type DSDeviceServiceServer interface {
	GetDeviceList(context.Context, *GetDeviceListRequest) (*GetDeviceListResponse, error)
	GetDeviceProfile(context.Context, *GetDSDeviceProfileRequest) (*GetDSDeviceProfileResponse, error)
	GetDeviceHistory(context.Context, *GetDeviceHistoryRequest) (*GetDeviceHistoryResponse, error)
	SetDeviceMode(context.Context, *SetDeviceModeRequest) (*SetDeviceModeResponse, error)
	AddDevice(context.Context, *AddDeviceRequest) (*AddDeviceResponse, error)
	DeleteDevice(context.Context, *DeleteDeviceRequest) (*DeleteDeviceResponse, error)
}

// UnimplementedDSDeviceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDSDeviceServiceServer struct {
}

func (*UnimplementedDSDeviceServiceServer) GetDeviceList(ctx context.Context, req *GetDeviceListRequest) (*GetDeviceListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceList not implemented")
}
func (*UnimplementedDSDeviceServiceServer) GetDeviceProfile(ctx context.Context, req *GetDSDeviceProfileRequest) (*GetDSDeviceProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceProfile not implemented")
}
func (*UnimplementedDSDeviceServiceServer) GetDeviceHistory(ctx context.Context, req *GetDeviceHistoryRequest) (*GetDeviceHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceHistory not implemented")
}
func (*UnimplementedDSDeviceServiceServer) SetDeviceMode(ctx context.Context, req *SetDeviceModeRequest) (*SetDeviceModeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDeviceMode not implemented")
}
func (*UnimplementedDSDeviceServiceServer) AddDevice(ctx context.Context, req *AddDeviceRequest) (*AddDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDevice not implemented")
}
func (*UnimplementedDSDeviceServiceServer) DeleteDevice(ctx context.Context, req *DeleteDeviceRequest) (*DeleteDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDevice not implemented")
}

func RegisterDSDeviceServiceServer(s *grpc.Server, srv DSDeviceServiceServer) {
	s.RegisterService(&_DSDeviceService_serviceDesc, srv)
}

func _DSDeviceService_GetDeviceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSDeviceServiceServer).GetDeviceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m2m.DSDeviceService/GetDeviceList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSDeviceServiceServer).GetDeviceList(ctx, req.(*GetDeviceListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DSDeviceService_GetDeviceProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDSDeviceProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSDeviceServiceServer).GetDeviceProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m2m.DSDeviceService/GetDeviceProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSDeviceServiceServer).GetDeviceProfile(ctx, req.(*GetDSDeviceProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DSDeviceService_GetDeviceHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSDeviceServiceServer).GetDeviceHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m2m.DSDeviceService/GetDeviceHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSDeviceServiceServer).GetDeviceHistory(ctx, req.(*GetDeviceHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DSDeviceService_SetDeviceMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDeviceModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSDeviceServiceServer).SetDeviceMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m2m.DSDeviceService/SetDeviceMode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSDeviceServiceServer).SetDeviceMode(ctx, req.(*SetDeviceModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DSDeviceService_AddDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSDeviceServiceServer).AddDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m2m.DSDeviceService/AddDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSDeviceServiceServer).AddDevice(ctx, req.(*AddDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DSDeviceService_DeleteDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSDeviceServiceServer).DeleteDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m2m.DSDeviceService/DeleteDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSDeviceServiceServer).DeleteDevice(ctx, req.(*DeleteDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DSDeviceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "m2m.DSDeviceService",
	HandlerType: (*DSDeviceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDeviceList",
			Handler:    _DSDeviceService_GetDeviceList_Handler,
		},
		{
			MethodName: "GetDeviceProfile",
			Handler:    _DSDeviceService_GetDeviceProfile_Handler,
		},
		{
			MethodName: "GetDeviceHistory",
			Handler:    _DSDeviceService_GetDeviceHistory_Handler,
		},
		{
			MethodName: "SetDeviceMode",
			Handler:    _DSDeviceService_SetDeviceMode_Handler,
		},
		{
			MethodName: "AddDevice",
			Handler:    _DSDeviceService_AddDevice_Handler,
		},
		{
			MethodName: "DeleteDevice",
			Handler:    _DSDeviceService_DeleteDevice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mxprotocol-server/lpwan-app-server/device_item.proto",
}
