// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mxprotocol-server/lpwan-app-server/mining.proto

package m2m

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// MiningRequest sends gateway list to m2m
type MiningRequest struct {
	GatewayMac           []string `protobuf:"bytes,1,rep,name=gateway_mac,json=gatewayMac,proto3" json:"gateway_mac,omitempty"`
	MiningRevenue        float64  `protobuf:"fixed64,2,opt,name=mining_revenue,json=miningRevenue,proto3" json:"mining_revenue,omitempty"`
	MxcPrice             float64  `protobuf:"fixed64,3,opt,name=mxc_price,json=mxcPrice,proto3" json:"mxc_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MiningRequest) Reset()         { *m = MiningRequest{} }
func (m *MiningRequest) String() string { return proto.CompactTextString(m) }
func (*MiningRequest) ProtoMessage()    {}
func (*MiningRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d961e739e3c6bf1, []int{0}
}

func (m *MiningRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MiningRequest.Unmarshal(m, b)
}
func (m *MiningRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MiningRequest.Marshal(b, m, deterministic)
}
func (m *MiningRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MiningRequest.Merge(m, src)
}
func (m *MiningRequest) XXX_Size() int {
	return xxx_messageInfo_MiningRequest.Size(m)
}
func (m *MiningRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MiningRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MiningRequest proto.InternalMessageInfo

func (m *MiningRequest) GetGatewayMac() []string {
	if m != nil {
		return m.GatewayMac
	}
	return nil
}

func (m *MiningRequest) GetMiningRevenue() float64 {
	if m != nil {
		return m.MiningRevenue
	}
	return 0
}

func (m *MiningRequest) GetMxcPrice() float64 {
	if m != nil {
		return m.MxcPrice
	}
	return 0
}

type MiningResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MiningResponse) Reset()         { *m = MiningResponse{} }
func (m *MiningResponse) String() string { return proto.CompactTextString(m) }
func (*MiningResponse) ProtoMessage()    {}
func (*MiningResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d961e739e3c6bf1, []int{1}
}

func (m *MiningResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MiningResponse.Unmarshal(m, b)
}
func (m *MiningResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MiningResponse.Marshal(b, m, deterministic)
}
func (m *MiningResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MiningResponse.Merge(m, src)
}
func (m *MiningResponse) XXX_Size() int {
	return xxx_messageInfo_MiningResponse.Size(m)
}
func (m *MiningResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MiningResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MiningResponse proto.InternalMessageInfo

func (m *MiningResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*MiningRequest)(nil), "m2m.MiningRequest")
	proto.RegisterType((*MiningResponse)(nil), "m2m.MiningResponse")
}

func init() {
	proto.RegisterFile("mxprotocol-server/lpwan-app-server/mining.proto", fileDescriptor_8d961e739e3c6bf1)
}

var fileDescriptor_8d961e739e3c6bf1 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x41, 0x6a, 0xc3, 0x30,
	0x10, 0x45, 0x51, 0x0d, 0x26, 0x99, 0x92, 0x2c, 0xa6, 0x50, 0x4c, 0xbb, 0xa8, 0x09, 0x14, 0xbc,
	0x89, 0x43, 0xdd, 0x1b, 0x74, 0x1f, 0x28, 0xee, 0x01, 0x8c, 0x2a, 0x86, 0x20, 0xc8, 0x48, 0xaa,
	0x24, 0x3b, 0xee, 0xed, 0x4b, 0x65, 0x7b, 0xe1, 0xe5, 0x7f, 0x7c, 0xde, 0xfc, 0x81, 0x13, 0x8f,
	0xce, 0xdb, 0x68, 0x95, 0xbd, 0x1e, 0x03, 0xf9, 0x81, 0xfc, 0xe9, 0xea, 0x6e, 0xd2, 0x1c, 0xa5,
	0x73, 0x0b, 0x60, 0x6d, 0xb4, 0xb9, 0xd4, 0xa9, 0x87, 0x19, 0x37, 0x7c, 0x88, 0xb0, 0x3b, 0x27,
	0xd8, 0xd2, 0x4f, 0x4f, 0x21, 0xe2, 0x0b, 0xdc, 0x5f, 0x64, 0xa4, 0x9b, 0xfc, 0xed, 0x58, 0xaa,
	0x42, 0x94, 0x59, 0xb5, 0x6d, 0x61, 0x46, 0x67, 0xa9, 0xf0, 0x15, 0xf6, 0x93, 0xa6, 0xf3, 0x34,
	0x90, 0xe9, 0xa9, 0xb8, 0x2b, 0x45, 0x25, 0xda, 0x1d, 0xcf, 0x9e, 0x04, 0xf1, 0x19, 0xb6, 0x3c,
	0xaa, 0xce, 0x79, 0xad, 0xa8, 0xc8, 0x52, 0x63, 0xc3, 0xa3, 0xfa, 0xfc, 0xcf, 0x87, 0x0a, 0xf6,
	0xcb, 0xd5, 0xe0, 0xac, 0x09, 0x84, 0x8f, 0x90, 0x87, 0x28, 0x63, 0x1f, 0x0a, 0x51, 0x8a, 0x6a,
	0xd3, 0xce, 0xa9, 0xf9, 0x58, 0xf6, 0x7d, 0x91, 0x1f, 0xb4, 0x22, 0x7c, 0x83, 0x7c, 0x02, 0x88,
	0x35, 0x37, 0x5c, 0xaf, 0xd6, 0x3f, 0x3d, 0xac, 0xd8, 0xe4, 0xfe, 0xce, 0xd3, 0xbf, 0xef, 0x7f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xdc, 0xc3, 0xba, 0x3a, 0x22, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MiningServiceClient is the client API for MiningService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MiningServiceClient interface {
	Mining(ctx context.Context, in *MiningRequest, opts ...grpc.CallOption) (*MiningResponse, error)
}

type miningServiceClient struct {
	cc *grpc.ClientConn
}

func NewMiningServiceClient(cc *grpc.ClientConn) MiningServiceClient {
	return &miningServiceClient{cc}
}

func (c *miningServiceClient) Mining(ctx context.Context, in *MiningRequest, opts ...grpc.CallOption) (*MiningResponse, error) {
	out := new(MiningResponse)
	err := c.cc.Invoke(ctx, "/m2m.MiningService/Mining", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MiningServiceServer is the server API for MiningService service.
type MiningServiceServer interface {
	Mining(context.Context, *MiningRequest) (*MiningResponse, error)
}

// UnimplementedMiningServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMiningServiceServer struct {
}

func (*UnimplementedMiningServiceServer) Mining(ctx context.Context, req *MiningRequest) (*MiningResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mining not implemented")
}

func RegisterMiningServiceServer(s *grpc.Server, srv MiningServiceServer) {
	s.RegisterService(&_MiningService_serviceDesc, srv)
}

func _MiningService_Mining_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MiningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiningServiceServer).Mining(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m2m.MiningService/Mining",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiningServiceServer).Mining(ctx, req.(*MiningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MiningService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "m2m.MiningService",
	HandlerType: (*MiningServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Mining",
			Handler:    _MiningService_Mining_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mxprotocol-server/lpwan-app-server/mining.proto",
}
