// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lpwan-server/common/common.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Modulation int32

const (
	// LoRa
	Modulation_LORA Modulation = 0
	// FSK
	Modulation_FSK Modulation = 1
)

var Modulation_name = map[int32]string{
	0: "LORA",
	1: "FSK",
}

var Modulation_value = map[string]int32{
	"LORA": 0,
	"FSK":  1,
}

func (x Modulation) String() string {
	return proto.EnumName(Modulation_name, int32(x))
}

func (Modulation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e59973a2677afee0, []int{0}
}

type Region int32

const (
	// EU868
	Region_EU868 Region = 0
	// US915
	Region_US915 Region = 2
	// CN779
	Region_CN779 Region = 3
	// EU433
	Region_EU433 Region = 4
	// AU915
	Region_AU915 Region = 5
	// CN470
	Region_CN470 Region = 6
	// AS923
	Region_AS923 Region = 7
	// KR920
	Region_KR920 Region = 8
	// IN865
	Region_IN865 Region = 9
	// RU864
	Region_RU864 Region = 10
)

var Region_name = map[int32]string{
	0:  "EU868",
	2:  "US915",
	3:  "CN779",
	4:  "EU433",
	5:  "AU915",
	6:  "CN470",
	7:  "AS923",
	8:  "KR920",
	9:  "IN865",
	10: "RU864",
}

var Region_value = map[string]int32{
	"EU868": 0,
	"US915": 2,
	"CN779": 3,
	"EU433": 4,
	"AU915": 5,
	"CN470": 6,
	"AS923": 7,
	"KR920": 8,
	"IN865": 9,
	"RU864": 10,
}

func (x Region) String() string {
	return proto.EnumName(Region_name, int32(x))
}

func (Region) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e59973a2677afee0, []int{1}
}

type LocationSource int32

const (
	// Unknown.
	LocationSource_UNKNOWN LocationSource = 0
	// GPS.
	LocationSource_GPS LocationSource = 1
	// Manually configured.
	LocationSource_CONFIG LocationSource = 2
	// Geo resolver.
	LocationSource_GEO_RESOLVER LocationSource = 3
)

var LocationSource_name = map[int32]string{
	0: "UNKNOWN",
	1: "GPS",
	2: "CONFIG",
	3: "GEO_RESOLVER",
}

var LocationSource_value = map[string]int32{
	"UNKNOWN":      0,
	"GPS":          1,
	"CONFIG":       2,
	"GEO_RESOLVER": 3,
}

func (x LocationSource) String() string {
	return proto.EnumName(LocationSource_name, int32(x))
}

func (LocationSource) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e59973a2677afee0, []int{2}
}

type KeyEnvelope struct {
	// KEK label.
	KekLabel string `protobuf:"bytes,1,opt,name=kek_label,json=kekLabel,proto3" json:"kek_label,omitempty"`
	// AES key (when the kek_label is set, this key is encrypted using a key
	// known to the join-server and application-server.
	// For more information please refer to the LoRaWAN Backend Interface
	// 'Key Transport Security' section.
	AesKey               []byte   `protobuf:"bytes,2,opt,name=aes_key,json=aesKey,proto3" json:"aes_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyEnvelope) Reset()         { *m = KeyEnvelope{} }
func (m *KeyEnvelope) String() string { return proto.CompactTextString(m) }
func (*KeyEnvelope) ProtoMessage()    {}
func (*KeyEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_e59973a2677afee0, []int{0}
}

func (m *KeyEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyEnvelope.Unmarshal(m, b)
}
func (m *KeyEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyEnvelope.Marshal(b, m, deterministic)
}
func (m *KeyEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyEnvelope.Merge(m, src)
}
func (m *KeyEnvelope) XXX_Size() int {
	return xxx_messageInfo_KeyEnvelope.Size(m)
}
func (m *KeyEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_KeyEnvelope proto.InternalMessageInfo

func (m *KeyEnvelope) GetKekLabel() string {
	if m != nil {
		return m.KekLabel
	}
	return ""
}

func (m *KeyEnvelope) GetAesKey() []byte {
	if m != nil {
		return m.AesKey
	}
	return nil
}

type Location struct {
	// Latitude.
	Latitude float64 `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	// Longitude.
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	// Altitude.
	Altitude float64 `protobuf:"fixed64,3,opt,name=altitude,proto3" json:"altitude,omitempty"`
	// Location source.
	Source LocationSource `protobuf:"varint,4,opt,name=source,proto3,enum=common.LocationSource" json:"source,omitempty"`
	// Accuracy (in meters).
	Accuracy             uint32   `protobuf:"varint,5,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_e59973a2677afee0, []int{1}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Location) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Location) GetAltitude() float64 {
	if m != nil {
		return m.Altitude
	}
	return 0
}

func (m *Location) GetSource() LocationSource {
	if m != nil {
		return m.Source
	}
	return LocationSource_UNKNOWN
}

func (m *Location) GetAccuracy() uint32 {
	if m != nil {
		return m.Accuracy
	}
	return 0
}

type ContextDetails struct {
	// Context ID (UUID).
	ContextId            []byte   `protobuf:"bytes,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContextDetails) Reset()         { *m = ContextDetails{} }
func (m *ContextDetails) String() string { return proto.CompactTextString(m) }
func (*ContextDetails) ProtoMessage()    {}
func (*ContextDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_e59973a2677afee0, []int{2}
}

func (m *ContextDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContextDetails.Unmarshal(m, b)
}
func (m *ContextDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContextDetails.Marshal(b, m, deterministic)
}
func (m *ContextDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContextDetails.Merge(m, src)
}
func (m *ContextDetails) XXX_Size() int {
	return xxx_messageInfo_ContextDetails.Size(m)
}
func (m *ContextDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_ContextDetails.DiscardUnknown(m)
}

var xxx_messageInfo_ContextDetails proto.InternalMessageInfo

func (m *ContextDetails) GetContextId() []byte {
	if m != nil {
		return m.ContextId
	}
	return nil
}

func init() {
	proto.RegisterEnum("common.Modulation", Modulation_name, Modulation_value)
	proto.RegisterEnum("common.Region", Region_name, Region_value)
	proto.RegisterEnum("common.LocationSource", LocationSource_name, LocationSource_value)
	proto.RegisterType((*KeyEnvelope)(nil), "common.KeyEnvelope")
	proto.RegisterType((*Location)(nil), "common.Location")
	proto.RegisterType((*ContextDetails)(nil), "common.ContextDetails")
}

func init() { proto.RegisterFile("lpwan-server/common/common.proto", fileDescriptor_e59973a2677afee0) }

var fileDescriptor_e59973a2677afee0 = []byte{
	// 442 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x52, 0x5b, 0x8f, 0x9a, 0x40,
	0x14, 0x5e, 0xbc, 0x20, 0x9c, 0xb5, 0x66, 0x32, 0x0f, 0xad, 0xe9, 0x25, 0x25, 0x3e, 0x19, 0x93,
	0xd5, 0x5d, 0x71, 0xbd, 0x3c, 0x6e, 0x5d, 0xd6, 0x18, 0x2c, 0x34, 0x43, 0x68, 0x93, 0xbe, 0x98,
	0x11, 0xa6, 0x96, 0x80, 0x8c, 0xe1, 0x62, 0xd7, 0xff, 0xd4, 0x1f, 0xd9, 0x0c, 0xb0, 0xdb, 0xf8,
	0xc4, 0x77, 0x3b, 0x87, 0x73, 0x26, 0x07, 0xb4, 0xe8, 0xf8, 0x87, 0xc6, 0x37, 0x29, 0x4b, 0x4e,
	0x2c, 0x19, 0x79, 0xfc, 0x70, 0xe0, 0x71, 0xf5, 0x19, 0x1e, 0x13, 0x9e, 0x71, 0x2c, 0x97, 0xac,
	0xb7, 0x84, 0x6b, 0x93, 0x9d, 0x8d, 0xf8, 0xc4, 0x22, 0x7e, 0x64, 0xf8, 0x03, 0xa8, 0x21, 0x0b,
	0xb7, 0x11, 0xdd, 0xb1, 0xa8, 0x2b, 0x69, 0x52, 0x5f, 0x25, 0x4a, 0xc8, 0xc2, 0x8d, 0xe0, 0xf8,
	0x1d, 0xb4, 0x28, 0x4b, 0xb7, 0x21, 0x3b, 0x77, 0x6b, 0x9a, 0xd4, 0x6f, 0x13, 0x99, 0xb2, 0xd4,
	0x64, 0xe7, 0xde, 0x5f, 0x09, 0x94, 0x0d, 0xf7, 0x68, 0x16, 0xf0, 0x18, 0xbf, 0x07, 0x25, 0xa2,
	0x59, 0x90, 0xe5, 0x3e, 0x2b, 0x3a, 0x48, 0xe4, 0x95, 0xe3, 0x8f, 0xa0, 0x46, 0x3c, 0xde, 0x97,
	0x66, 0xad, 0x30, 0xff, 0x0b, 0xa2, 0x92, 0x46, 0x55, 0x65, 0xbd, 0xac, 0x7c, 0xe1, 0x78, 0x08,
	0x72, 0xca, 0xf3, 0xc4, 0x63, 0xdd, 0x86, 0x26, 0xf5, 0x3b, 0xe3, 0xb7, 0xc3, 0x6a, 0x9d, 0x97,
	0xff, 0x3a, 0x85, 0x4b, 0xaa, 0x54, 0xd1, 0xcb, 0xf3, 0xf2, 0x84, 0x7a, 0xe7, 0x6e, 0x53, 0x93,
	0xfa, 0x6f, 0xc8, 0x2b, 0xef, 0x8d, 0xa0, 0xb3, 0xe4, 0x71, 0xc6, 0x9e, 0xb3, 0x47, 0x96, 0xd1,
	0x20, 0x4a, 0xf1, 0x27, 0x00, 0xaf, 0x54, 0xb6, 0x81, 0x5f, 0x4c, 0xdd, 0x26, 0x6a, 0xa5, 0xac,
	0xfd, 0xc1, 0x67, 0x80, 0xaf, 0xdc, 0xcf, 0xa3, 0x72, 0x41, 0x05, 0x1a, 0x1b, 0x9b, 0x3c, 0xa0,
	0x2b, 0xdc, 0x82, 0xfa, 0x93, 0x63, 0x22, 0x69, 0x70, 0x02, 0x99, 0xb0, 0xbd, 0x30, 0x55, 0x68,
	0x1a, 0xee, 0x7c, 0x3a, 0x47, 0x57, 0x02, 0xba, 0xce, 0xe2, 0xee, 0x1e, 0xd5, 0x04, 0x5c, 0x5a,
	0xb3, 0xd9, 0x02, 0xd5, 0xcb, 0xc0, 0x44, 0xd7, 0x51, 0x43, 0xc0, 0x07, 0x57, 0x04, 0x9a, 0x65,
	0x60, 0x32, 0xbb, 0x45, 0x72, 0xa1, 0x3a, 0x8b, 0xb1, 0x8e, 0x5a, 0x02, 0x9a, 0x64, 0x31, 0xbe,
	0x45, 0x8a, 0x80, 0x6b, 0x6b, 0x3e, 0xbd, 0x47, 0xaa, 0x80, 0xc4, 0x9d, 0x4f, 0x27, 0x08, 0x06,
	0x8f, 0xd0, 0xb9, 0xdc, 0x1f, 0x5f, 0x43, 0xcb, 0xb5, 0x4c, 0xcb, 0xfe, 0x61, 0x95, 0xf3, 0xad,
	0xbe, 0x39, 0x48, 0xc2, 0x00, 0xf2, 0xd2, 0xb6, 0x9e, 0xd6, 0x2b, 0x54, 0xc3, 0x08, 0xda, 0x2b,
	0xc3, 0xde, 0x12, 0xc3, 0xb1, 0x37, 0xdf, 0x0d, 0x82, 0xea, 0x5f, 0xf4, 0x9f, 0x77, 0xfb, 0x20,
	0xfb, 0x9d, 0xef, 0xc4, 0x9b, 0x8e, 0x0e, 0xcf, 0xde, 0xcd, 0x2f, 0x9e, 0xc7, 0x7e, 0xd1, 0x76,
	0x74, 0x71, 0x49, 0xf4, 0x18, 0x54, 0x67, 0xb4, 0x93, 0x8b, 0x3b, 0xd2, 0xff, 0x05, 0x00, 0x00,
	0xff, 0xff, 0x01, 0xc5, 0xca, 0x71, 0x6b, 0x02, 0x00, 0x00,
}
