// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lpwan-app-server/ui/internal.proto

package ui

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Language int32

const (
	Language_de   Language = 0
	Language_en   Language = 1
	Language_es   Language = 2
	Language_fr   Language = 3
	Language_ja   Language = 4
	Language_ko   Language = 5
	Language_nl   Language = 6
	Language_ru   Language = 7
	Language_zhCN Language = 8
	Language_zhTW Language = 9
)

var Language_name = map[int32]string{
	0: "de",
	1: "en",
	2: "es",
	3: "fr",
	4: "ja",
	5: "ko",
	6: "nl",
	7: "ru",
	8: "zhCN",
	9: "zhTW",
}

var Language_value = map[string]int32{
	"de":   0,
	"en":   1,
	"es":   2,
	"fr":   3,
	"ja":   4,
	"ko":   5,
	"nl":   6,
	"ru":   7,
	"zhCN": 8,
	"zhTW": 9,
}

func (x Language) String() string {
	return proto.EnumName(Language_name, int32(x))
}

func (Language) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_af4633894bd93ab0, []int{0}
}

type GoogleRecaptchaRequest struct {
	Secret               string   `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Response             string   `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	Remoteip             string   `protobuf:"bytes,3,opt,name=remoteip,proto3" json:"remoteip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoogleRecaptchaRequest) Reset()         { *m = GoogleRecaptchaRequest{} }
func (m *GoogleRecaptchaRequest) String() string { return proto.CompactTextString(m) }
func (*GoogleRecaptchaRequest) ProtoMessage()    {}
func (*GoogleRecaptchaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_af4633894bd93ab0, []int{0}
}

func (m *GoogleRecaptchaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoogleRecaptchaRequest.Unmarshal(m, b)
}
func (m *GoogleRecaptchaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoogleRecaptchaRequest.Marshal(b, m, deterministic)
}
func (m *GoogleRecaptchaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoogleRecaptchaRequest.Merge(m, src)
}
func (m *GoogleRecaptchaRequest) XXX_Size() int {
	return xxx_messageInfo_GoogleRecaptchaRequest.Size(m)
}
func (m *GoogleRecaptchaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GoogleRecaptchaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GoogleRecaptchaRequest proto.InternalMessageInfo

func (m *GoogleRecaptchaRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *GoogleRecaptchaRequest) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func (m *GoogleRecaptchaRequest) GetRemoteip() string {
	if m != nil {
		return m.Remoteip
	}
	return ""
}

type GoogleRecaptchaResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ChallengeTs          string   `protobuf:"bytes,2,opt,name=challenge_ts,json=challengeTs,proto3" json:"challenge_ts,omitempty"`
	Hostname             string   `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	ErrorCodes           string   `protobuf:"bytes,4,opt,name=error_codes,json=errorCodes,proto3" json:"error_codes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoogleRecaptchaResponse) Reset()         { *m = GoogleRecaptchaResponse{} }
func (m *GoogleRecaptchaResponse) String() string { return proto.CompactTextString(m) }
func (*GoogleRecaptchaResponse) ProtoMessage()    {}
func (*GoogleRecaptchaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_af4633894bd93ab0, []int{1}
}

func (m *GoogleRecaptchaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoogleRecaptchaResponse.Unmarshal(m, b)
}
func (m *GoogleRecaptchaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoogleRecaptchaResponse.Marshal(b, m, deterministic)
}
func (m *GoogleRecaptchaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoogleRecaptchaResponse.Merge(m, src)
}
func (m *GoogleRecaptchaResponse) XXX_Size() int {
	return xxx_messageInfo_GoogleRecaptchaResponse.Size(m)
}
func (m *GoogleRecaptchaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GoogleRecaptchaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GoogleRecaptchaResponse proto.InternalMessageInfo

func (m *GoogleRecaptchaResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GoogleRecaptchaResponse) GetChallengeTs() string {
	if m != nil {
		return m.ChallengeTs
	}
	return ""
}

func (m *GoogleRecaptchaResponse) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *GoogleRecaptchaResponse) GetErrorCodes() string {
	if m != nil {
		return m.ErrorCodes
	}
	return ""
}

type ProfileSettings struct {
	// Existing users in the system can not be assigned to organizations and
	// application and can not be listed by non global admin users.
	DisableAssignExistingUsers bool     `protobuf:"varint,1,opt,name=disable_assign_existing_users,json=disableAssignExistingUsers,proto3" json:"disable_assign_existing_users,omitempty"`
	XXX_NoUnkeyedLiteral       struct{} `json:"-"`
	XXX_unrecognized           []byte   `json:"-"`
	XXX_sizecache              int32    `json:"-"`
}

func (m *ProfileSettings) Reset()         { *m = ProfileSettings{} }
func (m *ProfileSettings) String() string { return proto.CompactTextString(m) }
func (*ProfileSettings) ProtoMessage()    {}
func (*ProfileSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_af4633894bd93ab0, []int{2}
}

func (m *ProfileSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileSettings.Unmarshal(m, b)
}
func (m *ProfileSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileSettings.Marshal(b, m, deterministic)
}
func (m *ProfileSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileSettings.Merge(m, src)
}
func (m *ProfileSettings) XXX_Size() int {
	return xxx_messageInfo_ProfileSettings.Size(m)
}
func (m *ProfileSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileSettings.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileSettings proto.InternalMessageInfo

func (m *ProfileSettings) GetDisableAssignExistingUsers() bool {
	if m != nil {
		return m.DisableAssignExistingUsers
	}
	return false
}

// Defines an organization to which an user is associated.
type OrganizationLink struct {
	// Organization ID.
	OrganizationId int64 `protobuf:"varint,1,opt,name=organization_id,json=organizationID,proto3" json:"organization_id,omitempty"`
	// Organization name.
	OrganizationName string `protobuf:"bytes,2,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	// User is admin within the context of this organization.
	// There is no need to set the is_device_admin and is_gateway_admin flags.
	IsAdmin bool `protobuf:"varint,3,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	// User is able to modify device related resources (applications,
	// device-profiles, devices, multicast-groups).
	IsDeviceAdmin bool `protobuf:"varint,6,opt,name=is_device_admin,json=isDeviceAdmin,proto3" json:"is_device_admin,omitempty"`
	// User is able to modify gateways.
	IsGatewayAdmin bool `protobuf:"varint,7,opt,name=is_gateway_admin,json=isGatewayAdmin,proto3" json:"is_gateway_admin,omitempty"`
	// Created at timestamp.
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp.
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OrganizationLink) Reset()         { *m = OrganizationLink{} }
func (m *OrganizationLink) String() string { return proto.CompactTextString(m) }
func (*OrganizationLink) ProtoMessage()    {}
func (*OrganizationLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_af4633894bd93ab0, []int{3}
}

func (m *OrganizationLink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrganizationLink.Unmarshal(m, b)
}
func (m *OrganizationLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrganizationLink.Marshal(b, m, deterministic)
}
func (m *OrganizationLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrganizationLink.Merge(m, src)
}
func (m *OrganizationLink) XXX_Size() int {
	return xxx_messageInfo_OrganizationLink.Size(m)
}
func (m *OrganizationLink) XXX_DiscardUnknown() {
	xxx_messageInfo_OrganizationLink.DiscardUnknown(m)
}

var xxx_messageInfo_OrganizationLink proto.InternalMessageInfo

func (m *OrganizationLink) GetOrganizationId() int64 {
	if m != nil {
		return m.OrganizationId
	}
	return 0
}

func (m *OrganizationLink) GetOrganizationName() string {
	if m != nil {
		return m.OrganizationName
	}
	return ""
}

func (m *OrganizationLink) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

func (m *OrganizationLink) GetIsDeviceAdmin() bool {
	if m != nil {
		return m.IsDeviceAdmin
	}
	return false
}

func (m *OrganizationLink) GetIsGatewayAdmin() bool {
	if m != nil {
		return m.IsGatewayAdmin
	}
	return false
}

func (m *OrganizationLink) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *OrganizationLink) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type LoginRequest struct {
	// Username of the user.
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// Password of the user.
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_af4633894bd93ab0, []int{4}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	// The JWT tag to be used to access lora-app-server interfaces.
	Jwt                  string   `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_af4633894bd93ab0, []int{5}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

type ProfileResponse struct {
	// User object.
	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// Organizations to which the user is associated.
	Organizations []*OrganizationLink `protobuf:"bytes,3,rep,name=organizations,proto3" json:"organizations,omitempty"`
	// Profile settings.
	Settings             *ProfileSettings `protobuf:"bytes,4,opt,name=settings,proto3" json:"settings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ProfileResponse) Reset()         { *m = ProfileResponse{} }
func (m *ProfileResponse) String() string { return proto.CompactTextString(m) }
func (*ProfileResponse) ProtoMessage()    {}
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_af4633894bd93ab0, []int{6}
}

func (m *ProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileResponse.Unmarshal(m, b)
}
func (m *ProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileResponse.Marshal(b, m, deterministic)
}
func (m *ProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileResponse.Merge(m, src)
}
func (m *ProfileResponse) XXX_Size() int {
	return xxx_messageInfo_ProfileResponse.Size(m)
}
func (m *ProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileResponse proto.InternalMessageInfo

func (m *ProfileResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ProfileResponse) GetOrganizations() []*OrganizationLink {
	if m != nil {
		return m.Organizations
	}
	return nil
}

func (m *ProfileResponse) GetSettings() *ProfileSettings {
	if m != nil {
		return m.Settings
	}
	return nil
}

type GlobalSearchRequest struct {
	// Search query.
	Search string `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	// Max number of results to return.
	Limit int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Offset offset of the result-set (for pagination).
	Offset               int64    `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GlobalSearchRequest) Reset()         { *m = GlobalSearchRequest{} }
func (m *GlobalSearchRequest) String() string { return proto.CompactTextString(m) }
func (*GlobalSearchRequest) ProtoMessage()    {}
func (*GlobalSearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_af4633894bd93ab0, []int{7}
}

func (m *GlobalSearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalSearchRequest.Unmarshal(m, b)
}
func (m *GlobalSearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalSearchRequest.Marshal(b, m, deterministic)
}
func (m *GlobalSearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalSearchRequest.Merge(m, src)
}
func (m *GlobalSearchRequest) XXX_Size() int {
	return xxx_messageInfo_GlobalSearchRequest.Size(m)
}
func (m *GlobalSearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalSearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalSearchRequest proto.InternalMessageInfo

func (m *GlobalSearchRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

func (m *GlobalSearchRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GlobalSearchRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type GlobalSearchResponse struct {
	Result               []*GlobalSearchResult `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GlobalSearchResponse) Reset()         { *m = GlobalSearchResponse{} }
func (m *GlobalSearchResponse) String() string { return proto.CompactTextString(m) }
func (*GlobalSearchResponse) ProtoMessage()    {}
func (*GlobalSearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_af4633894bd93ab0, []int{8}
}

func (m *GlobalSearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalSearchResponse.Unmarshal(m, b)
}
func (m *GlobalSearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalSearchResponse.Marshal(b, m, deterministic)
}
func (m *GlobalSearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalSearchResponse.Merge(m, src)
}
func (m *GlobalSearchResponse) XXX_Size() int {
	return xxx_messageInfo_GlobalSearchResponse.Size(m)
}
func (m *GlobalSearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalSearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalSearchResponse proto.InternalMessageInfo

func (m *GlobalSearchResponse) GetResult() []*GlobalSearchResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type GlobalSearchResult struct {
	// Record kind.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Search score.
	Score float32 `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	// Organization id.
	OrganizationId int64 `protobuf:"varint,3,opt,name=organization_id,json=organizationID,proto3" json:"organization_id,omitempty"`
	// Organization name.
	OrganizationName string `protobuf:"bytes,4,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	// Application id.
	ApplicationId int64 `protobuf:"varint,5,opt,name=application_id,json=applicationID,proto3" json:"application_id,omitempty"`
	// Application name.
	ApplicationName string `protobuf:"bytes,6,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	// Device DevEUI (hex encoded).
	DeviceDevEui string `protobuf:"bytes,7,opt,name=device_dev_eui,json=deviceDevEUI,proto3" json:"device_dev_eui,omitempty"`
	// Device name.
	DeviceName string `protobuf:"bytes,8,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Gateway MAC (hex encoded).
	GatewayMac string `protobuf:"bytes,9,opt,name=gateway_mac,json=gatewayMAC,proto3" json:"gateway_mac,omitempty"`
	// Gateway name.
	GatewayName          string   `protobuf:"bytes,10,opt,name=gateway_name,json=gatewayName,proto3" json:"gateway_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GlobalSearchResult) Reset()         { *m = GlobalSearchResult{} }
func (m *GlobalSearchResult) String() string { return proto.CompactTextString(m) }
func (*GlobalSearchResult) ProtoMessage()    {}
func (*GlobalSearchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_af4633894bd93ab0, []int{9}
}

func (m *GlobalSearchResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalSearchResult.Unmarshal(m, b)
}
func (m *GlobalSearchResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalSearchResult.Marshal(b, m, deterministic)
}
func (m *GlobalSearchResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalSearchResult.Merge(m, src)
}
func (m *GlobalSearchResult) XXX_Size() int {
	return xxx_messageInfo_GlobalSearchResult.Size(m)
}
func (m *GlobalSearchResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalSearchResult.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalSearchResult proto.InternalMessageInfo

func (m *GlobalSearchResult) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *GlobalSearchResult) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *GlobalSearchResult) GetOrganizationId() int64 {
	if m != nil {
		return m.OrganizationId
	}
	return 0
}

func (m *GlobalSearchResult) GetOrganizationName() string {
	if m != nil {
		return m.OrganizationName
	}
	return ""
}

func (m *GlobalSearchResult) GetApplicationId() int64 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

func (m *GlobalSearchResult) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

func (m *GlobalSearchResult) GetDeviceDevEui() string {
	if m != nil {
		return m.DeviceDevEui
	}
	return ""
}

func (m *GlobalSearchResult) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *GlobalSearchResult) GetGatewayMac() string {
	if m != nil {
		return m.GatewayMac
	}
	return ""
}

func (m *GlobalSearchResult) GetGatewayName() string {
	if m != nil {
		return m.GatewayName
	}
	return ""
}

type BrandingResponse struct {
	// Logo html.
	Logo string `protobuf:"bytes,1,opt,name=logo,proto3" json:"logo,omitempty"`
	// Registration html.
	Registration string `protobuf:"bytes,2,opt,name=registration,proto3" json:"registration,omitempty"`
	// Footer html.
	Footer string `protobuf:"bytes,3,opt,name=footer,proto3" json:"footer,omitempty"`
	// Logo img path
	LogoPath             string   `protobuf:"bytes,4,opt,name=logo_path,json=logoPath,proto3" json:"logo_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BrandingResponse) Reset()         { *m = BrandingResponse{} }
func (m *BrandingResponse) String() string { return proto.CompactTextString(m) }
func (*BrandingResponse) ProtoMessage()    {}
func (*BrandingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_af4633894bd93ab0, []int{10}
}

func (m *BrandingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrandingResponse.Unmarshal(m, b)
}
func (m *BrandingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrandingResponse.Marshal(b, m, deterministic)
}
func (m *BrandingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrandingResponse.Merge(m, src)
}
func (m *BrandingResponse) XXX_Size() int {
	return xxx_messageInfo_BrandingResponse.Size(m)
}
func (m *BrandingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BrandingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BrandingResponse proto.InternalMessageInfo

func (m *BrandingResponse) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

func (m *BrandingResponse) GetRegistration() string {
	if m != nil {
		return m.Registration
	}
	return ""
}

func (m *BrandingResponse) GetFooter() string {
	if m != nil {
		return m.Footer
	}
	return ""
}

func (m *BrandingResponse) GetLogoPath() string {
	if m != nil {
		return m.LogoPath
	}
	return ""
}

type RegisterUserRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Language             Language `protobuf:"varint,2,opt,name=language,proto3,enum=ui.Language" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserRequest) Reset()         { *m = RegisterUserRequest{} }
func (m *RegisterUserRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterUserRequest) ProtoMessage()    {}
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_af4633894bd93ab0, []int{11}
}

func (m *RegisterUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserRequest.Unmarshal(m, b)
}
func (m *RegisterUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserRequest.Marshal(b, m, deterministic)
}
func (m *RegisterUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserRequest.Merge(m, src)
}
func (m *RegisterUserRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterUserRequest.Size(m)
}
func (m *RegisterUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserRequest proto.InternalMessageInfo

func (m *RegisterUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterUserRequest) GetLanguage() Language {
	if m != nil {
		return m.Language
	}
	return Language_de
}

type ConfirmRegistrationRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmRegistrationRequest) Reset()         { *m = ConfirmRegistrationRequest{} }
func (m *ConfirmRegistrationRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmRegistrationRequest) ProtoMessage()    {}
func (*ConfirmRegistrationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_af4633894bd93ab0, []int{12}
}

func (m *ConfirmRegistrationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmRegistrationRequest.Unmarshal(m, b)
}
func (m *ConfirmRegistrationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmRegistrationRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmRegistrationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmRegistrationRequest.Merge(m, src)
}
func (m *ConfirmRegistrationRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmRegistrationRequest.Size(m)
}
func (m *ConfirmRegistrationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmRegistrationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmRegistrationRequest proto.InternalMessageInfo

func (m *ConfirmRegistrationRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ConfirmRegistrationResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	SessionTTL           int32    `protobuf:"varint,3,opt,name=sessionTTL,proto3" json:"sessionTTL,omitempty"`
	IsAdmin              bool     `protobuf:"varint,4,opt,name=isAdmin,proto3" json:"isAdmin,omitempty"`
	IsActive             bool     `protobuf:"varint,5,opt,name=isActive,proto3" json:"isActive,omitempty"`
	Jwt                  string   `protobuf:"bytes,6,opt,name=jwt,proto3" json:"jwt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmRegistrationResponse) Reset()         { *m = ConfirmRegistrationResponse{} }
func (m *ConfirmRegistrationResponse) String() string { return proto.CompactTextString(m) }
func (*ConfirmRegistrationResponse) ProtoMessage()    {}
func (*ConfirmRegistrationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_af4633894bd93ab0, []int{13}
}

func (m *ConfirmRegistrationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmRegistrationResponse.Unmarshal(m, b)
}
func (m *ConfirmRegistrationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmRegistrationResponse.Marshal(b, m, deterministic)
}
func (m *ConfirmRegistrationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmRegistrationResponse.Merge(m, src)
}
func (m *ConfirmRegistrationResponse) XXX_Size() int {
	return xxx_messageInfo_ConfirmRegistrationResponse.Size(m)
}
func (m *ConfirmRegistrationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmRegistrationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmRegistrationResponse proto.InternalMessageInfo

func (m *ConfirmRegistrationResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ConfirmRegistrationResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ConfirmRegistrationResponse) GetSessionTTL() int32 {
	if m != nil {
		return m.SessionTTL
	}
	return 0
}

func (m *ConfirmRegistrationResponse) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

func (m *ConfirmRegistrationResponse) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *ConfirmRegistrationResponse) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

type FinishRegistrationRequest struct {
	OrganizationName        string   `protobuf:"bytes,1,opt,name=organizationName,proto3" json:"organizationName,omitempty"`
	OrganizationDisplayName string   `protobuf:"bytes,2,opt,name=organizationDisplayName,proto3" json:"organizationDisplayName,omitempty"`
	UserId                  int64    `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Password                string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *FinishRegistrationRequest) Reset()         { *m = FinishRegistrationRequest{} }
func (m *FinishRegistrationRequest) String() string { return proto.CompactTextString(m) }
func (*FinishRegistrationRequest) ProtoMessage()    {}
func (*FinishRegistrationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_af4633894bd93ab0, []int{14}
}

func (m *FinishRegistrationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinishRegistrationRequest.Unmarshal(m, b)
}
func (m *FinishRegistrationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinishRegistrationRequest.Marshal(b, m, deterministic)
}
func (m *FinishRegistrationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinishRegistrationRequest.Merge(m, src)
}
func (m *FinishRegistrationRequest) XXX_Size() int {
	return xxx_messageInfo_FinishRegistrationRequest.Size(m)
}
func (m *FinishRegistrationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FinishRegistrationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FinishRegistrationRequest proto.InternalMessageInfo

func (m *FinishRegistrationRequest) GetOrganizationName() string {
	if m != nil {
		return m.OrganizationName
	}
	return ""
}

func (m *FinishRegistrationRequest) GetOrganizationDisplayName() string {
	if m != nil {
		return m.OrganizationDisplayName
	}
	return ""
}

func (m *FinishRegistrationRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *FinishRegistrationRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type TOTPStatusResponse struct {
	// set to true if TOTP is enabled
	Enabled              bool     `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TOTPStatusResponse) Reset()         { *m = TOTPStatusResponse{} }
func (m *TOTPStatusResponse) String() string { return proto.CompactTextString(m) }
func (*TOTPStatusResponse) ProtoMessage()    {}
func (*TOTPStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_af4633894bd93ab0, []int{15}
}

func (m *TOTPStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TOTPStatusResponse.Unmarshal(m, b)
}
func (m *TOTPStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TOTPStatusResponse.Marshal(b, m, deterministic)
}
func (m *TOTPStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TOTPStatusResponse.Merge(m, src)
}
func (m *TOTPStatusResponse) XXX_Size() int {
	return xxx_messageInfo_TOTPStatusResponse.Size(m)
}
func (m *TOTPStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TOTPStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TOTPStatusResponse proto.InternalMessageInfo

func (m *TOTPStatusResponse) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type GetTOTPConfigurationRequest struct {
	// the size of QR code image
	QrCodeSize           int64    `protobuf:"varint,1,opt,name=qr_code_size,json=qrCodeSize,proto3" json:"qr_code_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTOTPConfigurationRequest) Reset()         { *m = GetTOTPConfigurationRequest{} }
func (m *GetTOTPConfigurationRequest) String() string { return proto.CompactTextString(m) }
func (*GetTOTPConfigurationRequest) ProtoMessage()    {}
func (*GetTOTPConfigurationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_af4633894bd93ab0, []int{16}
}

func (m *GetTOTPConfigurationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTOTPConfigurationRequest.Unmarshal(m, b)
}
func (m *GetTOTPConfigurationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTOTPConfigurationRequest.Marshal(b, m, deterministic)
}
func (m *GetTOTPConfigurationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTOTPConfigurationRequest.Merge(m, src)
}
func (m *GetTOTPConfigurationRequest) XXX_Size() int {
	return xxx_messageInfo_GetTOTPConfigurationRequest.Size(m)
}
func (m *GetTOTPConfigurationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTOTPConfigurationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTOTPConfigurationRequest proto.InternalMessageInfo

func (m *GetTOTPConfigurationRequest) GetQrCodeSize() int64 {
	if m != nil {
		return m.QrCodeSize
	}
	return 0
}

type GetTOTPConfigurationResponse struct {
	// otpauth:// url containing details of TOTP configuration
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// the secret encoded as a string of 32 characters
	Secret string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	// list of recovery codes
	RecoveryCode []string `protobuf:"bytes,3,rep,name=recovery_code,json=recoveryCode,proto3" json:"recovery_code,omitempty"`
	// QR code base64 encoded in PNG format
	QrCode               string   `protobuf:"bytes,4,opt,name=qr_code,json=qrCode,proto3" json:"qr_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTOTPConfigurationResponse) Reset()         { *m = GetTOTPConfigurationResponse{} }
func (m *GetTOTPConfigurationResponse) String() string { return proto.CompactTextString(m) }
func (*GetTOTPConfigurationResponse) ProtoMessage()    {}
func (*GetTOTPConfigurationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_af4633894bd93ab0, []int{17}
}

func (m *GetTOTPConfigurationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTOTPConfigurationResponse.Unmarshal(m, b)
}
func (m *GetTOTPConfigurationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTOTPConfigurationResponse.Marshal(b, m, deterministic)
}
func (m *GetTOTPConfigurationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTOTPConfigurationResponse.Merge(m, src)
}
func (m *GetTOTPConfigurationResponse) XXX_Size() int {
	return xxx_messageInfo_GetTOTPConfigurationResponse.Size(m)
}
func (m *GetTOTPConfigurationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTOTPConfigurationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTOTPConfigurationResponse proto.InternalMessageInfo

func (m *GetTOTPConfigurationResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *GetTOTPConfigurationResponse) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *GetTOTPConfigurationResponse) GetRecoveryCode() []string {
	if m != nil {
		return m.RecoveryCode
	}
	return nil
}

func (m *GetTOTPConfigurationResponse) GetQrCode() string {
	if m != nil {
		return m.QrCode
	}
	return ""
}

type TOTPStatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TOTPStatusRequest) Reset()         { *m = TOTPStatusRequest{} }
func (m *TOTPStatusRequest) String() string { return proto.CompactTextString(m) }
func (*TOTPStatusRequest) ProtoMessage()    {}
func (*TOTPStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_af4633894bd93ab0, []int{18}
}

func (m *TOTPStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TOTPStatusRequest.Unmarshal(m, b)
}
func (m *TOTPStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TOTPStatusRequest.Marshal(b, m, deterministic)
}
func (m *TOTPStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TOTPStatusRequest.Merge(m, src)
}
func (m *TOTPStatusRequest) XXX_Size() int {
	return xxx_messageInfo_TOTPStatusRequest.Size(m)
}
func (m *TOTPStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TOTPStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TOTPStatusRequest proto.InternalMessageInfo

type GetRecoveryCodesRequest struct {
	// if true, then old recovery codes will be removed and new will be
	// generated, otherwise the old codes will remain valid and will be returned
	Regenerate           bool     `protobuf:"varint,1,opt,name=regenerate,proto3" json:"regenerate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRecoveryCodesRequest) Reset()         { *m = GetRecoveryCodesRequest{} }
func (m *GetRecoveryCodesRequest) String() string { return proto.CompactTextString(m) }
func (*GetRecoveryCodesRequest) ProtoMessage()    {}
func (*GetRecoveryCodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_af4633894bd93ab0, []int{19}
}

func (m *GetRecoveryCodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecoveryCodesRequest.Unmarshal(m, b)
}
func (m *GetRecoveryCodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecoveryCodesRequest.Marshal(b, m, deterministic)
}
func (m *GetRecoveryCodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecoveryCodesRequest.Merge(m, src)
}
func (m *GetRecoveryCodesRequest) XXX_Size() int {
	return xxx_messageInfo_GetRecoveryCodesRequest.Size(m)
}
func (m *GetRecoveryCodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecoveryCodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecoveryCodesRequest proto.InternalMessageInfo

func (m *GetRecoveryCodesRequest) GetRegenerate() bool {
	if m != nil {
		return m.Regenerate
	}
	return false
}

type GetRecoveryCodesResponse struct {
	// list of recovery codes
	RecoveryCode         []string `protobuf:"bytes,1,rep,name=recovery_code,json=recoveryCode,proto3" json:"recovery_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRecoveryCodesResponse) Reset()         { *m = GetRecoveryCodesResponse{} }
func (m *GetRecoveryCodesResponse) String() string { return proto.CompactTextString(m) }
func (*GetRecoveryCodesResponse) ProtoMessage()    {}
func (*GetRecoveryCodesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_af4633894bd93ab0, []int{20}
}

func (m *GetRecoveryCodesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecoveryCodesResponse.Unmarshal(m, b)
}
func (m *GetRecoveryCodesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecoveryCodesResponse.Marshal(b, m, deterministic)
}
func (m *GetRecoveryCodesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecoveryCodesResponse.Merge(m, src)
}
func (m *GetRecoveryCodesResponse) XXX_Size() int {
	return xxx_messageInfo_GetRecoveryCodesResponse.Size(m)
}
func (m *GetRecoveryCodesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecoveryCodesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecoveryCodesResponse proto.InternalMessageInfo

func (m *GetRecoveryCodesResponse) GetRecoveryCode() []string {
	if m != nil {
		return m.RecoveryCode
	}
	return nil
}

func init() {
	proto.RegisterEnum("ui.Language", Language_name, Language_value)
	proto.RegisterType((*GoogleRecaptchaRequest)(nil), "ui.GoogleRecaptchaRequest")
	proto.RegisterType((*GoogleRecaptchaResponse)(nil), "ui.GoogleRecaptchaResponse")
	proto.RegisterType((*ProfileSettings)(nil), "ui.ProfileSettings")
	proto.RegisterType((*OrganizationLink)(nil), "ui.OrganizationLink")
	proto.RegisterType((*LoginRequest)(nil), "ui.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "ui.LoginResponse")
	proto.RegisterType((*ProfileResponse)(nil), "ui.ProfileResponse")
	proto.RegisterType((*GlobalSearchRequest)(nil), "ui.GlobalSearchRequest")
	proto.RegisterType((*GlobalSearchResponse)(nil), "ui.GlobalSearchResponse")
	proto.RegisterType((*GlobalSearchResult)(nil), "ui.GlobalSearchResult")
	proto.RegisterType((*BrandingResponse)(nil), "ui.BrandingResponse")
	proto.RegisterType((*RegisterUserRequest)(nil), "ui.RegisterUserRequest")
	proto.RegisterType((*ConfirmRegistrationRequest)(nil), "ui.ConfirmRegistrationRequest")
	proto.RegisterType((*ConfirmRegistrationResponse)(nil), "ui.ConfirmRegistrationResponse")
	proto.RegisterType((*FinishRegistrationRequest)(nil), "ui.FinishRegistrationRequest")
	proto.RegisterType((*TOTPStatusResponse)(nil), "ui.TOTPStatusResponse")
	proto.RegisterType((*GetTOTPConfigurationRequest)(nil), "ui.GetTOTPConfigurationRequest")
	proto.RegisterType((*GetTOTPConfigurationResponse)(nil), "ui.GetTOTPConfigurationResponse")
	proto.RegisterType((*TOTPStatusRequest)(nil), "ui.TOTPStatusRequest")
	proto.RegisterType((*GetRecoveryCodesRequest)(nil), "ui.GetRecoveryCodesRequest")
	proto.RegisterType((*GetRecoveryCodesResponse)(nil), "ui.GetRecoveryCodesResponse")
}

func init() {
	proto.RegisterFile("lpwan-app-server/ui/internal.proto", fileDescriptor_af4633894bd93ab0)
}

var fileDescriptor_af4633894bd93ab0 = []byte{
	// 1626 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xcd, 0x52, 0x23, 0xc9,
	0x11, 0xb6, 0x7e, 0x10, 0x22, 0x11, 0xd0, 0x53, 0xb0, 0xa0, 0x69, 0x18, 0x06, 0xda, 0x3b, 0xbb,
	0x98, 0xb5, 0x50, 0x04, 0xbe, 0x78, 0xe7, 0xb2, 0x81, 0x81, 0x21, 0x88, 0xc0, 0xb3, 0x13, 0x8d,
	0xb0, 0x1d, 0xe1, 0x08, 0x2b, 0x8a, 0x56, 0xa9, 0x55, 0x4b, 0xab, 0xbb, 0xa7, 0xaa, 0x1a, 0x0c,
	0x3e, 0x38, 0xc2, 0x0e, 0xef, 0x0b, 0xcc, 0xd5, 0x2f, 0xe1, 0x83, 0x9f, 0xc2, 0x47, 0xbf, 0x82,
	0x5f, 0xc0, 0x6f, 0xe0, 0xa8, 0xac, 0x6a, 0x4d, 0xeb, 0x6f, 0x6c, 0xef, 0x45, 0xdd, 0x99, 0x95,
	0x95, 0x5f, 0x66, 0x56, 0xd6, 0x97, 0x2d, 0xf0, 0xa2, 0xf4, 0x81, 0xc6, 0x2d, 0x9a, 0xa6, 0x2d,
	0xc9, 0xc4, 0x3d, 0x13, 0xed, 0x8c, 0xb7, 0x79, 0xac, 0x98, 0x88, 0x69, 0x74, 0x94, 0x8a, 0x44,
	0x25, 0xa4, 0x9c, 0x71, 0x77, 0x27, 0x4c, 0x92, 0x30, 0x62, 0x6d, 0x9a, 0xf2, 0x36, 0x8d, 0xe3,
	0x44, 0x51, 0xc5, 0x93, 0x58, 0x1a, 0x0b, 0xf7, 0xb9, 0xe2, 0x43, 0x26, 0x15, 0x1d, 0xa6, 0xed,
	0xd1, 0x9b, 0x5d, 0x7a, 0xc6, 0x86, 0xa9, 0x7a, 0x6c, 0xe3, 0xaf, 0x55, 0xed, 0xce, 0xc2, 0xcc,
	0x24, 0x13, 0x66, 0xdd, 0x1b, 0xc0, 0xe6, 0x05, 0xa2, 0xf9, 0x2c, 0xa0, 0xa9, 0x0a, 0x06, 0xd4,
	0x67, 0xef, 0x33, 0x26, 0x15, 0xd9, 0x84, 0x9a, 0x64, 0x81, 0x60, 0xaa, 0x59, 0xda, 0x2b, 0x1d,
	0x2c, 0xf9, 0x56, 0x22, 0x2e, 0xd4, 0x05, 0x93, 0x69, 0x12, 0x4b, 0xd6, 0x2c, 0xe3, 0xca, 0x48,
	0x36, 0x6b, 0xc3, 0x44, 0x31, 0x9e, 0x36, 0x2b, 0xf9, 0x9a, 0x91, 0xbd, 0x0f, 0x25, 0xd8, 0x9a,
	0x82, 0xb2, 0xfb, 0x9a, 0xb0, 0x28, 0xb3, 0x20, 0x60, 0x52, 0x22, 0x58, 0xdd, 0xcf, 0x45, 0xb2,
	0x0f, 0x8d, 0x60, 0x40, 0xa3, 0x88, 0xc5, 0x21, 0xeb, 0x2a, 0x69, 0x11, 0x97, 0x47, 0xba, 0x8e,
	0xd4, 0xa0, 0x83, 0x44, 0xaa, 0x98, 0x0e, 0x59, 0x0e, 0x9a, 0xcb, 0xe4, 0x25, 0x2c, 0x33, 0x21,
	0x12, 0xd1, 0x0d, 0x92, 0x1e, 0x93, 0xcd, 0x2a, 0x2e, 0x03, 0xaa, 0x4e, 0xb5, 0xc6, 0xeb, 0xc0,
	0xda, 0x3b, 0x91, 0xf4, 0x79, 0xc4, 0xae, 0x99, 0x52, 0x3c, 0x0e, 0x25, 0x39, 0x81, 0x17, 0x3d,
	0x2e, 0xe9, 0x6d, 0xc4, 0xba, 0x54, 0x4a, 0x1e, 0xc6, 0x5d, 0xf6, 0x7b, 0x2e, 0xf5, 0x5a, 0x57,
	0x17, 0x2e, 0x0f, 0xd1, 0xb5, 0x46, 0x27, 0x68, 0x73, 0x6e, 0x4d, 0x6e, 0xb4, 0x85, 0xf7, 0x8f,
	0x32, 0x38, 0xdf, 0x8a, 0x90, 0xc6, 0xfc, 0x09, 0xcf, 0xee, 0x8a, 0xc7, 0x77, 0xe4, 0x4b, 0x58,
	0x4b, 0x0a, 0xba, 0x2e, 0xef, 0xa1, 0xa7, 0x8a, 0xbf, 0x5a, 0x54, 0x5f, 0x9e, 0x91, 0xaf, 0xe0,
	0xd9, 0x98, 0x21, 0x66, 0x66, 0x12, 0x77, 0x8a, 0x0b, 0x6f, 0x75, 0x86, 0xcf, 0xa1, 0xce, 0x65,
	0x97, 0xf6, 0x86, 0x3c, 0xc6, 0xec, 0xeb, 0xfe, 0x22, 0x97, 0x27, 0x5a, 0x24, 0x5f, 0xc0, 0x1a,
	0x97, 0xdd, 0x1e, 0xbb, 0xe7, 0x01, 0xb3, 0x16, 0x35, 0xb4, 0x58, 0xe1, 0xf2, 0x0c, 0xb5, 0xc6,
	0xee, 0x00, 0x1c, 0x2e, 0xbb, 0x21, 0x55, 0xec, 0x81, 0x3e, 0x5a, 0xc3, 0x45, 0x34, 0x5c, 0xe5,
	0xf2, 0xc2, 0xa8, 0x8d, 0xe5, 0xd7, 0x00, 0x81, 0x60, 0x54, 0xb1, 0x5e, 0x97, 0x2a, 0xac, 0xe6,
	0xf2, 0xb1, 0x7b, 0x64, 0xda, 0xd5, 0x34, 0xd4, 0x6d, 0xd6, 0x3f, 0xea, 0xe4, 0x6d, 0xe9, 0x2f,
	0x59, 0xeb, 0x13, 0xa5, 0xb7, 0x66, 0x69, 0x2f, 0xdf, 0xba, 0xf0, 0xdf, 0xb7, 0x5a, 0xeb, 0x13,
	0xe5, 0xbd, 0x81, 0xc6, 0x55, 0x12, 0xf2, 0x38, 0xef, 0x4c, 0x17, 0xea, 0xfa, 0x20, 0xb0, 0x2c,
	0xa6, 0x37, 0x47, 0xb2, 0x5e, 0x4b, 0xa9, 0x94, 0x0f, 0x89, 0xe8, 0xe5, 0xdd, 0x99, 0xcb, 0xde,
	0x3e, 0xac, 0x58, 0x3f, 0xb6, 0xed, 0x1c, 0xa8, 0x7c, 0xf7, 0x90, 0xf7, 0xb7, 0x7e, 0xf5, 0xfe,
	0x5a, 0x1a, 0xf5, 0xc3, 0xc8, 0x6a, 0x07, 0xaa, 0xda, 0x3d, 0x9a, 0x2d, 0x1f, 0xd7, 0x8f, 0x32,
	0x7e, 0xa4, 0x4f, 0xd9, 0x47, 0x2d, 0x79, 0x0d, 0x2b, 0xc5, 0x33, 0x91, 0xcd, 0xca, 0x5e, 0xe5,
	0x60, 0xf9, 0x78, 0x43, 0x9b, 0x4d, 0xb6, 0x80, 0x3f, 0x6e, 0x4a, 0xda, 0x50, 0x97, 0xb6, 0xeb,
	0x6c, 0x31, 0xd7, 0xf5, 0xb6, 0x89, 0x86, 0xf4, 0x47, 0x46, 0xde, 0x6f, 0x61, 0xfd, 0x22, 0x4a,
	0x6e, 0x69, 0x74, 0xcd, 0xa8, 0x08, 0x06, 0x63, 0x57, 0x55, 0x2b, 0x3e, 0x5e, 0x55, 0x2d, 0x91,
	0x0d, 0x58, 0x88, 0xf8, 0x90, 0x2b, 0xac, 0x44, 0xc5, 0x37, 0x82, 0xb6, 0x4e, 0xfa, 0x7d, 0xc9,
	0x14, 0xf6, 0x4b, 0xc5, 0xb7, 0x92, 0xf7, 0x06, 0x36, 0xc6, 0x9d, 0xdb, 0xfc, 0x8f, 0xa0, 0x26,
	0x98, 0xcc, 0x22, 0x5d, 0x28, 0x9d, 0xda, 0xa6, 0x8e, 0x71, 0xc2, 0x32, 0x8b, 0x94, 0x6f, 0xad,
	0xbc, 0x7f, 0x97, 0x81, 0x4c, 0x2f, 0x13, 0x02, 0xd5, 0x3b, 0x1e, 0xf7, 0x6c, 0x88, 0xf8, 0xae,
	0x03, 0x94, 0x41, 0x22, 0x4c, 0x77, 0x97, 0x7d, 0x23, 0xcc, 0xba, 0x28, 0x95, 0xff, 0xfd, 0xa2,
	0x54, 0xe7, 0x5c, 0x94, 0x57, 0xb0, 0x4a, 0xd3, 0x34, 0xe2, 0xc1, 0xc8, 0xe9, 0x02, 0x3a, 0x5d,
	0x29, 0x68, 0x2f, 0xcf, 0xc8, 0x4f, 0xc0, 0x29, 0x9a, 0xa1, 0xcb, 0x1a, 0xba, 0x5c, 0x2b, 0xe8,
	0xd1, 0xe3, 0xe7, 0xb0, 0x6a, 0x2f, 0x57, 0x8f, 0xdd, 0x77, 0x59, 0xc6, 0xf1, 0xd6, 0x2c, 0xf9,
	0x0d, 0xa3, 0x3d, 0x63, 0xf7, 0xe7, 0x37, 0x97, 0x9a, 0x82, 0xac, 0x15, 0xfa, 0xaa, 0x1b, 0x0a,
	0x32, 0xaa, 0xb7, 0x96, 0xa3, 0xf2, 0xbb, 0x37, 0xa4, 0x41, 0x73, 0xc9, 0x18, 0x58, 0xd5, 0x2f,
	0x4f, 0x4e, 0x35, 0x07, 0xe6, 0x06, 0xe8, 0x02, 0x0c, 0x07, 0x5a, 0x9d, 0xf6, 0xe1, 0xfd, 0x11,
	0x9c, 0x5f, 0x08, 0x1a, 0xf7, 0x78, 0x1c, 0x8e, 0xce, 0x8d, 0x40, 0x35, 0x4a, 0xc2, 0x24, 0x2f,
	0xb8, 0x7e, 0x27, 0x1e, 0x34, 0x04, 0x0b, 0xb9, 0x54, 0x02, 0xd3, 0xb0, 0x57, 0x64, 0x4c, 0xa7,
	0xfb, 0xa3, 0x9f, 0x24, 0x8a, 0x09, 0xcb, 0xa6, 0x56, 0x22, 0xdb, 0xb0, 0xa4, 0x7d, 0x74, 0x53,
	0xaa, 0x06, 0xb6, 0xca, 0x75, 0xad, 0x78, 0x47, 0xd5, 0xc0, 0xbb, 0x81, 0x75, 0x1f, 0x9d, 0x30,
	0x81, 0x97, 0xc3, 0x76, 0xe6, 0x06, 0x2c, 0xb0, 0x21, 0xe5, 0x91, 0x0d, 0xc2, 0x08, 0xe4, 0x00,
	0xea, 0x11, 0x8d, 0xc3, 0x8c, 0x86, 0xe6, 0xe4, 0x57, 0x8f, 0x1b, 0xba, 0xa7, 0xae, 0xac, 0xce,
	0x1f, 0xad, 0x7a, 0xc7, 0xe0, 0x9e, 0x26, 0x71, 0x9f, 0x8b, 0xa1, 0x5f, 0x08, 0xb1, 0xe0, 0x5d,
	0x25, 0x77, 0x2c, 0xce, 0xbd, 0xa3, 0xe0, 0xfd, 0xad, 0x04, 0xdb, 0x33, 0x37, 0xd9, 0xba, 0xac,
	0x42, 0x79, 0x44, 0xbd, 0x65, 0xde, 0x1b, 0xa3, 0x93, 0xf2, 0x04, 0x9d, 0xec, 0x02, 0x48, 0x26,
	0x25, 0x4f, 0xe2, 0x4e, 0xe7, 0x0a, 0xeb, 0xb1, 0xe0, 0x17, 0x34, 0x7a, 0x70, 0x59, 0xb6, 0xc5,
	0x8a, 0x14, 0xc8, 0xd7, 0xd5, 0xbc, 0x7c, 0x12, 0x28, 0x7e, 0xcf, 0xb0, 0xd1, 0xea, 0xfe, 0x48,
	0xce, 0x79, 0xa7, 0xf6, 0x91, 0x77, 0xfe, 0x5e, 0x82, 0xe7, 0x6f, 0x78, 0xcc, 0xe5, 0x60, 0x56,
	0x9e, 0x87, 0x30, 0xd5, 0xce, 0x36, 0xe5, 0xe9, 0x36, 0xff, 0x39, 0x6c, 0x15, 0x75, 0x67, 0x5c,
	0xa6, 0x91, 0x69, 0x12, 0x9b, 0xdc, 0xbc, 0x65, 0x7d, 0xee, 0x3a, 0xef, 0xcb, 0xfc, 0xb6, 0x59,
	0x69, 0x8c, 0x52, 0xab, 0x13, 0x94, 0x7a, 0x04, 0xa4, 0xf3, 0x6d, 0xe7, 0xdd, 0xb5, 0xa2, 0x2a,
	0x93, 0xc5, 0x71, 0xce, 0x62, 0x3d, 0x1b, 0x7b, 0xf9, 0x38, 0xb7, 0xa2, 0xf7, 0x0d, 0x6c, 0x5f,
	0x30, 0xa5, 0xb7, 0xe0, 0x09, 0x85, 0xd9, 0x78, 0xa2, 0x7b, 0xd0, 0x78, 0x6f, 0x66, 0x75, 0x57,
	0xf2, 0x27, 0x66, 0x0f, 0x09, 0xde, 0xe3, 0xb0, 0xbe, 0xe6, 0x4f, 0xcc, 0xfb, 0xbe, 0x04, 0x3b,
	0xb3, 0x3d, 0x7c, 0xe4, 0xf4, 0x4c, 0xe4, 0xfd, 0xa6, 0x5f, 0x0b, 0x1f, 0x32, 0xe5, 0xb1, 0x0f,
	0x99, 0x1f, 0xc3, 0x8a, 0x60, 0x41, 0x72, 0xcf, 0xc4, 0x23, 0x42, 0x22, 0x73, 0xe3, 0x65, 0x30,
	0x4a, 0x8d, 0x49, 0xb6, 0x60, 0xd1, 0x46, 0x64, 0x73, 0xaf, 0x99, 0x60, 0xbc, 0x75, 0x78, 0x56,
	0xcc, 0x1c, 0xe3, 0xf7, 0xbe, 0x86, 0xad, 0x0b, 0xa6, 0xfc, 0x82, 0x83, 0x7c, 0x49, 0x77, 0x92,
	0x60, 0x21, 0x8b, 0x99, 0xa0, 0x8a, 0xd9, 0xb2, 0x14, 0x34, 0xde, 0x37, 0xd0, 0x9c, 0xde, 0x6a,
	0x73, 0x9a, 0x8a, 0xb4, 0x34, 0x1d, 0xe9, 0xe1, 0xef, 0xa0, 0x9e, 0x5f, 0x20, 0x52, 0x83, 0x72,
	0x8f, 0x39, 0x3f, 0xd2, 0x4f, 0x16, 0x3b, 0x25, 0x7c, 0x4a, 0xa7, 0xac, 0x9f, 0x7d, 0xe1, 0x54,
	0xf4, 0xf3, 0x3b, 0xea, 0x54, 0xf5, 0xf3, 0x2e, 0x71, 0x16, 0xf4, 0x33, 0x8e, 0x9c, 0x9a, 0x7e,
	0x8a, 0xcc, 0x59, 0x24, 0x75, 0xa8, 0x3e, 0x0d, 0x4e, 0xdf, 0x3a, 0x75, 0xf3, 0xd6, 0xf9, 0xb5,
	0xb3, 0x74, 0xfc, 0x61, 0x19, 0xd6, 0x2e, 0xed, 0xc7, 0xea, 0x35, 0x13, 0x9a, 0xbe, 0xc8, 0x15,
	0x2c, 0xe0, 0x44, 0x25, 0x0e, 0xde, 0xdf, 0xc2, 0x90, 0x76, 0x9f, 0x15, 0x34, 0x26, 0x0d, 0x6f,
	0xf7, 0x4f, 0xff, 0xfc, 0xd7, 0x87, 0x72, 0xd3, 0x5b, 0xc7, 0x2f, 0xdb, 0xfc, 0xc3, 0xb7, 0x1d,
	0x69, 0xa3, 0xd7, 0xa5, 0x43, 0x72, 0x03, 0x8b, 0x76, 0xf4, 0x91, 0xcd, 0xa9, 0x2f, 0x83, 0x73,
	0xfd, 0x51, 0xeb, 0x16, 0xe7, 0xe3, 0xc8, 0xef, 0x0b, 0xf4, 0xbb, 0x45, 0x3e, 0x1b, 0xf7, 0x9b,
	0x5a, 0x5f, 0xbf, 0x81, 0x7a, 0xce, 0x8d, 0x73, 0xfd, 0xe2, 0xb8, 0x9e, 0x64, 0xd0, 0x3c, 0x60,
	0xb2, 0x39, 0xee, 0xf8, 0x36, 0xf7, 0xd6, 0x85, 0x46, 0x71, 0xd0, 0x91, 0xad, 0xe9, 0xc9, 0x68,
	0x8a, 0xd1, 0x9c, 0x31, 0x32, 0x0d, 0xc4, 0x0e, 0x42, 0x6c, 0x92, 0x8d, 0x71, 0x08, 0x3b, 0xc0,
	0xfb, 0xd0, 0x28, 0xb2, 0xaa, 0x01, 0x98, 0xc1, 0xb3, 0xee, 0x9c, 0xbc, 0xbc, 0x57, 0xe8, 0xfe,
	0xa5, 0xe7, 0x8e, 0xbb, 0x2f, 0xf2, 0xbd, 0xae, 0xfc, 0x5f, 0x4a, 0xb0, 0x3e, 0x83, 0x32, 0xc9,
	0xae, 0xc6, 0x9b, 0x4f, 0xc0, 0xee, 0xcb, 0xb9, 0xeb, 0x36, 0xbd, 0x16, 0xe2, 0x7f, 0xe9, 0x79,
	0xf3, 0xf1, 0x5b, 0x81, 0xd9, 0xaf, 0xe3, 0x78, 0x04, 0x32, 0xcd, 0x82, 0xe4, 0x85, 0x46, 0x99,
	0xcb, 0x8e, 0x73, 0x73, 0xff, 0x29, 0x62, 0x7f, 0xe1, 0xed, 0x7f, 0x02, 0xbb, 0x8f, 0x5e, 0x35,
	0xf4, 0x9f, 0x4b, 0x48, 0x4d, 0xbf, 0x62, 0x82, 0xf7, 0x1f, 0x79, 0x1c, 0x4e, 0xfc, 0x55, 0x21,
	0x2e, 0x1e, 0xe1, 0xcc, 0xbf, 0x4a, 0xee, 0xf6, 0xcc, 0x35, 0x5b, 0x82, 0xaf, 0x30, 0x8c, 0x57,
	0xde, 0xde, 0x78, 0x18, 0xf7, 0x08, 0xd4, 0x0a, 0x5b, 0x22, 0xdf, 0xa1, 0xa3, 0xa0, 0xb0, 0x62,
	0xd9, 0xcd, 0x10, 0x0b, 0xf9, 0x4c, 0xbb, 0x9e, 0x22, 0x1a, 0x77, 0x73, 0x52, 0x6d, 0xc1, 0xf6,
	0x11, 0x6c, 0x9b, 0x3c, 0x1f, 0x07, 0x53, 0x89, 0x4a, 0x5b, 0xd2, 0x78, 0xfc, 0xbe, 0x04, 0x1b,
	0xb3, 0x18, 0x94, 0xe0, 0x61, 0x7e, 0x82, 0x9d, 0xdd, 0xbd, 0xf9, 0x06, 0x9f, 0xce, 0x15, 0xe1,
	0x83, 0xe2, 0x0e, 0x93, 0x2b, 0x9c, 0xe3, 0x58, 0xd0, 0xfe, 0xfe, 0xdf, 0x44, 0x3f, 0x47, 0xa4,
	0x5d, 0x6f, 0x56, 0xa2, 0x66, 0xd8, 0x68, 0x88, 0x00, 0x96, 0xcf, 0xcc, 0xbf, 0xb4, 0x1f, 0x82,
	0x31, 0xe7, 0xf2, 0x20, 0x86, 0xfd, 0xf3, 0xa7, 0x41, 0xfe, 0x00, 0xce, 0x24, 0x73, 0x93, 0x6d,
	0x5b, 0xaa, 0x59, 0xa3, 0xc0, 0xdd, 0x99, 0xbd, 0x68, 0x51, 0xe7, 0xb4, 0x2d, 0xa2, 0xe6, 0x84,
	0xdf, 0xc2, 0xbf, 0xb3, 0xaf, 0x4b, 0x87, 0xb7, 0x35, 0x6c, 0xfa, 0x9f, 0xfd, 0x27, 0x00, 0x00,
	0xff, 0xff, 0xd0, 0xb5, 0xbf, 0x57, 0x5c, 0x10, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InternalServiceClient is the client API for InternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InternalServiceClient interface {
	// Log in a user
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// Get the current user's profile
	Profile(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ProfileResponse, error)
	// Get the branding for the UI
	Branding(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*BrandingResponse, error)
	// Perform a global search.
	GlobalSearch(ctx context.Context, in *GlobalSearchRequest, opts ...grpc.CallOption) (*GlobalSearchResponse, error)
	RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ConfirmRegistration(ctx context.Context, in *ConfirmRegistrationRequest, opts ...grpc.CallOption) (*ConfirmRegistrationResponse, error)
	FinishRegistration(ctx context.Context, in *FinishRegistrationRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetVerifyingGoogleRecaptcha(ctx context.Context, in *GoogleRecaptchaRequest, opts ...grpc.CallOption) (*GoogleRecaptchaResponse, error)
	GetTOTPStatus(ctx context.Context, in *TOTPStatusRequest, opts ...grpc.CallOption) (*TOTPStatusResponse, error)
	GetTOTPConfiguration(ctx context.Context, in *GetTOTPConfigurationRequest, opts ...grpc.CallOption) (*GetTOTPConfigurationResponse, error)
	EnableTOTP(ctx context.Context, in *TOTPStatusRequest, opts ...grpc.CallOption) (*TOTPStatusResponse, error)
	DisableTOTP(ctx context.Context, in *TOTPStatusRequest, opts ...grpc.CallOption) (*TOTPStatusResponse, error)
	GetRecoveryCodes(ctx context.Context, in *GetRecoveryCodesRequest, opts ...grpc.CallOption) (*GetRecoveryCodesResponse, error)
}

type internalServiceClient struct {
	cc *grpc.ClientConn
}

func NewInternalServiceClient(cc *grpc.ClientConn) InternalServiceClient {
	return &internalServiceClient{cc}
}

func (c *internalServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/ui.InternalService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) Profile(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ProfileResponse, error) {
	out := new(ProfileResponse)
	err := c.cc.Invoke(ctx, "/ui.InternalService/Profile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) Branding(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*BrandingResponse, error) {
	out := new(BrandingResponse)
	err := c.cc.Invoke(ctx, "/ui.InternalService/Branding", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) GlobalSearch(ctx context.Context, in *GlobalSearchRequest, opts ...grpc.CallOption) (*GlobalSearchResponse, error) {
	out := new(GlobalSearchResponse)
	err := c.cc.Invoke(ctx, "/ui.InternalService/GlobalSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/ui.InternalService/RegisterUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) ConfirmRegistration(ctx context.Context, in *ConfirmRegistrationRequest, opts ...grpc.CallOption) (*ConfirmRegistrationResponse, error) {
	out := new(ConfirmRegistrationResponse)
	err := c.cc.Invoke(ctx, "/ui.InternalService/ConfirmRegistration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) FinishRegistration(ctx context.Context, in *FinishRegistrationRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/ui.InternalService/FinishRegistration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) GetVerifyingGoogleRecaptcha(ctx context.Context, in *GoogleRecaptchaRequest, opts ...grpc.CallOption) (*GoogleRecaptchaResponse, error) {
	out := new(GoogleRecaptchaResponse)
	err := c.cc.Invoke(ctx, "/ui.InternalService/GetVerifyingGoogleRecaptcha", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) GetTOTPStatus(ctx context.Context, in *TOTPStatusRequest, opts ...grpc.CallOption) (*TOTPStatusResponse, error) {
	out := new(TOTPStatusResponse)
	err := c.cc.Invoke(ctx, "/ui.InternalService/GetTOTPStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) GetTOTPConfiguration(ctx context.Context, in *GetTOTPConfigurationRequest, opts ...grpc.CallOption) (*GetTOTPConfigurationResponse, error) {
	out := new(GetTOTPConfigurationResponse)
	err := c.cc.Invoke(ctx, "/ui.InternalService/GetTOTPConfiguration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) EnableTOTP(ctx context.Context, in *TOTPStatusRequest, opts ...grpc.CallOption) (*TOTPStatusResponse, error) {
	out := new(TOTPStatusResponse)
	err := c.cc.Invoke(ctx, "/ui.InternalService/EnableTOTP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) DisableTOTP(ctx context.Context, in *TOTPStatusRequest, opts ...grpc.CallOption) (*TOTPStatusResponse, error) {
	out := new(TOTPStatusResponse)
	err := c.cc.Invoke(ctx, "/ui.InternalService/DisableTOTP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) GetRecoveryCodes(ctx context.Context, in *GetRecoveryCodesRequest, opts ...grpc.CallOption) (*GetRecoveryCodesResponse, error) {
	out := new(GetRecoveryCodesResponse)
	err := c.cc.Invoke(ctx, "/ui.InternalService/GetRecoveryCodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalServiceServer is the server API for InternalService service.
type InternalServiceServer interface {
	// Log in a user
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// Get the current user's profile
	Profile(context.Context, *empty.Empty) (*ProfileResponse, error)
	// Get the branding for the UI
	Branding(context.Context, *empty.Empty) (*BrandingResponse, error)
	// Perform a global search.
	GlobalSearch(context.Context, *GlobalSearchRequest) (*GlobalSearchResponse, error)
	RegisterUser(context.Context, *RegisterUserRequest) (*empty.Empty, error)
	ConfirmRegistration(context.Context, *ConfirmRegistrationRequest) (*ConfirmRegistrationResponse, error)
	FinishRegistration(context.Context, *FinishRegistrationRequest) (*empty.Empty, error)
	GetVerifyingGoogleRecaptcha(context.Context, *GoogleRecaptchaRequest) (*GoogleRecaptchaResponse, error)
	GetTOTPStatus(context.Context, *TOTPStatusRequest) (*TOTPStatusResponse, error)
	GetTOTPConfiguration(context.Context, *GetTOTPConfigurationRequest) (*GetTOTPConfigurationResponse, error)
	EnableTOTP(context.Context, *TOTPStatusRequest) (*TOTPStatusResponse, error)
	DisableTOTP(context.Context, *TOTPStatusRequest) (*TOTPStatusResponse, error)
	GetRecoveryCodes(context.Context, *GetRecoveryCodesRequest) (*GetRecoveryCodesResponse, error)
}

// UnimplementedInternalServiceServer can be embedded to have forward compatible implementations.
type UnimplementedInternalServiceServer struct {
}

func (*UnimplementedInternalServiceServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedInternalServiceServer) Profile(ctx context.Context, req *empty.Empty) (*ProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Profile not implemented")
}
func (*UnimplementedInternalServiceServer) Branding(ctx context.Context, req *empty.Empty) (*BrandingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Branding not implemented")
}
func (*UnimplementedInternalServiceServer) GlobalSearch(ctx context.Context, req *GlobalSearchRequest) (*GlobalSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GlobalSearch not implemented")
}
func (*UnimplementedInternalServiceServer) RegisterUser(ctx context.Context, req *RegisterUserRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUser not implemented")
}
func (*UnimplementedInternalServiceServer) ConfirmRegistration(ctx context.Context, req *ConfirmRegistrationRequest) (*ConfirmRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmRegistration not implemented")
}
func (*UnimplementedInternalServiceServer) FinishRegistration(ctx context.Context, req *FinishRegistrationRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinishRegistration not implemented")
}
func (*UnimplementedInternalServiceServer) GetVerifyingGoogleRecaptcha(ctx context.Context, req *GoogleRecaptchaRequest) (*GoogleRecaptchaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVerifyingGoogleRecaptcha not implemented")
}
func (*UnimplementedInternalServiceServer) GetTOTPStatus(ctx context.Context, req *TOTPStatusRequest) (*TOTPStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTOTPStatus not implemented")
}
func (*UnimplementedInternalServiceServer) GetTOTPConfiguration(ctx context.Context, req *GetTOTPConfigurationRequest) (*GetTOTPConfigurationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTOTPConfiguration not implemented")
}
func (*UnimplementedInternalServiceServer) EnableTOTP(ctx context.Context, req *TOTPStatusRequest) (*TOTPStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableTOTP not implemented")
}
func (*UnimplementedInternalServiceServer) DisableTOTP(ctx context.Context, req *TOTPStatusRequest) (*TOTPStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableTOTP not implemented")
}
func (*UnimplementedInternalServiceServer) GetRecoveryCodes(ctx context.Context, req *GetRecoveryCodesRequest) (*GetRecoveryCodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecoveryCodes not implemented")
}

func RegisterInternalServiceServer(s *grpc.Server, srv InternalServiceServer) {
	s.RegisterService(&_InternalService_serviceDesc, srv)
}

func _InternalService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ui.InternalService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_Profile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).Profile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ui.InternalService/Profile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).Profile(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_Branding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).Branding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ui.InternalService/Branding",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).Branding(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_GlobalSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GlobalSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).GlobalSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ui.InternalService/GlobalSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).GlobalSearch(ctx, req.(*GlobalSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ui.InternalService/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).RegisterUser(ctx, req.(*RegisterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_ConfirmRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).ConfirmRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ui.InternalService/ConfirmRegistration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).ConfirmRegistration(ctx, req.(*ConfirmRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_FinishRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).FinishRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ui.InternalService/FinishRegistration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).FinishRegistration(ctx, req.(*FinishRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_GetVerifyingGoogleRecaptcha_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoogleRecaptchaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).GetVerifyingGoogleRecaptcha(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ui.InternalService/GetVerifyingGoogleRecaptcha",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).GetVerifyingGoogleRecaptcha(ctx, req.(*GoogleRecaptchaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_GetTOTPStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TOTPStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).GetTOTPStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ui.InternalService/GetTOTPStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).GetTOTPStatus(ctx, req.(*TOTPStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_GetTOTPConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTOTPConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).GetTOTPConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ui.InternalService/GetTOTPConfiguration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).GetTOTPConfiguration(ctx, req.(*GetTOTPConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_EnableTOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TOTPStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).EnableTOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ui.InternalService/EnableTOTP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).EnableTOTP(ctx, req.(*TOTPStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_DisableTOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TOTPStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).DisableTOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ui.InternalService/DisableTOTP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).DisableTOTP(ctx, req.(*TOTPStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_GetRecoveryCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecoveryCodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).GetRecoveryCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ui.InternalService/GetRecoveryCodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).GetRecoveryCodes(ctx, req.(*GetRecoveryCodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _InternalService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ui.InternalService",
	HandlerType: (*InternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _InternalService_Login_Handler,
		},
		{
			MethodName: "Profile",
			Handler:    _InternalService_Profile_Handler,
		},
		{
			MethodName: "Branding",
			Handler:    _InternalService_Branding_Handler,
		},
		{
			MethodName: "GlobalSearch",
			Handler:    _InternalService_GlobalSearch_Handler,
		},
		{
			MethodName: "RegisterUser",
			Handler:    _InternalService_RegisterUser_Handler,
		},
		{
			MethodName: "ConfirmRegistration",
			Handler:    _InternalService_ConfirmRegistration_Handler,
		},
		{
			MethodName: "FinishRegistration",
			Handler:    _InternalService_FinishRegistration_Handler,
		},
		{
			MethodName: "GetVerifyingGoogleRecaptcha",
			Handler:    _InternalService_GetVerifyingGoogleRecaptcha_Handler,
		},
		{
			MethodName: "GetTOTPStatus",
			Handler:    _InternalService_GetTOTPStatus_Handler,
		},
		{
			MethodName: "GetTOTPConfiguration",
			Handler:    _InternalService_GetTOTPConfiguration_Handler,
		},
		{
			MethodName: "EnableTOTP",
			Handler:    _InternalService_EnableTOTP_Handler,
		},
		{
			MethodName: "DisableTOTP",
			Handler:    _InternalService_DisableTOTP_Handler,
		},
		{
			MethodName: "GetRecoveryCodes",
			Handler:    _InternalService_GetRecoveryCodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lpwan-app-server/ui/internal.proto",
}
