// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lpwan-app-server/ui/settings.proto

package ui

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetSettingsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSettingsRequest) Reset()         { *m = GetSettingsRequest{} }
func (m *GetSettingsRequest) String() string { return proto.CompactTextString(m) }
func (*GetSettingsRequest) ProtoMessage()    {}
func (*GetSettingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_89f82689bef70059, []int{0}
}

func (m *GetSettingsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSettingsRequest.Unmarshal(m, b)
}
func (m *GetSettingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSettingsRequest.Marshal(b, m, deterministic)
}
func (m *GetSettingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSettingsRequest.Merge(m, src)
}
func (m *GetSettingsRequest) XXX_Size() int {
	return xxx_messageInfo_GetSettingsRequest.Size(m)
}
func (m *GetSettingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSettingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSettingsRequest proto.InternalMessageInfo

type GetSettingsResponse struct {
	// when supernode income is lower than expected revenue, warn system owner to increase income
	LowBalanceWarning    string  `protobuf:"bytes,1,opt,name=low_balance_warning,json=lowBalanceWarning,proto3" json:"low_balance_warning,omitempty"`
	DownlinkPrice        float64 `protobuf:"fixed64,2,opt,name=downlink_price,json=downlinkPrice,proto3" json:"downlink_price,omitempty"`
	SupernodeIncomeRatio float64 `protobuf:"fixed64,3,opt,name=supernode_income_ratio,json=supernodeIncomeRatio,proto3" json:"supernode_income_ratio,omitempty"`
	// this is the percentage of reward from supernode income
	StakingPercentage float64 `protobuf:"fixed64,4,opt,name=staking_percentage,json=stakingPercentage,proto3" json:"staking_percentage,omitempty"`
	// this is the percentage of expected reward from staking amount
	StakingExpectedRevenuePercentage float64  `protobuf:"fixed64,5,opt,name=staking_expected_revenue_percentage,json=stakingExpectedRevenuePercentage,proto3" json:"staking_expected_revenue_percentage,omitempty"`
	Compensation                     float64  `protobuf:"fixed64,6,opt,name=compensation,proto3" json:"compensation,omitempty"`
	XXX_NoUnkeyedLiteral             struct{} `json:"-"`
	XXX_unrecognized                 []byte   `json:"-"`
	XXX_sizecache                    int32    `json:"-"`
}

func (m *GetSettingsResponse) Reset()         { *m = GetSettingsResponse{} }
func (m *GetSettingsResponse) String() string { return proto.CompactTextString(m) }
func (*GetSettingsResponse) ProtoMessage()    {}
func (*GetSettingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_89f82689bef70059, []int{1}
}

func (m *GetSettingsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSettingsResponse.Unmarshal(m, b)
}
func (m *GetSettingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSettingsResponse.Marshal(b, m, deterministic)
}
func (m *GetSettingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSettingsResponse.Merge(m, src)
}
func (m *GetSettingsResponse) XXX_Size() int {
	return xxx_messageInfo_GetSettingsResponse.Size(m)
}
func (m *GetSettingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSettingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSettingsResponse proto.InternalMessageInfo

func (m *GetSettingsResponse) GetLowBalanceWarning() string {
	if m != nil {
		return m.LowBalanceWarning
	}
	return ""
}

func (m *GetSettingsResponse) GetDownlinkPrice() float64 {
	if m != nil {
		return m.DownlinkPrice
	}
	return 0
}

func (m *GetSettingsResponse) GetSupernodeIncomeRatio() float64 {
	if m != nil {
		return m.SupernodeIncomeRatio
	}
	return 0
}

func (m *GetSettingsResponse) GetStakingPercentage() float64 {
	if m != nil {
		return m.StakingPercentage
	}
	return 0
}

func (m *GetSettingsResponse) GetStakingExpectedRevenuePercentage() float64 {
	if m != nil {
		return m.StakingExpectedRevenuePercentage
	}
	return 0
}

func (m *GetSettingsResponse) GetCompensation() float64 {
	if m != nil {
		return m.Compensation
	}
	return 0
}

type ModifySettingsRequest struct {
	LowBalanceWarning          *wrappers.Int64Value `protobuf:"bytes,1,opt,name=lowBalanceWarning,proto3" json:"lowBalanceWarning,omitempty"`
	DownlinkFee                *wrappers.Int64Value `protobuf:"bytes,2,opt,name=downlinkFee,proto3" json:"downlinkFee,omitempty"`
	TransactionPercentageShare *wrappers.Int64Value `protobuf:"bytes,3,opt,name=transactionPercentageShare,proto3" json:"transactionPercentageShare,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}             `json:"-"`
	XXX_unrecognized           []byte               `json:"-"`
	XXX_sizecache              int32                `json:"-"`
}

func (m *ModifySettingsRequest) Reset()         { *m = ModifySettingsRequest{} }
func (m *ModifySettingsRequest) String() string { return proto.CompactTextString(m) }
func (*ModifySettingsRequest) ProtoMessage()    {}
func (*ModifySettingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_89f82689bef70059, []int{2}
}

func (m *ModifySettingsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifySettingsRequest.Unmarshal(m, b)
}
func (m *ModifySettingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifySettingsRequest.Marshal(b, m, deterministic)
}
func (m *ModifySettingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifySettingsRequest.Merge(m, src)
}
func (m *ModifySettingsRequest) XXX_Size() int {
	return xxx_messageInfo_ModifySettingsRequest.Size(m)
}
func (m *ModifySettingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifySettingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifySettingsRequest proto.InternalMessageInfo

func (m *ModifySettingsRequest) GetLowBalanceWarning() *wrappers.Int64Value {
	if m != nil {
		return m.LowBalanceWarning
	}
	return nil
}

func (m *ModifySettingsRequest) GetDownlinkFee() *wrappers.Int64Value {
	if m != nil {
		return m.DownlinkFee
	}
	return nil
}

func (m *ModifySettingsRequest) GetTransactionPercentageShare() *wrappers.Int64Value {
	if m != nil {
		return m.TransactionPercentageShare
	}
	return nil
}

type ModifySettingsResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifySettingsResponse) Reset()         { *m = ModifySettingsResponse{} }
func (m *ModifySettingsResponse) String() string { return proto.CompactTextString(m) }
func (*ModifySettingsResponse) ProtoMessage()    {}
func (*ModifySettingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_89f82689bef70059, []int{3}
}

func (m *ModifySettingsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifySettingsResponse.Unmarshal(m, b)
}
func (m *ModifySettingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifySettingsResponse.Marshal(b, m, deterministic)
}
func (m *ModifySettingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifySettingsResponse.Merge(m, src)
}
func (m *ModifySettingsResponse) XXX_Size() int {
	return xxx_messageInfo_ModifySettingsResponse.Size(m)
}
func (m *ModifySettingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifySettingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModifySettingsResponse proto.InternalMessageInfo

func (m *ModifySettingsResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*GetSettingsRequest)(nil), "ui.GetSettingsRequest")
	proto.RegisterType((*GetSettingsResponse)(nil), "ui.GetSettingsResponse")
	proto.RegisterType((*ModifySettingsRequest)(nil), "ui.ModifySettingsRequest")
	proto.RegisterType((*ModifySettingsResponse)(nil), "ui.ModifySettingsResponse")
}

func init() {
	proto.RegisterFile("lpwan-app-server/ui/settings.proto", fileDescriptor_89f82689bef70059)
}

var fileDescriptor_89f82689bef70059 = []byte{
	// 489 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xcd, 0x6e, 0xd3, 0x4e,
	0x10, 0x97, 0xf3, 0xff, 0x13, 0xc1, 0x86, 0xb6, 0xea, 0xb6, 0x0d, 0xc6, 0x20, 0x14, 0x19, 0x21,
	0x55, 0x48, 0xb1, 0x51, 0xa9, 0x38, 0x20, 0x71, 0x41, 0x02, 0x94, 0x43, 0xa5, 0xca, 0x11, 0x70,
	0xe0, 0x60, 0x6d, 0x9c, 0xa9, 0x59, 0xd5, 0x9d, 0x5d, 0xf6, 0x23, 0x86, 0x2b, 0xaf, 0xc0, 0x2b,
	0x71, 0xe3, 0xc8, 0x2b, 0xf0, 0x1c, 0x08, 0x79, 0xbd, 0x2e, 0x49, 0x13, 0xd1, 0xe3, 0xce, 0xef,
	0x63, 0x77, 0x7e, 0x33, 0x4b, 0xe2, 0x4a, 0xd6, 0x0c, 0xc7, 0x4c, 0xca, 0xb1, 0x06, 0xb5, 0x00,
	0x95, 0x5a, 0x9e, 0x6a, 0x30, 0x86, 0x63, 0xa9, 0x13, 0xa9, 0x84, 0x11, 0xb4, 0x67, 0x79, 0x74,
	0xbf, 0x14, 0xa2, 0xac, 0x20, 0x65, 0x92, 0xa7, 0x0c, 0x51, 0x18, 0x66, 0xb8, 0x40, 0xcf, 0x88,
	0x1e, 0x78, 0xd4, 0x9d, 0x66, 0xf6, 0x2c, 0xad, 0x15, 0x93, 0x12, 0x94, 0xc7, 0xe3, 0x7d, 0x42,
	0xdf, 0x80, 0x99, 0x7a, 0xdb, 0x0c, 0x3e, 0x59, 0xd0, 0x26, 0xfe, 0xde, 0x23, 0x7b, 0x2b, 0x65,
	0x2d, 0x05, 0x6a, 0xa0, 0x09, 0xd9, 0xab, 0x44, 0x9d, 0xcf, 0x58, 0xc5, 0xb0, 0x80, 0xbc, 0x66,
	0x0a, 0x39, 0x96, 0x61, 0x30, 0x0a, 0x0e, 0x6f, 0x65, 0xbb, 0x95, 0xa8, 0x5f, 0xb6, 0xc8, 0xfb,
	0x16, 0xa0, 0x8f, 0xc8, 0xf6, 0x5c, 0xd4, 0x58, 0x71, 0x3c, 0xcf, 0xa5, 0xe2, 0x05, 0x84, 0xbd,
	0x51, 0x70, 0x18, 0x64, 0x5b, 0x5d, 0xf5, 0xb4, 0x29, 0xd2, 0x63, 0x32, 0xd4, 0x56, 0x82, 0x42,
	0x31, 0x87, 0x9c, 0x63, 0x21, 0x2e, 0x20, 0x57, 0x4d, 0x1b, 0xe1, 0x7f, 0x8e, 0xbe, 0x7f, 0x89,
	0x4e, 0x1c, 0x98, 0x35, 0x18, 0x1d, 0x13, 0xaa, 0x0d, 0x3b, 0xe7, 0x58, 0xe6, 0x12, 0x54, 0x01,
	0x68, 0x58, 0x09, 0xe1, 0xff, 0x4e, 0xb1, 0xeb, 0x91, 0xd3, 0x4b, 0x80, 0x9e, 0x90, 0x87, 0x1d,
	0x1d, 0x3e, 0x4b, 0x28, 0x0c, 0xcc, 0x73, 0x05, 0x0b, 0x40, 0x0b, 0xcb, 0xfa, 0x1b, 0x4e, 0x3f,
	0xf2, 0xd4, 0x57, 0x9e, 0x99, 0xb5, 0xc4, 0x25, 0xbb, 0x98, 0xdc, 0x2e, 0xc4, 0x85, 0x04, 0xd4,
	0x2e, 0xef, 0xb0, 0xef, 0x74, 0x2b, 0xb5, 0xf8, 0x77, 0x40, 0x0e, 0x4e, 0xc4, 0x9c, 0x9f, 0x7d,
	0xb9, 0x12, 0x30, 0x9d, 0x90, 0xf5, 0xb4, 0x5c, 0x8c, 0x83, 0xa3, 0x7b, 0x49, 0x3b, 0xb2, 0xa4,
	0x1b, 0x59, 0x32, 0x41, 0xf3, 0xec, 0xf8, 0x1d, 0xab, 0x2c, 0x6c, 0xca, 0xf8, 0x05, 0x19, 0x74,
	0x69, 0xbe, 0x86, 0x36, 0xe0, 0x6b, 0x4c, 0x96, 0xf9, 0xf4, 0x03, 0x89, 0x8c, 0x62, 0xa8, 0x59,
	0xd1, 0x3c, 0xf9, 0x6f, 0x83, 0xd3, 0x8f, 0x4c, 0x81, 0xcb, 0xff, 0x1a, 0xb7, 0x7f, 0xc8, 0xe3,
	0x27, 0x64, 0x78, 0xb5, 0x7f, 0xbf, 0x49, 0x43, 0xd2, 0xd7, 0x86, 0x19, 0xab, 0x5d, 0xd7, 0x37,
	0x33, 0x7f, 0x3a, 0xfa, 0x11, 0x90, 0x9d, 0x8e, 0x3c, 0x05, 0xb5, 0x68, 0xd6, 0xe3, 0x2d, 0x19,
	0x2c, 0x2d, 0x23, 0x1d, 0x26, 0x96, 0x27, 0xeb, 0x4b, 0x1b, 0xdd, 0x59, 0xab, 0xb7, 0x77, 0xc5,
	0x07, 0x5f, 0x7f, 0xfe, 0xfa, 0xd6, 0xdb, 0xa1, 0x5b, 0xee, 0x8f, 0x74, 0x5f, 0x88, 0x32, 0xb2,
	0xbd, 0xfa, 0x38, 0x7a, 0xb7, 0x71, 0xd8, 0x38, 0xb0, 0x28, 0xda, 0x04, 0x79, 0xff, 0xd0, 0xf9,
	0xd3, 0x68, 0xd5, 0xff, 0x79, 0xf0, 0x78, 0xd6, 0x77, 0x81, 0x3d, 0xfd, 0x13, 0x00, 0x00, 0xff,
	0xff, 0x3f, 0xfe, 0x28, 0xb2, 0xcc, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SettingsServiceClient is the client API for SettingsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SettingsServiceClient interface {
	GetSettings(ctx context.Context, in *GetSettingsRequest, opts ...grpc.CallOption) (*GetSettingsResponse, error)
	ModifySettings(ctx context.Context, in *ModifySettingsRequest, opts ...grpc.CallOption) (*ModifySettingsResponse, error)
}

type settingsServiceClient struct {
	cc *grpc.ClientConn
}

func NewSettingsServiceClient(cc *grpc.ClientConn) SettingsServiceClient {
	return &settingsServiceClient{cc}
}

func (c *settingsServiceClient) GetSettings(ctx context.Context, in *GetSettingsRequest, opts ...grpc.CallOption) (*GetSettingsResponse, error) {
	out := new(GetSettingsResponse)
	err := c.cc.Invoke(ctx, "/ui.SettingsService/GetSettings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingsServiceClient) ModifySettings(ctx context.Context, in *ModifySettingsRequest, opts ...grpc.CallOption) (*ModifySettingsResponse, error) {
	out := new(ModifySettingsResponse)
	err := c.cc.Invoke(ctx, "/ui.SettingsService/ModifySettings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SettingsServiceServer is the server API for SettingsService service.
type SettingsServiceServer interface {
	GetSettings(context.Context, *GetSettingsRequest) (*GetSettingsResponse, error)
	ModifySettings(context.Context, *ModifySettingsRequest) (*ModifySettingsResponse, error)
}

// UnimplementedSettingsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSettingsServiceServer struct {
}

func (*UnimplementedSettingsServiceServer) GetSettings(ctx context.Context, req *GetSettingsRequest) (*GetSettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSettings not implemented")
}
func (*UnimplementedSettingsServiceServer) ModifySettings(ctx context.Context, req *ModifySettingsRequest) (*ModifySettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifySettings not implemented")
}

func RegisterSettingsServiceServer(s *grpc.Server, srv SettingsServiceServer) {
	s.RegisterService(&_SettingsService_serviceDesc, srv)
}

func _SettingsService_GetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsServiceServer).GetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ui.SettingsService/GetSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsServiceServer).GetSettings(ctx, req.(*GetSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingsService_ModifySettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifySettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsServiceServer).ModifySettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ui.SettingsService/ModifySettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsServiceServer).ModifySettings(ctx, req.(*ModifySettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SettingsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ui.SettingsService",
	HandlerType: (*SettingsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSettings",
			Handler:    _SettingsService_GetSettings_Handler,
		},
		{
			MethodName: "ModifySettings",
			Handler:    _SettingsService_ModifySettings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lpwan-app-server/ui/settings.proto",
}
