// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mxprotocol-server/lpwan-server/networkserver.proto

package ms

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeviceMode int32

const (
	DeviceMode_DV_INACTIVE              DeviceMode = 0
	DeviceMode_DV_FREE_GATEWAYS_LIMITED DeviceMode = 1
	DeviceMode_DV_WHOLE_NETWORK         DeviceMode = 2
	DeviceMode_DV_DELETED               DeviceMode = 3
)

var DeviceMode_name = map[int32]string{
	0: "DV_INACTIVE",
	1: "DV_FREE_GATEWAYS_LIMITED",
	2: "DV_WHOLE_NETWORK",
	3: "DV_DELETED",
}

var DeviceMode_value = map[string]int32{
	"DV_INACTIVE":              0,
	"DV_FREE_GATEWAYS_LIMITED": 1,
	"DV_WHOLE_NETWORK":         2,
	"DV_DELETED":               3,
}

func (x DeviceMode) String() string {
	return proto.EnumName(DeviceMode_name, int32(x))
}

func (DeviceMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c6ae0d8c2cf58792, []int{0}
}

type Category int32

const (
	Category_JOIN_ANS    Category = 0
	Category_MAC_COMMAND Category = 1
	Category_PAYLOAD     Category = 2
	Category_UNKNOWN_PKT Category = 3
)

var Category_name = map[int32]string{
	0: "JOIN_ANS",
	1: "MAC_COMMAND",
	2: "PAYLOAD",
	3: "UNKNOWN_PKT",
}

var Category_value = map[string]int32{
	"JOIN_ANS":    0,
	"MAC_COMMAND": 1,
	"PAYLOAD":     2,
	"UNKNOWN_PKT": 3,
}

func (x Category) String() string {
	return proto.EnumName(Category_name, int32(x))
}

func (Category) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c6ae0d8c2cf58792, []int{1}
}

type DvUsageModeRequest struct {
	DvEui                string   `protobuf:"bytes,1,opt,name=dv_eui,json=dvEui,proto3" json:"dv_eui,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DvUsageModeRequest) Reset()         { *m = DvUsageModeRequest{} }
func (m *DvUsageModeRequest) String() string { return proto.CompactTextString(m) }
func (*DvUsageModeRequest) ProtoMessage()    {}
func (*DvUsageModeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6ae0d8c2cf58792, []int{0}
}

func (m *DvUsageModeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DvUsageModeRequest.Unmarshal(m, b)
}
func (m *DvUsageModeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DvUsageModeRequest.Marshal(b, m, deterministic)
}
func (m *DvUsageModeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DvUsageModeRequest.Merge(m, src)
}
func (m *DvUsageModeRequest) XXX_Size() int {
	return xxx_messageInfo_DvUsageModeRequest.Size(m)
}
func (m *DvUsageModeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DvUsageModeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DvUsageModeRequest proto.InternalMessageInfo

func (m *DvUsageModeRequest) GetDvEui() string {
	if m != nil {
		return m.DvEui
	}
	return ""
}

type GwMac struct {
	GwMac                string   `protobuf:"bytes,1,opt,name=gw_mac,json=gwMac,proto3" json:"gw_mac,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GwMac) Reset()         { *m = GwMac{} }
func (m *GwMac) String() string { return proto.CompactTextString(m) }
func (*GwMac) ProtoMessage()    {}
func (*GwMac) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6ae0d8c2cf58792, []int{1}
}

func (m *GwMac) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GwMac.Unmarshal(m, b)
}
func (m *GwMac) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GwMac.Marshal(b, m, deterministic)
}
func (m *GwMac) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GwMac.Merge(m, src)
}
func (m *GwMac) XXX_Size() int {
	return xxx_messageInfo_GwMac.Size(m)
}
func (m *GwMac) XXX_DiscardUnknown() {
	xxx_messageInfo_GwMac.DiscardUnknown(m)
}

var xxx_messageInfo_GwMac proto.InternalMessageInfo

func (m *GwMac) GetGwMac() string {
	if m != nil {
		return m.GwMac
	}
	return ""
}

type DvUsageModeResponse struct {
	DvMode               DeviceMode `protobuf:"varint,1,opt,name=dv_mode,json=dvMode,proto3,enum=ms.DeviceMode" json:"dv_mode,omitempty"`
	FreeGwMac            []*GwMac   `protobuf:"bytes,2,rep,name=free_gw_mac,json=freeGwMac,proto3" json:"free_gw_mac,omitempty"`
	EnoughBalance        bool       `protobuf:"varint,3,opt,name=enough_balance,json=enoughBalance,proto3" json:"enough_balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DvUsageModeResponse) Reset()         { *m = DvUsageModeResponse{} }
func (m *DvUsageModeResponse) String() string { return proto.CompactTextString(m) }
func (*DvUsageModeResponse) ProtoMessage()    {}
func (*DvUsageModeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6ae0d8c2cf58792, []int{2}
}

func (m *DvUsageModeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DvUsageModeResponse.Unmarshal(m, b)
}
func (m *DvUsageModeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DvUsageModeResponse.Marshal(b, m, deterministic)
}
func (m *DvUsageModeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DvUsageModeResponse.Merge(m, src)
}
func (m *DvUsageModeResponse) XXX_Size() int {
	return xxx_messageInfo_DvUsageModeResponse.Size(m)
}
func (m *DvUsageModeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DvUsageModeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DvUsageModeResponse proto.InternalMessageInfo

func (m *DvUsageModeResponse) GetDvMode() DeviceMode {
	if m != nil {
		return m.DvMode
	}
	return DeviceMode_DV_INACTIVE
}

func (m *DvUsageModeResponse) GetFreeGwMac() []*GwMac {
	if m != nil {
		return m.FreeGwMac
	}
	return nil
}

func (m *DvUsageModeResponse) GetEnoughBalance() bool {
	if m != nil {
		return m.EnoughBalance
	}
	return false
}

type GwUsageModeRequest struct {
	GwMac                string   `protobuf:"bytes,1,opt,name=gw_mac,json=gwMac,proto3" json:"gw_mac,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GwUsageModeRequest) Reset()         { *m = GwUsageModeRequest{} }
func (m *GwUsageModeRequest) String() string { return proto.CompactTextString(m) }
func (*GwUsageModeRequest) ProtoMessage()    {}
func (*GwUsageModeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6ae0d8c2cf58792, []int{3}
}

func (m *GwUsageModeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GwUsageModeRequest.Unmarshal(m, b)
}
func (m *GwUsageModeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GwUsageModeRequest.Marshal(b, m, deterministic)
}
func (m *GwUsageModeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GwUsageModeRequest.Merge(m, src)
}
func (m *GwUsageModeRequest) XXX_Size() int {
	return xxx_messageInfo_GwUsageModeRequest.Size(m)
}
func (m *GwUsageModeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GwUsageModeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GwUsageModeRequest proto.InternalMessageInfo

func (m *GwUsageModeRequest) GetGwMac() string {
	if m != nil {
		return m.GwMac
	}
	return ""
}

type GwUsageModeResponse struct {
	GwMode               string   `protobuf:"bytes,1,opt,name=gw_mode,json=gwMode,proto3" json:"gw_mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GwUsageModeResponse) Reset()         { *m = GwUsageModeResponse{} }
func (m *GwUsageModeResponse) String() string { return proto.CompactTextString(m) }
func (*GwUsageModeResponse) ProtoMessage()    {}
func (*GwUsageModeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6ae0d8c2cf58792, []int{4}
}

func (m *GwUsageModeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GwUsageModeResponse.Unmarshal(m, b)
}
func (m *GwUsageModeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GwUsageModeResponse.Marshal(b, m, deterministic)
}
func (m *GwUsageModeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GwUsageModeResponse.Merge(m, src)
}
func (m *GwUsageModeResponse) XXX_Size() int {
	return xxx_messageInfo_GwUsageModeResponse.Size(m)
}
func (m *GwUsageModeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GwUsageModeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GwUsageModeResponse proto.InternalMessageInfo

func (m *GwUsageModeResponse) GetGwMode() string {
	if m != nil {
		return m.GwMode
	}
	return ""
}

type DlPkt struct {
	DlIdNs               string   `protobuf:"bytes,1,opt,name=dl_id_ns,json=dlIdNs,proto3" json:"dl_id_ns,omitempty"`
	GwMac                string   `protobuf:"bytes,2,opt,name=gw_mac,json=gwMac,proto3" json:"gw_mac,omitempty"`
	DevEui               string   `protobuf:"bytes,3,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	TokenDlFrm1          int64    `protobuf:"varint,4,opt,name=token_dl_frm1,json=tokenDlFrm1,proto3" json:"token_dl_frm1,omitempty"`
	TokenDlFrm2          int64    `protobuf:"varint,5,opt,name=token_dl_frm2,json=tokenDlFrm2,proto3" json:"token_dl_frm2,omitempty"`
	CreateAt             string   `protobuf:"bytes,6,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	Nonce                int64    `protobuf:"varint,7,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Size                 float64  `protobuf:"fixed64,8,opt,name=size,proto3" json:"size,omitempty"`
	Category             Category `protobuf:"varint,9,opt,name=category,proto3,enum=ms.Category" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DlPkt) Reset()         { *m = DlPkt{} }
func (m *DlPkt) String() string { return proto.CompactTextString(m) }
func (*DlPkt) ProtoMessage()    {}
func (*DlPkt) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6ae0d8c2cf58792, []int{5}
}

func (m *DlPkt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DlPkt.Unmarshal(m, b)
}
func (m *DlPkt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DlPkt.Marshal(b, m, deterministic)
}
func (m *DlPkt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DlPkt.Merge(m, src)
}
func (m *DlPkt) XXX_Size() int {
	return xxx_messageInfo_DlPkt.Size(m)
}
func (m *DlPkt) XXX_DiscardUnknown() {
	xxx_messageInfo_DlPkt.DiscardUnknown(m)
}

var xxx_messageInfo_DlPkt proto.InternalMessageInfo

func (m *DlPkt) GetDlIdNs() string {
	if m != nil {
		return m.DlIdNs
	}
	return ""
}

func (m *DlPkt) GetGwMac() string {
	if m != nil {
		return m.GwMac
	}
	return ""
}

func (m *DlPkt) GetDevEui() string {
	if m != nil {
		return m.DevEui
	}
	return ""
}

func (m *DlPkt) GetTokenDlFrm1() int64 {
	if m != nil {
		return m.TokenDlFrm1
	}
	return 0
}

func (m *DlPkt) GetTokenDlFrm2() int64 {
	if m != nil {
		return m.TokenDlFrm2
	}
	return 0
}

func (m *DlPkt) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

func (m *DlPkt) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *DlPkt) GetSize() float64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *DlPkt) GetCategory() Category {
	if m != nil {
		return m.Category
	}
	return Category_JOIN_ANS
}

type DlPktSentRequest struct {
	DlPkt                *DlPkt   `protobuf:"bytes,1,opt,name=dl_pkt,json=dlPkt,proto3" json:"dl_pkt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DlPktSentRequest) Reset()         { *m = DlPktSentRequest{} }
func (m *DlPktSentRequest) String() string { return proto.CompactTextString(m) }
func (*DlPktSentRequest) ProtoMessage()    {}
func (*DlPktSentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6ae0d8c2cf58792, []int{6}
}

func (m *DlPktSentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DlPktSentRequest.Unmarshal(m, b)
}
func (m *DlPktSentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DlPktSentRequest.Marshal(b, m, deterministic)
}
func (m *DlPktSentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DlPktSentRequest.Merge(m, src)
}
func (m *DlPktSentRequest) XXX_Size() int {
	return xxx_messageInfo_DlPktSentRequest.Size(m)
}
func (m *DlPktSentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DlPktSentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DlPktSentRequest proto.InternalMessageInfo

func (m *DlPktSentRequest) GetDlPkt() *DlPkt {
	if m != nil {
		return m.DlPkt
	}
	return nil
}

type DlPktSentResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DlPktSentResponse) Reset()         { *m = DlPktSentResponse{} }
func (m *DlPktSentResponse) String() string { return proto.CompactTextString(m) }
func (*DlPktSentResponse) ProtoMessage()    {}
func (*DlPktSentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6ae0d8c2cf58792, []int{7}
}

func (m *DlPktSentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DlPktSentResponse.Unmarshal(m, b)
}
func (m *DlPktSentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DlPktSentResponse.Marshal(b, m, deterministic)
}
func (m *DlPktSentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DlPktSentResponse.Merge(m, src)
}
func (m *DlPktSentResponse) XXX_Size() int {
	return xxx_messageInfo_DlPktSentResponse.Size(m)
}
func (m *DlPktSentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DlPktSentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DlPktSentResponse proto.InternalMessageInfo

type UlPkt struct {
	UlIdNs               int64    `protobuf:"varint,1,opt,name=ul_id_ns,json=ulIdNs,proto3" json:"ul_id_ns,omitempty"`
	GwMac                []*GwMac `protobuf:"bytes,2,rep,name=gw_mac,json=gwMac,proto3" json:"gw_mac,omitempty"`
	DevEui               string   `protobuf:"bytes,3,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Nonce                int64    `protobuf:"varint,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Size                 float64  `protobuf:"fixed64,7,opt,name=size,proto3" json:"size,omitempty"`
	Category             Category `protobuf:"varint,9,opt,name=category,proto3,enum=ms.Category" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UlPkt) Reset()         { *m = UlPkt{} }
func (m *UlPkt) String() string { return proto.CompactTextString(m) }
func (*UlPkt) ProtoMessage()    {}
func (*UlPkt) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6ae0d8c2cf58792, []int{8}
}

func (m *UlPkt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UlPkt.Unmarshal(m, b)
}
func (m *UlPkt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UlPkt.Marshal(b, m, deterministic)
}
func (m *UlPkt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UlPkt.Merge(m, src)
}
func (m *UlPkt) XXX_Size() int {
	return xxx_messageInfo_UlPkt.Size(m)
}
func (m *UlPkt) XXX_DiscardUnknown() {
	xxx_messageInfo_UlPkt.DiscardUnknown(m)
}

var xxx_messageInfo_UlPkt proto.InternalMessageInfo

func (m *UlPkt) GetUlIdNs() int64 {
	if m != nil {
		return m.UlIdNs
	}
	return 0
}

func (m *UlPkt) GetGwMac() []*GwMac {
	if m != nil {
		return m.GwMac
	}
	return nil
}

func (m *UlPkt) GetDevEui() string {
	if m != nil {
		return m.DevEui
	}
	return ""
}

func (m *UlPkt) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UlPkt) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *UlPkt) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *UlPkt) GetSize() float64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *UlPkt) GetCategory() Category {
	if m != nil {
		return m.Category
	}
	return Category_JOIN_ANS
}

type UlPktSentRequest struct {
	UlPkt                *UlPkt   `protobuf:"bytes,1,opt,name=ul_pkt,json=ulPkt,proto3" json:"ul_pkt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UlPktSentRequest) Reset()         { *m = UlPktSentRequest{} }
func (m *UlPktSentRequest) String() string { return proto.CompactTextString(m) }
func (*UlPktSentRequest) ProtoMessage()    {}
func (*UlPktSentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6ae0d8c2cf58792, []int{9}
}

func (m *UlPktSentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UlPktSentRequest.Unmarshal(m, b)
}
func (m *UlPktSentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UlPktSentRequest.Marshal(b, m, deterministic)
}
func (m *UlPktSentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UlPktSentRequest.Merge(m, src)
}
func (m *UlPktSentRequest) XXX_Size() int {
	return xxx_messageInfo_UlPktSentRequest.Size(m)
}
func (m *UlPktSentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UlPktSentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UlPktSentRequest proto.InternalMessageInfo

func (m *UlPktSentRequest) GetUlPkt() *UlPkt {
	if m != nil {
		return m.UlPkt
	}
	return nil
}

type UlPktSentResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UlPktSentResponse) Reset()         { *m = UlPktSentResponse{} }
func (m *UlPktSentResponse) String() string { return proto.CompactTextString(m) }
func (*UlPktSentResponse) ProtoMessage()    {}
func (*UlPktSentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6ae0d8c2cf58792, []int{10}
}

func (m *UlPktSentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UlPktSentResponse.Unmarshal(m, b)
}
func (m *UlPktSentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UlPktSentResponse.Marshal(b, m, deterministic)
}
func (m *UlPktSentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UlPktSentResponse.Merge(m, src)
}
func (m *UlPktSentResponse) XXX_Size() int {
	return xxx_messageInfo_UlPktSentResponse.Size(m)
}
func (m *UlPktSentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UlPktSentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UlPktSentResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("ms.DeviceMode", DeviceMode_name, DeviceMode_value)
	proto.RegisterEnum("ms.Category", Category_name, Category_value)
	proto.RegisterType((*DvUsageModeRequest)(nil), "ms.DvUsageModeRequest")
	proto.RegisterType((*GwMac)(nil), "ms.GwMac")
	proto.RegisterType((*DvUsageModeResponse)(nil), "ms.DvUsageModeResponse")
	proto.RegisterType((*GwUsageModeRequest)(nil), "ms.GwUsageModeRequest")
	proto.RegisterType((*GwUsageModeResponse)(nil), "ms.GwUsageModeResponse")
	proto.RegisterType((*DlPkt)(nil), "ms.DlPkt")
	proto.RegisterType((*DlPktSentRequest)(nil), "ms.DlPktSentRequest")
	proto.RegisterType((*DlPktSentResponse)(nil), "ms.DlPktSentResponse")
	proto.RegisterType((*UlPkt)(nil), "ms.UlPkt")
	proto.RegisterType((*UlPktSentRequest)(nil), "ms.UlPktSentRequest")
	proto.RegisterType((*UlPktSentResponse)(nil), "ms.UlPktSentResponse")
}

func init() {
	proto.RegisterFile("mxprotocol-server/lpwan-server/networkserver.proto", fileDescriptor_c6ae0d8c2cf58792)
}

var fileDescriptor_c6ae0d8c2cf58792 = []byte{
	// 727 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xdd, 0x6e, 0xea, 0x46,
	0x10, 0xc7, 0x8f, 0xe1, 0xd8, 0xe0, 0xe1, 0x1c, 0xea, 0x6e, 0x48, 0x63, 0xa5, 0x1f, 0x42, 0x96,
	0xaa, 0xd2, 0x54, 0xa5, 0x0a, 0xed, 0x45, 0xaf, 0x22, 0xb9, 0xd8, 0xa1, 0x34, 0xd8, 0x44, 0x06,
	0x83, 0x72, 0xb5, 0x72, 0xbc, 0x1b, 0x8a, 0x30, 0x36, 0xf5, 0x07, 0xb4, 0x7d, 0x80, 0x5e, 0xf4,
	0xaa, 0x2f, 0xd9, 0xf7, 0xa8, 0x76, 0x8d, 0x13, 0x07, 0x90, 0x2a, 0x9d, 0x1b, 0xcc, 0xce, 0xfc,
	0x67, 0x67, 0xf7, 0x37, 0x3b, 0x03, 0xbd, 0xf5, 0xef, 0x9b, 0x38, 0x4a, 0x23, 0x3f, 0x0a, 0xbe,
	0x4d, 0x68, 0xbc, 0xa5, 0xf1, 0x77, 0xc1, 0x66, 0xe7, 0x85, 0xc5, 0x22, 0xa4, 0xe9, 0x2e, 0x8a,
	0x57, 0xf9, 0xaa, 0xcb, 0xa5, 0xa8, 0xb2, 0x4e, 0xb4, 0x6f, 0x00, 0x19, 0x5b, 0x37, 0xf1, 0x16,
	0xd4, 0x8a, 0x08, 0x75, 0xe8, 0x6f, 0x19, 0x4d, 0x52, 0x74, 0x0e, 0x12, 0xd9, 0x62, 0x9a, 0x2d,
	0x55, 0xa1, 0x2d, 0x74, 0x64, 0x47, 0x24, 0x5b, 0x33, 0x5b, 0x6a, 0x5f, 0x80, 0x38, 0xd8, 0x59,
	0x9e, 0xcf, 0xfc, 0x8b, 0x1d, 0x5e, 0x7b, 0x7e, 0xe1, 0x5f, 0x30, 0xb3, 0xf6, 0x8f, 0x00, 0x67,
	0xaf, 0x76, 0x4b, 0x36, 0x51, 0x98, 0x50, 0xf4, 0x15, 0xd4, 0xc8, 0x16, 0xaf, 0x23, 0x42, 0xb9,
	0xbe, 0xd9, 0x6b, 0x76, 0xd7, 0x49, 0xd7, 0xa0, 0xdb, 0xa5, 0x9f, 0x0b, 0x25, 0xb2, 0x65, 0x5f,
	0xf4, 0x35, 0x34, 0x9e, 0x62, 0x4a, 0xf1, 0x7e, 0xf3, 0x4a, 0xbb, 0xda, 0x69, 0xf4, 0x64, 0x26,
	0xe6, 0x79, 0x1d, 0x99, 0x79, 0xf3, 0x23, 0x7c, 0x09, 0x4d, 0x1a, 0x46, 0xd9, 0xe2, 0x57, 0xfc,
	0xe8, 0x05, 0x5e, 0xe8, 0x53, 0xb5, 0xda, 0x16, 0x3a, 0x75, 0xe7, 0x7d, 0x6e, 0xfd, 0x29, 0x37,
	0xb2, 0xfb, 0x0d, 0x76, 0xa7, 0xee, 0x77, 0xea, 0xfc, 0x5d, 0x38, 0x7b, 0x25, 0xde, 0x1f, 0xff,
	0x02, 0x6a, 0x4c, 0x5d, 0x1c, 0x5f, 0x76, 0xa4, 0xc5, 0x8e, 0x09, 0xb4, 0xbf, 0x2b, 0x20, 0x1a,
	0xc1, 0xfd, 0x2a, 0x45, 0x2a, 0xd4, 0x49, 0x80, 0x97, 0x04, 0x87, 0x49, 0xa1, 0x21, 0xc1, 0x90,
	0xd8, 0x49, 0x29, 0x55, 0xa5, 0x94, 0x8a, 0xed, 0x49, 0x68, 0x8e, 0xb8, 0xba, 0xd7, 0x53, 0xc6,
	0x18, 0x69, 0xf0, 0x3e, 0x8d, 0x56, 0x34, 0xc4, 0x24, 0xc0, 0x4f, 0xf1, 0xfa, 0x5a, 0x7d, 0xdb,
	0x16, 0x3a, 0x55, 0xa7, 0xc1, 0x8d, 0x46, 0x70, 0x1b, 0xaf, 0xaf, 0x0f, 0x35, 0x3d, 0x55, 0x3c,
	0xd4, 0xf4, 0xd0, 0xa7, 0x20, 0xfb, 0x31, 0xf5, 0x52, 0x8a, 0xbd, 0x54, 0x95, 0x78, 0x8a, 0x7a,
	0x6e, 0xd0, 0x53, 0xd4, 0x02, 0x31, 0x8c, 0x18, 0xb3, 0x1a, 0x0f, 0xcc, 0x17, 0x08, 0xc1, 0xdb,
	0x64, 0xf9, 0x27, 0x55, 0xeb, 0x6d, 0xa1, 0x23, 0x38, 0xfc, 0x3f, 0xea, 0x40, 0xdd, 0xf7, 0x52,
	0xba, 0x88, 0xe2, 0x3f, 0x54, 0x99, 0xd7, 0xee, 0x1d, 0x2b, 0x47, 0x7f, 0x6f, 0x73, 0x9e, 0xbd,
	0xda, 0x0f, 0xa0, 0x70, 0x16, 0x13, 0x1a, 0xa6, 0x05, 0xe7, 0x36, 0x48, 0x24, 0xc0, 0x9b, 0x55,
	0xca, 0xa1, 0xec, 0x4b, 0xc9, 0x55, 0x8e, 0x48, 0xd8, 0x47, 0x3b, 0x83, 0x8f, 0x4b, 0x51, 0x39,
	0x70, 0xed, 0x5f, 0x01, 0x44, 0xb7, 0xe0, 0x9a, 0x95, 0xb9, 0x56, 0x1d, 0x29, 0xcb, 0xb9, 0xb6,
	0x4b, 0x5c, 0x0f, 0x5e, 0xc9, 0xff, 0x21, 0x6e, 0x81, 0xc8, 0x49, 0x71, 0xb4, 0xb2, 0x93, 0x2f,
	0xd0, 0xe7, 0x00, 0x39, 0x1f, 0xc2, 0x88, 0x89, 0xdc, 0xb5, 0x47, 0x48, 0xca, 0xc8, 0xa4, 0x53,
	0xc8, 0x6a, 0x1f, 0x8a, 0xcc, 0x3d, 0x81, 0x2c, 0x3b, 0x42, 0xe6, 0xe6, 0xc8, 0xb2, 0x02, 0x99,
	0x7b, 0x88, 0xec, 0xca, 0x03, 0x78, 0xe9, 0x27, 0xf4, 0x11, 0x34, 0x8c, 0x19, 0x1e, 0xda, 0x7a,
	0x7f, 0x3a, 0x9c, 0x99, 0xca, 0x1b, 0xf4, 0x19, 0xa8, 0xc6, 0x0c, 0xdf, 0x3a, 0xa6, 0x89, 0x07,
	0xfa, 0xd4, 0x9c, 0xeb, 0x0f, 0x13, 0x3c, 0x1a, 0x5a, 0xc3, 0xa9, 0x69, 0x28, 0x02, 0x6a, 0x81,
	0x62, 0xcc, 0xf0, 0xfc, 0xe7, 0xf1, 0xc8, 0xc4, 0xb6, 0x39, 0x9d, 0x8f, 0x9d, 0x3b, 0xa5, 0x82,
	0x9a, 0x00, 0xc6, 0x0c, 0x1b, 0xe6, 0xc8, 0x64, 0xaa, 0xea, 0xd5, 0x00, 0xea, 0xc5, 0x1d, 0xd0,
	0x3b, 0xa8, 0xff, 0x32, 0x1e, 0xda, 0x58, 0xb7, 0x27, 0xca, 0x1b, 0x96, 0xce, 0xd2, 0xfb, 0xb8,
	0x3f, 0xb6, 0x2c, 0xdd, 0x66, 0x1b, 0x36, 0xa0, 0x76, 0xaf, 0x3f, 0x8c, 0xc6, 0xba, 0xa1, 0x54,
	0x98, 0xd7, 0xb5, 0xef, 0xec, 0xf1, 0xdc, 0xc6, 0xf7, 0x77, 0x53, 0xa5, 0xda, 0xfb, 0xab, 0x02,
	0x8a, 0xd5, 0xb3, 0x26, 0x7c, 0x16, 0xb1, 0xdf, 0xa5, 0x4f, 0xd1, 0x0d, 0x34, 0x4a, 0xa3, 0x03,
	0x7d, 0xc2, 0x5f, 0xca, 0xd1, 0x64, 0xba, 0xbc, 0x38, 0xb2, 0xef, 0x9b, 0xf4, 0x06, 0x1a, 0xa5,
	0xde, 0xcd, 0xe3, 0x8f, 0x3b, 0x3f, 0x8f, 0x3f, 0xd5, 0xe4, 0x3f, 0x82, 0xfc, 0xfc, 0x10, 0x51,
	0xeb, 0xf9, 0x9d, 0x96, 0x4a, 0x73, 0x79, 0x7e, 0x60, 0x7d, 0x89, 0x74, 0x5f, 0x47, 0xba, 0x27,
	0x23, 0x8f, 0x8a, 0xf6, 0x28, 0xf1, 0x39, 0xfc, 0xfd, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc0,
	0xbd, 0xab, 0xd9, 0xbd, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// M2MServerServiceClient is the client API for M2MServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type M2MServerServiceClient interface {
	DvUsageMode(ctx context.Context, in *DvUsageModeRequest, opts ...grpc.CallOption) (*DvUsageModeResponse, error)
	GwUsageMode(ctx context.Context, in *GwUsageModeRequest, opts ...grpc.CallOption) (*GwUsageModeResponse, error)
	DlPktSent(ctx context.Context, in *DlPktSentRequest, opts ...grpc.CallOption) (*DlPktSentResponse, error)
	UlPktSent(ctx context.Context, in *UlPktSentRequest, opts ...grpc.CallOption) (*UlPktSentResponse, error)
}

type m2MServerServiceClient struct {
	cc *grpc.ClientConn
}

func NewM2MServerServiceClient(cc *grpc.ClientConn) M2MServerServiceClient {
	return &m2MServerServiceClient{cc}
}

func (c *m2MServerServiceClient) DvUsageMode(ctx context.Context, in *DvUsageModeRequest, opts ...grpc.CallOption) (*DvUsageModeResponse, error) {
	out := new(DvUsageModeResponse)
	err := c.cc.Invoke(ctx, "/ms.M2MServerService/DvUsageMode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *m2MServerServiceClient) GwUsageMode(ctx context.Context, in *GwUsageModeRequest, opts ...grpc.CallOption) (*GwUsageModeResponse, error) {
	out := new(GwUsageModeResponse)
	err := c.cc.Invoke(ctx, "/ms.M2MServerService/GwUsageMode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *m2MServerServiceClient) DlPktSent(ctx context.Context, in *DlPktSentRequest, opts ...grpc.CallOption) (*DlPktSentResponse, error) {
	out := new(DlPktSentResponse)
	err := c.cc.Invoke(ctx, "/ms.M2MServerService/DlPktSent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *m2MServerServiceClient) UlPktSent(ctx context.Context, in *UlPktSentRequest, opts ...grpc.CallOption) (*UlPktSentResponse, error) {
	out := new(UlPktSentResponse)
	err := c.cc.Invoke(ctx, "/ms.M2MServerService/UlPktSent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// M2MServerServiceServer is the server API for M2MServerService service.
type M2MServerServiceServer interface {
	DvUsageMode(context.Context, *DvUsageModeRequest) (*DvUsageModeResponse, error)
	GwUsageMode(context.Context, *GwUsageModeRequest) (*GwUsageModeResponse, error)
	DlPktSent(context.Context, *DlPktSentRequest) (*DlPktSentResponse, error)
	UlPktSent(context.Context, *UlPktSentRequest) (*UlPktSentResponse, error)
}

// UnimplementedM2MServerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedM2MServerServiceServer struct {
}

func (*UnimplementedM2MServerServiceServer) DvUsageMode(ctx context.Context, req *DvUsageModeRequest) (*DvUsageModeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DvUsageMode not implemented")
}
func (*UnimplementedM2MServerServiceServer) GwUsageMode(ctx context.Context, req *GwUsageModeRequest) (*GwUsageModeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GwUsageMode not implemented")
}
func (*UnimplementedM2MServerServiceServer) DlPktSent(ctx context.Context, req *DlPktSentRequest) (*DlPktSentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DlPktSent not implemented")
}
func (*UnimplementedM2MServerServiceServer) UlPktSent(ctx context.Context, req *UlPktSentRequest) (*UlPktSentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UlPktSent not implemented")
}

func RegisterM2MServerServiceServer(s *grpc.Server, srv M2MServerServiceServer) {
	s.RegisterService(&_M2MServerService_serviceDesc, srv)
}

func _M2MServerService_DvUsageMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DvUsageModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(M2MServerServiceServer).DvUsageMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ms.M2MServerService/DvUsageMode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(M2MServerServiceServer).DvUsageMode(ctx, req.(*DvUsageModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _M2MServerService_GwUsageMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GwUsageModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(M2MServerServiceServer).GwUsageMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ms.M2MServerService/GwUsageMode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(M2MServerServiceServer).GwUsageMode(ctx, req.(*GwUsageModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _M2MServerService_DlPktSent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DlPktSentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(M2MServerServiceServer).DlPktSent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ms.M2MServerService/DlPktSent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(M2MServerServiceServer).DlPktSent(ctx, req.(*DlPktSentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _M2MServerService_UlPktSent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UlPktSentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(M2MServerServiceServer).UlPktSent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ms.M2MServerService/UlPktSent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(M2MServerServiceServer).UlPktSent(ctx, req.(*UlPktSentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _M2MServerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ms.M2MServerService",
	HandlerType: (*M2MServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DvUsageMode",
			Handler:    _M2MServerService_DvUsageMode_Handler,
		},
		{
			MethodName: "GwUsageMode",
			Handler:    _M2MServerService_GwUsageMode_Handler,
		},
		{
			MethodName: "DlPktSent",
			Handler:    _M2MServerService_DlPktSent_Handler,
		},
		{
			MethodName: "UlPktSent",
			Handler:    _M2MServerService_UlPktSent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mxprotocol-server/lpwan-server/networkserver.proto",
}
